/**
 * @author generated by eTrice
 *
 * Source File of ActorClass ACANService
 * 
 */

#include "ACANService.h"

#include "modelbase/etActor.h"
#include "debugging/etLogger.h"
#include "debugging/etMSCLogger.h"
#include "etUnit/etUnit.h"
#include "base/etMemory.h"

#include "room/basic/service/can/PCANRx.h"
#include "room/basic/service/can/PCANTx.h"
#include "room/basic/service/timing/PTimer.h"

#include "ACANService_Utils.h"

/*--------------------- begin user code ---------------------*/
/*uc3 */
#include "pclCANService.h"
/*--------------------- end user code ---------------------*/

/* interface item IDs */
enum interface_items {
	IFITEM_timer = 1,
	IFITEM_canTx = 2,
	IFITEM_canRx = 3
};

/* state IDs */
enum state_ids {
	NO_STATE = 0,
	STATE_TOP = 1,
	STATE_Operational = 2,
	STATE_MAX = 3
};

/* transition chains */
enum chain_ids {
	CHAIN_TRANS_INITIAL_TO__Operational = 1,
	CHAIN_TRANS_tr0_FROM_Operational_TO_Operational_BY_sendMsgcanTx_tr0 = 2,
	CHAIN_TRANS_tr1_FROM_Operational_TO_Operational_BY_initcanTx_tr1 = 3,
	CHAIN_TRANS_tr2_FROM_Operational_TO_Operational_BY_initcanRx_tr2 = 4,
	CHAIN_TRANS_tr3_FROM_Operational_TO_Operational_BY_timeouttimer_tr3 = 5,
	CHAIN_TRANS_tr4_FROM_Operational_TO_Operational_BY_listenOnMsgcanRx_tr4 = 6
};

/* triggers */
enum triggers {
	POLLING = 0,
	TRIG_timer__timeout = IFITEM_timer + EVT_SHIFT*PTimer_OUT_timeout,
	TRIG_canTx__init = IFITEM_canTx + EVT_SHIFT*PCANTx_IN_init,
	TRIG_canTx__sendMsg = IFITEM_canTx + EVT_SHIFT*PCANTx_IN_sendMsg,
	TRIG_canTx__resendMsg = IFITEM_canTx + EVT_SHIFT*PCANTx_IN_resendMsg,
	TRIG_canRx__init = IFITEM_canRx + EVT_SHIFT*PCANRx_IN_init,
	TRIG_canRx__readMsg = IFITEM_canRx + EVT_SHIFT*PCANRx_IN_readMsg,
	TRIG_canRx__listenOnMsg = IFITEM_canRx + EVT_SHIFT*PCANRx_IN_listenOnMsg,
	TRIG_canRx__transmitRequest = IFITEM_canRx + EVT_SHIFT*PCANRx_IN_transmitRequest
};


static void setState(ACANService* self, etInt16 new_state) {
	self->state = new_state;
}

static etInt16 getState(ACANService* self) {
	return self->state;
}

/* Entry and Exit Codes */

/* Action Codes */
static void action_TRANS_INITIAL_TO__Operational(ACANService* self) {
	timer_startTimer(pollTime);
	pclCANInitNodes();
}
static void action_TRANS_tr0_FROM_Operational_TO_Operational_BY_sendMsgcanTx_tr0(ACANService* self, const InterfaceItemBase* ifitem, pclCANMsg* data) {
	uint32 c;
	
	c =txData[((etReplSubPort*)ifitem)->index].channel;
	pclCANSendMsg(c,data);
}
static void action_TRANS_tr1_FROM_Operational_TO_Operational_BY_initcanTx_tr1(ACANService* self, const InterfaceItemBase* ifitem, uint32 data) {
	txData[((etReplSubPort*)ifitem)->index].channel = data;
	pclCANInitMO(data);
}
static void action_TRANS_tr2_FROM_Operational_TO_Operational_BY_initcanRx_tr2(ACANService* self, const InterfaceItemBase* ifitem, uint32 data) {
	rxData[((etReplSubPort*)ifitem)->index].channel = data;
	pclCANInitMO(data);
}
static void action_TRANS_tr3_FROM_Operational_TO_Operational_BY_timeouttimer_tr3(ACANService* self, const InterfaceItemBase* ifitem) {
	pollAllRxMsgs();
}
static void action_TRANS_tr4_FROM_Operational_TO_Operational_BY_listenOnMsgcanRx_tr4(ACANService* self, const InterfaceItemBase* ifitem, pclCANMsg* data) {
	uint32 c;
	
	c =rxData[((etReplSubPort*)ifitem)->index].channel;
	pclCANListenOnMsg(c,data);
}

/**
 * calls exit codes while exiting from the current state to one of its
 * parent states while remembering the history
 * @param current__et - the current state
 * @param to - the final parent state
 */
static void exitTo(ACANService* self, etInt16 current__et, etInt16 to) {
	while (current__et!=to) {
		switch (current__et) {
			case STATE_Operational:
				self->history[STATE_TOP] = STATE_Operational;
				current__et = STATE_TOP;
				break;
			default:
				/* should not occur */
				break;
		}
	}
}

/**
 * calls action, entry and exit codes along a transition chain. The generic data are cast to typed data
 * matching the trigger of this chain. The ID of the final state is returned
 * @param chain__et - the chain ID
 * @param generic_data__et - the generic data pointer
 * @return the +/- ID of the final state either with a positive sign, that indicates to execute the state's entry code, or a negative sign vice versa
 */
static etInt16 executeTransitionChain(ACANService* self, int chain__et, const InterfaceItemBase* ifitem, void* generic_data__et) {
	switch (chain__et) {
		case CHAIN_TRANS_INITIAL_TO__Operational:
		{
			action_TRANS_INITIAL_TO__Operational(self);
			return STATE_Operational;
		}
		case CHAIN_TRANS_tr0_FROM_Operational_TO_Operational_BY_sendMsgcanTx_tr0:
		{
			pclCANMsg* data = ((pclCANMsg*) generic_data__et);
			action_TRANS_tr0_FROM_Operational_TO_Operational_BY_sendMsgcanTx_tr0(self, ifitem, data);
			return STATE_Operational;
		}
		case CHAIN_TRANS_tr1_FROM_Operational_TO_Operational_BY_initcanTx_tr1:
		{
			uint32 data = *((uint32*) generic_data__et);
			action_TRANS_tr1_FROM_Operational_TO_Operational_BY_initcanTx_tr1(self, ifitem, data);
			return STATE_Operational;
		}
		case CHAIN_TRANS_tr2_FROM_Operational_TO_Operational_BY_initcanRx_tr2:
		{
			uint32 data = *((uint32*) generic_data__et);
			action_TRANS_tr2_FROM_Operational_TO_Operational_BY_initcanRx_tr2(self, ifitem, data);
			return STATE_Operational;
		}
		case CHAIN_TRANS_tr3_FROM_Operational_TO_Operational_BY_timeouttimer_tr3:
		{
			action_TRANS_tr3_FROM_Operational_TO_Operational_BY_timeouttimer_tr3(self, ifitem);
			return STATE_Operational;
		}
		case CHAIN_TRANS_tr4_FROM_Operational_TO_Operational_BY_listenOnMsgcanRx_tr4:
		{
			pclCANMsg* data = ((pclCANMsg*) generic_data__et);
			action_TRANS_tr4_FROM_Operational_TO_Operational_BY_listenOnMsgcanRx_tr4(self, ifitem, data);
			return STATE_Operational;
		}
			default:
				/* should not occur */
				break;
	}
	return NO_STATE;
}

/**
 * calls entry codes while entering a state's history. The ID of the final leaf state is returned
 * @param state__et - the state which is entered
 * @return - the ID of the final leaf state
 */
static etInt16 enterHistory(ACANService* self, etInt16 state__et) {
	boolean skip_entry__et = ET_FALSE;
	if (state__et >= STATE_MAX) {
		state__et = (etInt16) (state__et - STATE_MAX);
		skip_entry__et = ET_TRUE;
	}
	while (ET_TRUE) {
		switch (state__et) {
			case STATE_Operational:
				/* in leaf state: return state id */
				return STATE_Operational;
			case STATE_TOP:
				state__et = self->history[STATE_TOP];
				break;
			default:
				/* should not occur */
				break;
		}
		skip_entry__et = ET_FALSE;
	}
	/* return NO_STATE; // required by CDT but detected as unreachable by JDT because of while (true) */
}

static void ACANService_executeInitTransition(ACANService* self) {
	int chain__et = CHAIN_TRANS_INITIAL_TO__Operational;
	etInt16 next__et = executeTransitionChain(self, chain__et, NULL, NULL);
	next__et = enterHistory(self, next__et);
	setState(self, next__et);
}

/* receiveEvent contains the main implementation of the FSM */
static void ACANService_receiveEvent(ACANService* self, InterfaceItemBase* ifitem, int evt, void* generic_data__et) {
	int trigger__et = ifitem->localId + EVT_SHIFT*evt;
	int chain__et = NOT_CAUGHT;
	etInt16 catching_state__et = NO_STATE;
	((void)trigger__et);	/* avoids unused warning */
	
	if (!handleSystemEvent(ifitem, evt, generic_data__et)) {
		switch (getState(self)) {
			case STATE_Operational:
				switch(trigger__et) {
						case TRIG_canTx__sendMsg:
							{
								chain__et = CHAIN_TRANS_tr0_FROM_Operational_TO_Operational_BY_sendMsgcanTx_tr0;
								catching_state__et = STATE_TOP;
							}
						break;
						case TRIG_canTx__init:
							{
								chain__et = CHAIN_TRANS_tr1_FROM_Operational_TO_Operational_BY_initcanTx_tr1;
								catching_state__et = STATE_TOP;
							}
						break;
						case TRIG_canRx__init:
							{
								chain__et = CHAIN_TRANS_tr2_FROM_Operational_TO_Operational_BY_initcanRx_tr2;
								catching_state__et = STATE_TOP;
							}
						break;
						case TRIG_timer__timeout:
							{
								chain__et = CHAIN_TRANS_tr3_FROM_Operational_TO_Operational_BY_timeouttimer_tr3;
								catching_state__et = STATE_TOP;
							}
						break;
						case TRIG_canRx__listenOnMsg:
							{
								chain__et = CHAIN_TRANS_tr4_FROM_Operational_TO_Operational_BY_listenOnMsgcanRx_tr4;
								catching_state__et = STATE_TOP;
							}
						break;
						default:
							/* should not occur */
							break;
				}
				break;
			default:
				/* should not occur */
				break;
		}
	}
	if (chain__et != NOT_CAUGHT) {
		exitTo(self, getState(self), catching_state__et);
		{
			etInt16 next__et = executeTransitionChain(self, chain__et, ifitem, generic_data__et);
			next__et = enterHistory(self, next__et);
			setState(self, next__et);
		}
	}
}

void ACANService_init(ACANService* self){
	ET_MSC_LOGGER_SYNC_ENTRY("ACANService", "init")
	self->state = STATE_TOP;
	{
		int i;
		for (i=0; i<ACANSERVICE_HISTORY_SIZE; ++i)
			self->history[i] = NO_STATE;
	}
	ACANService_executeInitTransition(self);
	ET_MSC_LOGGER_SYNC_EXIT
}


void ACANService_receiveMessage(void* self, const void* ifitem, const etMessage* msg){
	ET_MSC_LOGGER_SYNC_ENTRY("ACANService", "_receiveMessage")
	
	ACANService_receiveEvent(self, (etPort*)ifitem, msg->evtID, (void*)(((char*)msg)+MEM_CEIL(sizeof(etMessage))));
	
	ET_MSC_LOGGER_SYNC_EXIT
}


/*--------------------- operations ---------------------*/
void ACANService_pollAllRxMsgs(ACANService* self) {
	pclCANMsg msg;
	uint32 i;
	uint8 val;
	uint32 numberOfPorts = PCANRxReplPort_getReplication(&(self->constData->canRx));
	for(i=0;i<numberOfPorts;i++){
		if (PCL_TRUE == pclCANCheckReception(rxData[i].channel, &msg)){
			canRx_msgReceived(i, &msg);
			}
		}
}

