/**
 * @author generated by eTrice
 *
 * Utils File of ActorClass ACANService
 * 
 */

#ifndef _ROOM_BASIC_SERVICE_CAN_ACANSERVICE_UTILS_H_
#define _ROOM_BASIC_SERVICE_CAN_ACANSERVICE_UTILS_H_

#include "room/basic/service/can/ACANService.h"

/*
 * access macros for ports, operations and attributes
*/

/* simple event ports */

/* data receive ports */

/* data send ports */

/* saps */
#define timer_startTimer(data) PTimerConjPort_startTimer(&self->constData->timer, data)
#define timer_startTimeout(data) PTimerConjPort_startTimeout(&self->constData->timer, data)
#define timer_kill() PTimerConjPort_kill(&self->constData->timer)

/* replicated event ports */

/* services */
#define canTx_valueChanged_broadcast(data) PCANTxReplPort_valueChanged_broadcast(&self->constData->canTx, data)
#define canTx_valueChanged(idx, data) PCANTxReplPort_valueChanged(&self->constData->canTx, idx, data)
#define canRx_msgReceived_broadcast(data) PCANRxReplPort_msgReceived_broadcast(&self->constData->canRx, data)
#define canRx_msgReceived(idx, data) PCANRxReplPort_msgReceived(&self->constData->canRx, idx, data)

/* operations */
#define pollAllRxMsgs() ACANService_pollAllRxMsgs(self)

/* attributes */
#define rxData (self->rxData)
#define txData (self->txData)
#define pollTime (self->pollTime)

/* port operations */

#endif /* _ROOM_BASIC_SERVICE_CAN_ACANSERVICE_UTILS_H_ */

