/**
 * @author generated by eTrice
 *
 * Header File of DataClass DCANData
 * 
 */

#ifndef _ROOM_BASIC_SERVICE_CAN_DCANDATA_H_
#define _ROOM_BASIC_SERVICE_CAN_DCANDATA_H_

#include "etDatatypes.h"


		
typedef struct {
	/*--------------------- attributes ---------------------*/
	uint32 channel;
	uint32 msgId;
	uint8 data[8];
} DCANData;



/*--------------------- operations ---------------------*/

/* deep copy */
void DCANData_deepCopy(DCANData* source, DCANData* target);


#endif /* _ROOM_BASIC_SERVICE_CAN_DCANDATA_H_ */

