/**
 * @author generated by eTrice
 *
 * Source File of DataClass DSerialBuffer
 * 
 */

#include <string.h>

#include "DSerialBuffer.h"
#include "DSerialBuffer_Utils.h"



/*--------------------- operations ---------------------*/

void DSerialBuffer_deepCopy(DSerialBuffer* source, DSerialBuffer* target) {
	memcpy(target, source, sizeof(DSerialBuffer));
}


