/**
 * @author generated by eTrice
 *
 * this class contains the main function running component subSystem
 * it instantiates subSystem and starts and ends the lifecycle
 */

package Fischertechnik;

import org.eclipse.etrice.runtime.java.modelbase.RTSystem;
import org.eclipse.etrice.runtime.java.modelbase.SubSystemRunnerBase;

class Node_nodeRef1_subSystemRunner extends SubSystemRunnerBase {

	/**
     * main function
     * creates the main component and starts and stops the lifecycle
     */
	public static void main(String[] args) {
		// instantiate the main component
		RTSystem sys = new RTSystem("MachineSystem");
		Node_nodeRef1_subSystem main_component = new Node_nodeRef1_subSystem(sys, "subSystem");
		
		run(main_component, args);
	}
};
