/**
 * @author generated by eTrice
 *
 * this class contains the main function running Node nodeRef1 with SubSystem main
 * it instantiates Node nodeRef1 with SubSystem main and starts and ends the lifecycle
 */

#include <string.h>

#include "nodeRef1_main.h"

#include "debugging/etLogger.h"
#include "debugging/etMSCLogger.h"
#include "debugging/etDataLogger.h"

#include "osal/etPlatformLifecycle.h"

/**
 * main function
 * creates component and starts and stops the lifecycle
 */

int main(int argc, char** argv) {
	etBool runAsTest = ET_FALSE;

	if (argc>1 && strcmp(argv[1], "-headless")==0)
		runAsTest = ET_TRUE;
	if (argc>1 && strcmp(argv[1], "-run_as_test")==0)
		runAsTest = ET_TRUE;

	etUserEntry(); /* platform specific */
	
	etLogger_logInfo("***   T H E   B E G I N   ***");
	ET_MSC_LOGGER_OPEN("main");

	/* startup sequence  of lifecycle */
	nodeRef1_main_init(); 		/* lifecycle init */
	nodeRef1_main_start(); 	/* lifecycle start */

	etUserPreRun(); /* platform specific */

	/* run Scheduler */
	nodeRef1_main_run(runAsTest);

	etUserPostRun(); /* platform specific */

	/* shutdown sequence of lifecycle */
	nodeRef1_main_stop(); 		/* lifecycle stop */
	nodeRef1_main_destroy(); 	/* lifecycle destroy */

	ET_MSC_LOGGER_CLOSE
	etLogger_logInfo("***   T H E   E N D   ***");

	etUserExit(); /* platform specific */

	return 0;
}

