/**
 * @author generated by eTrice
 *
 * Header File of ActorClass Application
 * 
 */

#ifndef _HEXAGON_APPLICATION_H_
#define _HEXAGON_APPLICATION_H_

#include "etDatatypes.h"
#include "messaging/etMessage.h"

#include "hexagon/PBlinkyControl.h"
#include "room/basic/service/timing/PTimer.h"


typedef struct Application Application;

/* const part of ActorClass (ROM) */
typedef struct Application_const {
	const char* instName;
	
	/* simple ports */
	
	/* data receive ports */

	/* saps */
	
	/* replicated ports */
	
	/* services */
} Application_const;


/* variable part of ActorClass (RAM) */
struct Application {
	const Application_const* const constData;
	
	/* data send ports */
	
	/*--------------------- attributes ---------------------*/
	
};

void Application_init(Application* self);

void Application_receiveMessage(void* self, const void* ifitem, const etMessage* msg);


/*--------------------- operations ---------------------*/


#endif /* _HEXAGON_APPLICATION_H_ */

