/**
 * @author generated by eTrice
 *
 * Header File of Node nodeRef1 with SubSystem main
 * 
 */

#ifndef _NODEREF1_MAIN_H_
#define _NODEREF1_MAIN_H_

#include "etDatatypes.h"



/* lifecycle functions
 * init -> start -> run (loop) -> stop -> destroy
 */

void nodeRef1_main_init(void);		/* lifecycle init  	 */
void nodeRef1_main_start(void);	/* lifecycle start 	 */

void nodeRef1_main_run(etBool runAsTest);		/* lifecycle run 	 */

void nodeRef1_main_stop(void); 	/* lifecycle stop	 */
void nodeRef1_main_destroy(void); 	/* lifecycle destroy */

void nodeRef1_main_shutdown(void);  /* shutdown the dispatcher loop */


#endif /* _NODEREF1_MAIN_H_ */


