/**
 * @author generated by eTrice
 *
 * Instance File of Node nodeRef1 with SubSystem main
 * - instantiation of all actor instances and port instances
 * - configuration of data and connection of ports
 */

#include "messaging/etMessageService.h"

/* include all referenced ActorClasses */
#include "hexagon/Application.h"
#include "room/basic/service/timing/ATimingService.h"
#include "hexagon/ABlinky.h"

/* include all referenced ProtcolClasses */

/* instantiation of message services and message buffers */
/* PhysicalThread1 */
#define PHYSICALTHREAD1_POOL_SIZE		10
#define PHYSICALTHREAD1_BLOCK_SIZE	32
static uint8 msgBuffer_PhysicalThread1[PHYSICALTHREAD1_POOL_SIZE * PHYSICALTHREAD1_BLOCK_SIZE]; 
static etMessageService msgService_PhysicalThread1;

/* declarations of all ActorClass instances (const and variable structs) */

/* forward declaration of variable actor structs */
static Application _hexagon_main_appl;
static ABlinky _hexagon_main_appl_blinky;
static ATimingService _hexagon_main_timingService;

/* forward declaration of variable port structs */
/* nothing to do */
static PTimerConjPort_var _hexagon_main_appl_blinky_timer_var={
	0		/* status */
							};


/* instance _hexagon_main_appl */
static /*const*/ Application_const _hexagon_main_appl_const = {
	"/hexagon/main/appl"
	
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	
	/* data receive ports */
	
	/* saps */
	
	/* replicated ports */
	
	/* services */
};
static Application _hexagon_main_appl = {
	&_hexagon_main_appl_const,
	
	/* data send ports */
	
	/* attributes */
	
	/* state and history are initialized in init function */
};

/* instance _hexagon_main_appl_blinky */
static /*const*/ ABlinky_const _hexagon_main_appl_blinky_const = {
	"/hexagon/main/appl/blinky"
	
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	,{NULL, NULL, 0+BASE_ADDRESS, 1
	#ifdef ET_ASYNC_MSC_LOGGER_ACTIVATE
	,"/hexagon/main/appl/blinky",
	#endif
	} /* Port controlPort */
	
	/* data receive ports */
	
	/* saps */
	,{&_hexagon_main_appl_blinky_timer_var, &msgService_PhysicalThread1, 6+BASE_ADDRESS, 2
	#ifdef ET_ASYNC_MSC_LOGGER_ACTIVATE
	,"/hexagon/main/appl/blinky","/hexagon/main/timingService"
	#endif
	} /* Port timer */
	
	/* replicated ports */
	
	/* services */
};
static ABlinky _hexagon_main_appl_blinky = {
	&_hexagon_main_appl_blinky_const,
	
	/* data send ports */
	
	/* attributes */
	0		/* counter */,
	ET_TRUE		/* test */
	
	/* state and history are initialized in init function */
};

/* instance _hexagon_main_timingService */
static const etReplSubPort _hexagon_main_timingService_repl_sub_ports[1] = {
	/* Replicated Sub Ports: {varData, msgService, peerAddress, localId, index} */
	{{NULL,&msgService_PhysicalThread1, 4+BASE_ADDRESS, 1
	#ifdef ET_ASYNC_MSC_LOGGER_ACTIVATE
	,"/hexagon/main/timingService"
	,"/hexagon/main/appl/blinky"
	#endif
	},0} /* Repl Sub Port timer idx +0*/
};
static /*const*/ ATimingService_const _hexagon_main_timingService_const = {
	"/hexagon/main/timingService"
	
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	
	/* data receive ports */
	
	/* saps */
	
	/* replicated ports */
	
	/* services */
	,{1, _hexagon_main_timingService_repl_sub_ports+0}
};
static ATimingService _hexagon_main_timingService = {
	&_hexagon_main_timingService_const,
	
	/* data send ports */
	
	/* attributes */
	
	/* state and history are initialized in init function */
};

