/**
 * @author generated by eTrice
 *
 * Instance File of Node nodeRef1 with SubSystem main
 * - instantiation of all actor instances and port instances
 * - configuration of data and connection of ports
 */

#include "messaging/etMessageService.h"

/* include all referenced ActorClasses */
#include "hexagon/AButtonController.h"
#include "hexagon/Application.h"
#include "hexagon/AAdc.h"
#include "hexagon/ABlinky.h"
#include "hexagon/ADisplay.h"
#include "hexagon/AUartController.h"
#include "room/basic/service/timing/ATimingService.h"
#include "hexagon/AI2CController.h"

/* include all referenced ProtcolClasses */

/* instantiation of message services and message buffers */
/* PhysicalThread1 */
#define PHYSICALTHREAD1_POOL_SIZE		10
#define PHYSICALTHREAD1_BLOCK_SIZE	32
static uint8 msgBuffer_PhysicalThread1[PHYSICALTHREAD1_POOL_SIZE * PHYSICALTHREAD1_BLOCK_SIZE]; 
static etMessageService msgService_PhysicalThread1;

/* declarations of all ActorClass instances (const and variable structs) */

/* forward declaration of variable actor structs */
static Application _hexagon_main_appl;
static ABlinky _hexagon_main_appl_blinky;
static AButtonController _hexagon_main_appl_button;
static ADisplay _hexagon_main_appl_display;
static AAdc _hexagon_main_appl_adc;
static AI2CController _hexagon_main_appl_i2c;
static AUartController _hexagon_main_appl_uart;
static ATimingService _hexagon_main_timingService;

/* forward declaration of variable port structs */
static PIO004ConjPort_var _hexagon_main_appl_blinky_LED1_var={
	0		/* Handle */
							};
static PTimerConjPort_var _hexagon_main_appl_blinky_timer_var={
	0		/* status */
							};
static PIO004ConjPort_var _hexagon_main_appl_button_hwPin_var={
	0		/* Handle */
							};
static PTimerConjPort_var _hexagon_main_appl_button_timer_var={
	0		/* status */
							};
static PTimerConjPort_var _hexagon_main_appl_display_timer_var={
	0		/* status */
							};
static PTimerConjPort_var _hexagon_main_appl_display_timerAdc_var={
	0		/* status */
							};
static PADC001ConjPort_var _hexagon_main_appl_adc_adc_var={
	 0 		/* Handle */
							};
static PTimerConjPort_var _hexagon_main_appl_adc_timer_var={
	0		/* status */
							};
static PI2C001ConjPort_var _hexagon_main_appl_i2c_i2c_var={
	NULL		/* Handle */,
	0		/* i2cData */,
	0		/* i2cAddr */
							};
static PUART001ConjPort_var _hexagon_main_appl_uart_uart_var={
	0		/* Handle */
							};


/* instance _hexagon_main_appl */
static /*const*/ Application_const _hexagon_main_appl_const = {
	"/hexagon/main/appl"
	
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	,{NULL, &msgService_PhysicalThread1, 7+BASE_ADDRESS, 1
	#ifdef ET_ASYNC_MSC_LOGGER_ACTIVATE
	,"/hexagon/main/appl","/hexagon/main/appl/blinky"
	#endif
	} /* Port blinkyPort */
	,{NULL, &msgService_PhysicalThread1, 12+BASE_ADDRESS, 2
	#ifdef ET_ASYNC_MSC_LOGGER_ACTIVATE
	,"/hexagon/main/appl","/hexagon/main/appl/button"
	#endif
	} /* Port buttonControlPort */
	,{NULL, &msgService_PhysicalThread1, 11+BASE_ADDRESS, 3
	#ifdef ET_ASYNC_MSC_LOGGER_ACTIVATE
	,"/hexagon/main/appl","/hexagon/main/appl/button"
	#endif
	} /* Port buttonPort */
	,{NULL, &msgService_PhysicalThread1, 21+BASE_ADDRESS, 4
	#ifdef ET_ASYNC_MSC_LOGGER_ACTIVATE
	,"/hexagon/main/appl","/hexagon/main/appl/adc"
	#endif
	} /* Port adcControlPort */
	
	/* data receive ports */
	
	/* saps */
	
	/* replicated ports */
	
	/* services */
};
static Application _hexagon_main_appl = {
	&_hexagon_main_appl_const,
	
	/* data send ports */
	
	/* attributes */
	
	/* state and history are initialized in init function */
};

/* instance _hexagon_main_appl_blinky */
static /*const*/ ABlinky_const _hexagon_main_appl_blinky_const = {
	"/hexagon/main/appl/blinky"
	
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	,{NULL, &msgService_PhysicalThread1, 2+BASE_ADDRESS, 2
	#ifdef ET_ASYNC_MSC_LOGGER_ACTIVATE
	,"/hexagon/main/appl/blinky","/hexagon/main/appl"
	#endif
	} /* Port controlPort */
	,{&_hexagon_main_appl_blinky_LED1_var, NULL, 0+BASE_ADDRESS, 1
	#ifdef ET_ASYNC_MSC_LOGGER_ACTIVATE
	,"/hexagon/main/appl/blinky",
	#endif
	} /* Port LED1 */
	
	/* data receive ports */
	
	/* saps */
	,{&_hexagon_main_appl_blinky_timer_var, &msgService_PhysicalThread1, 34+BASE_ADDRESS, 3
	#ifdef ET_ASYNC_MSC_LOGGER_ACTIVATE
	,"/hexagon/main/appl/blinky","/hexagon/main/timingService"
	#endif
	} /* Port timer */
	
	/* replicated ports */
	
	/* services */
};
static ABlinky _hexagon_main_appl_blinky = {
	&_hexagon_main_appl_blinky_const,
	
	/* data send ports */
	
	/* attributes */
	0		/* counter */,
	ET_FALSE		/* test */
	
	/* state and history are initialized in init function */
};

/* instance _hexagon_main_appl_button */
static /*const*/ AButtonController_const _hexagon_main_appl_button_const = {
	"/hexagon/main/appl/button"
	
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	,{NULL, &msgService_PhysicalThread1, 4+BASE_ADDRESS, 2
	#ifdef ET_ASYNC_MSC_LOGGER_ACTIVATE
	,"/hexagon/main/appl/button","/hexagon/main/appl"
	#endif
	} /* Port ioPort */
	,{NULL, &msgService_PhysicalThread1, 3+BASE_ADDRESS, 3
	#ifdef ET_ASYNC_MSC_LOGGER_ACTIVATE
	,"/hexagon/main/appl/button","/hexagon/main/appl"
	#endif
	} /* Port controlPort */
	,{&_hexagon_main_appl_button_hwPin_var, NULL, 0+BASE_ADDRESS, 1
	#ifdef ET_ASYNC_MSC_LOGGER_ACTIVATE
	,"/hexagon/main/appl/button",
	#endif
	} /* Port hwPin */
	
	/* data receive ports */
	
	/* saps */
	,{&_hexagon_main_appl_button_timer_var, &msgService_PhysicalThread1, 35+BASE_ADDRESS, 4
	#ifdef ET_ASYNC_MSC_LOGGER_ACTIVATE
	,"/hexagon/main/appl/button","/hexagon/main/timingService"
	#endif
	} /* Port timer */
	
	/* replicated ports */
	
	/* services */
};
static AButtonController _hexagon_main_appl_button = {
	&_hexagon_main_appl_button_const,
	
	/* data send ports */
	
	/* attributes */
	0		/* pinState */
	
	/* state and history are initialized in init function */
};

/* instance _hexagon_main_appl_display */
static /*const*/ ADisplay_const _hexagon_main_appl_display_const = {
	"/hexagon/main/appl/display"
	
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	,{NULL, &msgService_PhysicalThread1, 23+BASE_ADDRESS, 2
	#ifdef ET_ASYNC_MSC_LOGGER_ACTIVATE
	,"/hexagon/main/appl/display","/hexagon/main/appl/adc"
	#endif
	} /* Port control */
	,{NULL, NULL, 0+BASE_ADDRESS, 1
	#ifdef ET_ASYNC_MSC_LOGGER_ACTIVATE
	,"/hexagon/main/appl/display",
	#endif
	} /* Port gui */
	
	/* data receive ports */
	
	/* saps */
	,{&_hexagon_main_appl_display_timer_var, &msgService_PhysicalThread1, 36+BASE_ADDRESS, 3
	#ifdef ET_ASYNC_MSC_LOGGER_ACTIVATE
	,"/hexagon/main/appl/display","/hexagon/main/timingService"
	#endif
	} /* Port timer */
	,{&_hexagon_main_appl_display_timerAdc_var, &msgService_PhysicalThread1, 37+BASE_ADDRESS, 4
	#ifdef ET_ASYNC_MSC_LOGGER_ACTIVATE
	,"/hexagon/main/appl/display","/hexagon/main/timingService"
	#endif
	} /* Port timerAdc */
	
	/* replicated ports */
	
	/* services */
};
static ADisplay _hexagon_main_appl_display = {
	&_hexagon_main_appl_display_const,
	
	/* data send ports */
	
	/* attributes */
	{
		NULL		/* s */,
		0		/* xPos */,
		0		/* yPos */
	}		/* str */,
	{
		NULL		/* bitmap */,
		0		/* xPos */,
		0		/* yPos */
	}		/* bmp */,
	0		/* showTime */,
	0		/* adcVal */
	
	/* state and history are initialized in init function */
};

/* instance _hexagon_main_appl_adc */
static const etReplSubPort _hexagon_main_appl_adc_repl_sub_ports[3] = {
	/* Replicated Sub Ports: {varData, msgService, peerAddress, localId, index} */
	{{NULL,&msgService_PhysicalThread1, 28+BASE_ADDRESS, 3
	#ifdef ET_ASYNC_MSC_LOGGER_ACTIVATE
	,"/hexagon/main/appl/adc"
	,"/hexagon/main/appl/i2c"
	#endif
	},0}, /* Repl Sub Port payload idx +0*/
	{{NULL,&msgService_PhysicalThread1, 16+BASE_ADDRESS, 3
	#ifdef ET_ASYNC_MSC_LOGGER_ACTIVATE
	,"/hexagon/main/appl/adc"
	,"/hexagon/main/appl/display"
	#endif
	},1}, /* Repl Sub Port payload idx +1*/
	{{NULL,&msgService_PhysicalThread1, 31+BASE_ADDRESS, 3
	#ifdef ET_ASYNC_MSC_LOGGER_ACTIVATE
	,"/hexagon/main/appl/adc"
	,"/hexagon/main/appl/uart"
	#endif
	},2} /* Repl Sub Port payload idx +2*/
};
static /*const*/ AAdc_const _hexagon_main_appl_adc_const = {
	"/hexagon/main/appl/adc"
	
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	,{NULL, &msgService_PhysicalThread1, 5+BASE_ADDRESS, 2
	#ifdef ET_ASYNC_MSC_LOGGER_ACTIVATE
	,"/hexagon/main/appl/adc","/hexagon/main/appl"
	#endif
	} /* Port control */
	,{&_hexagon_main_appl_adc_adc_var, NULL, 0+BASE_ADDRESS, 1
	#ifdef ET_ASYNC_MSC_LOGGER_ACTIVATE
	,"/hexagon/main/appl/adc",
	#endif
	} /* Port adc */
	
	/* data receive ports */
	
	/* saps */
	,{&_hexagon_main_appl_adc_timer_var, &msgService_PhysicalThread1, 38+BASE_ADDRESS, 4
	#ifdef ET_ASYNC_MSC_LOGGER_ACTIVATE
	,"/hexagon/main/appl/adc","/hexagon/main/timingService"
	#endif
	} /* Port timer */
	
	/* replicated ports */
	,{3, _hexagon_main_appl_adc_repl_sub_ports+0}
	
	/* services */
};
static AAdc _hexagon_main_appl_adc = {
	&_hexagon_main_appl_adc_const,
	
	/* data send ports */
	
	/* attributes */
	0		/* lastVal */,
	0		/* currentVal */
	
	/* state and history are initialized in init function */
};

/* instance _hexagon_main_appl_i2c */
static /*const*/ AI2CController_const _hexagon_main_appl_i2c_const = {
	"/hexagon/main/appl/i2c"
	
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	,{NULL, &msgService_PhysicalThread1, 22+BASE_ADDRESS, 2
	#ifdef ET_ASYNC_MSC_LOGGER_ACTIVATE
	,"/hexagon/main/appl/i2c","/hexagon/main/appl/adc"
	#endif
	} /* Port payload */
	,{&_hexagon_main_appl_i2c_i2c_var, NULL, 0+BASE_ADDRESS, 1
	#ifdef ET_ASYNC_MSC_LOGGER_ACTIVATE
	,"/hexagon/main/appl/i2c",
	#endif
	} /* Port i2c */
	
	/* data receive ports */
	
	/* saps */
	
	/* replicated ports */
	
	/* services */
};
static AI2CController _hexagon_main_appl_i2c = {
	&_hexagon_main_appl_i2c_const,
	
	/* data send ports */
	
	/* attributes */
	
	/* state and history are initialized in init function */
};

/* instance _hexagon_main_appl_uart */
static /*const*/ AUartController_const _hexagon_main_appl_uart_const = {
	"/hexagon/main/appl/uart"
	
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	,{NULL, &msgService_PhysicalThread1, 24+BASE_ADDRESS, 2
	#ifdef ET_ASYNC_MSC_LOGGER_ACTIVATE
	,"/hexagon/main/appl/uart","/hexagon/main/appl/adc"
	#endif
	} /* Port p0 */
	,{&_hexagon_main_appl_uart_uart_var, NULL, 0+BASE_ADDRESS, 1
	#ifdef ET_ASYNC_MSC_LOGGER_ACTIVATE
	,"/hexagon/main/appl/uart",
	#endif
	} /* Port uart */
	
	/* data receive ports */
	
	/* saps */
	
	/* replicated ports */
	
	/* services */
};
static AUartController _hexagon_main_appl_uart = {
	&_hexagon_main_appl_uart_const,
	
	/* data send ports */
	
	/* attributes */
	
	/* state and history are initialized in init function */
};

/* instance _hexagon_main_timingService */
static const etReplSubPort _hexagon_main_timingService_repl_sub_ports[5] = {
	/* Replicated Sub Ports: {varData, msgService, peerAddress, localId, index} */
	{{NULL,&msgService_PhysicalThread1, 9+BASE_ADDRESS, 1
	#ifdef ET_ASYNC_MSC_LOGGER_ACTIVATE
	,"/hexagon/main/timingService"
	,"/hexagon/main/appl/blinky"
	#endif
	},0}, /* Repl Sub Port timer idx +0*/
	{{NULL,&msgService_PhysicalThread1, 14+BASE_ADDRESS, 1
	#ifdef ET_ASYNC_MSC_LOGGER_ACTIVATE
	,"/hexagon/main/timingService"
	,"/hexagon/main/appl/button"
	#endif
	},1}, /* Repl Sub Port timer idx +1*/
	{{NULL,&msgService_PhysicalThread1, 18+BASE_ADDRESS, 1
	#ifdef ET_ASYNC_MSC_LOGGER_ACTIVATE
	,"/hexagon/main/timingService"
	,"/hexagon/main/appl/display"
	#endif
	},2}, /* Repl Sub Port timer idx +2*/
	{{NULL,&msgService_PhysicalThread1, 19+BASE_ADDRESS, 1
	#ifdef ET_ASYNC_MSC_LOGGER_ACTIVATE
	,"/hexagon/main/timingService"
	,"/hexagon/main/appl/display"
	#endif
	},3}, /* Repl Sub Port timer idx +3*/
	{{NULL,&msgService_PhysicalThread1, 26+BASE_ADDRESS, 1
	#ifdef ET_ASYNC_MSC_LOGGER_ACTIVATE
	,"/hexagon/main/timingService"
	,"/hexagon/main/appl/adc"
	#endif
	},4} /* Repl Sub Port timer idx +4*/
};
static /*const*/ ATimingService_const _hexagon_main_timingService_const = {
	"/hexagon/main/timingService"
	
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	
	/* data receive ports */
	
	/* saps */
	
	/* replicated ports */
	
	/* services */
	,{5, _hexagon_main_timingService_repl_sub_ports+0}
};
static ATimingService _hexagon_main_timingService = {
	&_hexagon_main_timingService_const,
	
	/* data send ports */
	
	/* attributes */
	
	/* state and history are initialized in init function */
};

