/**
 * @author generated by eTrice
 *
 * Source File of ActorClass AMrPing
 * 
 */

#include "AMrPing.h"

#include "modelbase/etActor.h"
#include "debugging/etLogger.h"
#include "debugging/etMSCLogger.h"
#include "etUnit/etUnit.h"
#include "base/etMemory.h"

#include "room/basic/service/can/PCANRx.h"
#include "room/basic/service/can/PCANTx.h"
#include "HexagonCANDemo/PPingPong.h"
#include "room/basic/service/timing/PTimer.h"

#include "AMrPing_Utils.h"


/* interface item IDs */
enum interface_items {
	IFITEM_p0 = 1,
	IFITEM_timer = 2,
	IFITEM_canTx = 3,
	IFITEM_canRx = 4
};

/* state IDs */
enum state_ids {
	NO_STATE = 0,
	STATE_TOP = 1,
	STATE_state0 = 2,
	STATE_MAX = 3
};

/* transition chains */
enum chain_ids {
	CHAIN_TRANS_INITIAL_TO__state0 = 1,
	CHAIN_TRANS_tr0_FROM_state0_TO_state0_BY_timeouttimer_tr0 = 2,
	CHAIN_TRANS_tr1_FROM_state0_TO_state0_BY_pingp0_tr1 = 3,
	CHAIN_TRANS_tr2_FROM_state0_TO_state0_BY_msgReceivedcanRx_tr2 = 4
};

/* triggers */
enum triggers {
	POLLING = 0,
	TRIG_p0__ping = IFITEM_p0 + EVT_SHIFT*PPingPong_IN_ping,
	TRIG_timer__timeout = IFITEM_timer + EVT_SHIFT*PTimer_OUT_timeout,
	TRIG_canTx__valueChanged = IFITEM_canTx + EVT_SHIFT*PCANTx_OUT_valueChanged,
	TRIG_canRx__msgReceived = IFITEM_canRx + EVT_SHIFT*PCANRx_OUT_msgReceived
};


static void setState(AMrPing* self, etInt16 new_state) {
	self->state = new_state;
}

static etInt16 getState(AMrPing* self) {
	return self->state;
}

/* Entry and Exit Codes */

/* Action Codes */
static void action_TRANS_INITIAL_TO__state0(AMrPing* self) {
	pclCANMsg msg;
	
	
	timer_startTimeout(500);
	canTx_init(ET_CAN_CHANNEL_NOT_DEFINED);
	canRx_init(ET_CAN_CHANNEL_NOT_DEFINED);
	//canTx.init(0x00000005);
	//canRx.init(0x00000007);
	
	msg.id = 0x12;
	canRx_listenOnMsg(&msg);
}
static void action_TRANS_tr0_FROM_state0_TO_state0_BY_timeouttimer_tr0(AMrPing* self, const InterfaceItemBase* ifitem) {
	p0_pong();
}
static void action_TRANS_tr1_FROM_state0_TO_state0_BY_pingp0_tr1(AMrPing* self, const InterfaceItemBase* ifitem) {
	static uint8 counter=0;
	pclCANMsg msg;
	
	if (counter & 0x01){
		msg.id = 0x27;
		}else{
		msg.id=0x30;
		}
	msg.len = 8;
	msg.data[0] = 10;
	msg.data[1] = 11;
	msg.data[2] = 12;
	msg.data[3] = 13;
	msg.data[4] = 14;
	msg.data[5] = 15;
	msg.data[6] = 16;
	msg.data[7] = counter++;
	
	timer_startTimeout(500);
	canTx_sendMsg(&msg);
}
static void action_TRANS_tr2_FROM_state0_TO_state0_BY_msgReceivedcanRx_tr2(AMrPing* self, const InterfaceItemBase* ifitem, pclCANMsg* data) {
	volatile pclCANMsg msg;
	
	msg = *data;
}

/**
 * calls exit codes while exiting from the current state to one of its
 * parent states while remembering the history
 * @param current__et - the current state
 * @param to - the final parent state
 */
static void exitTo(AMrPing* self, etInt16 current__et, etInt16 to) {
	while (current__et!=to) {
		switch (current__et) {
			case STATE_state0:
				self->history[STATE_TOP] = STATE_state0;
				current__et = STATE_TOP;
				break;
			default:
				/* should not occur */
				break;
		}
	}
}

/**
 * calls action, entry and exit codes along a transition chain. The generic data are cast to typed data
 * matching the trigger of this chain. The ID of the final state is returned
 * @param chain__et - the chain ID
 * @param generic_data__et - the generic data pointer
 * @return the +/- ID of the final state either with a positive sign, that indicates to execute the state's entry code, or a negative sign vice versa
 */
static etInt16 executeTransitionChain(AMrPing* self, int chain__et, const InterfaceItemBase* ifitem, void* generic_data__et) {
	switch (chain__et) {
		case CHAIN_TRANS_INITIAL_TO__state0:
		{
			action_TRANS_INITIAL_TO__state0(self);
			return STATE_state0;
		}
		case CHAIN_TRANS_tr0_FROM_state0_TO_state0_BY_timeouttimer_tr0:
		{
			action_TRANS_tr0_FROM_state0_TO_state0_BY_timeouttimer_tr0(self, ifitem);
			return STATE_state0;
		}
		case CHAIN_TRANS_tr1_FROM_state0_TO_state0_BY_pingp0_tr1:
		{
			action_TRANS_tr1_FROM_state0_TO_state0_BY_pingp0_tr1(self, ifitem);
			return STATE_state0;
		}
		case CHAIN_TRANS_tr2_FROM_state0_TO_state0_BY_msgReceivedcanRx_tr2:
		{
			pclCANMsg* data = ((pclCANMsg*) generic_data__et);
			action_TRANS_tr2_FROM_state0_TO_state0_BY_msgReceivedcanRx_tr2(self, ifitem, data);
			return STATE_state0;
		}
			default:
				/* should not occur */
				break;
	}
	return NO_STATE;
}

/**
 * calls entry codes while entering a state's history. The ID of the final leaf state is returned
 * @param state__et - the state which is entered
 * @return - the ID of the final leaf state
 */
static etInt16 enterHistory(AMrPing* self, etInt16 state__et) {
	boolean skip_entry__et = ET_FALSE;
	if (state__et >= STATE_MAX) {
		state__et = (etInt16) (state__et - STATE_MAX);
		skip_entry__et = ET_TRUE;
	}
	while (ET_TRUE) {
		switch (state__et) {
			case STATE_state0:
				/* in leaf state: return state id */
				return STATE_state0;
			case STATE_TOP:
				state__et = self->history[STATE_TOP];
				break;
			default:
				/* should not occur */
				break;
		}
		skip_entry__et = ET_FALSE;
	}
	/* return NO_STATE; // required by CDT but detected as unreachable by JDT because of while (true) */
}

static void AMrPing_executeInitTransition(AMrPing* self) {
	int chain__et = CHAIN_TRANS_INITIAL_TO__state0;
	etInt16 next__et = executeTransitionChain(self, chain__et, NULL, NULL);
	next__et = enterHistory(self, next__et);
	setState(self, next__et);
}

/* receiveEvent contains the main implementation of the FSM */
static void AMrPing_receiveEvent(AMrPing* self, InterfaceItemBase* ifitem, int evt, void* generic_data__et) {
	int trigger__et = ifitem->localId + EVT_SHIFT*evt;
	int chain__et = NOT_CAUGHT;
	etInt16 catching_state__et = NO_STATE;
	((void)trigger__et);	/* avoids unused warning */
	
	if (!handleSystemEvent(ifitem, evt, generic_data__et)) {
		switch (getState(self)) {
			case STATE_state0:
				switch(trigger__et) {
						case TRIG_timer__timeout:
							{
								chain__et = CHAIN_TRANS_tr0_FROM_state0_TO_state0_BY_timeouttimer_tr0;
								catching_state__et = STATE_TOP;
							}
						break;
						case TRIG_p0__ping:
							{
								chain__et = CHAIN_TRANS_tr1_FROM_state0_TO_state0_BY_pingp0_tr1;
								catching_state__et = STATE_TOP;
							}
						break;
						case TRIG_canRx__msgReceived:
							{
								chain__et = CHAIN_TRANS_tr2_FROM_state0_TO_state0_BY_msgReceivedcanRx_tr2;
								catching_state__et = STATE_TOP;
							}
						break;
						default:
							/* should not occur */
							break;
				}
				break;
			default:
				/* should not occur */
				break;
		}
	}
	if (chain__et != NOT_CAUGHT) {
		exitTo(self, getState(self), catching_state__et);
		{
			etInt16 next__et = executeTransitionChain(self, chain__et, ifitem, generic_data__et);
			next__et = enterHistory(self, next__et);
			setState(self, next__et);
		}
	}
}

void AMrPing_init(AMrPing* self){
	ET_MSC_LOGGER_SYNC_ENTRY("AMrPing", "init")
	self->state = STATE_TOP;
	{
		int i;
		for (i=0; i<AMRPING_HISTORY_SIZE; ++i)
			self->history[i] = NO_STATE;
	}
	AMrPing_executeInitTransition(self);
	ET_MSC_LOGGER_SYNC_EXIT
}


void AMrPing_receiveMessage(void* self, const void* ifitem, const etMessage* msg){
	ET_MSC_LOGGER_SYNC_ENTRY("AMrPing", "_receiveMessage")
	
	AMrPing_receiveEvent(self, (etPort*)ifitem, msg->evtID, (void*)(((char*)msg)+MEM_CEIL(sizeof(etMessage))));
	
	ET_MSC_LOGGER_SYNC_EXIT
}


/*--------------------- operations ---------------------*/

