/**
 * @author generated by eTrice
 *
 * Utils File of ProtocolClass PPingPong
 * 
 */

#ifndef _HEXAGONCANDEMO_PPINGPONG_UTILS_H_
#define _HEXAGONCANDEMO_PPINGPONG_UTILS_H_

#include "HexagonCANDemo/PPingPong.h"

/*
 * access macros for operations and attributes
*/


#endif /* _HEXAGONCANDEMO_PPINGPONG_UTILS_H_ */

