/**
 * @author generated by eTrice
 *
 * Header File of ActorClass AMrPong
 * 
 */

#ifndef _HEXAGONCANDEMO_AMRPONG_H_
#define _HEXAGONCANDEMO_AMRPONG_H_

#include "etDatatypes.h"
#include "messaging/etMessage.h"

#include "HexagonCANDemo/PPingPong.h"


typedef struct AMrPong AMrPong;

/* const part of ActorClass (ROM) */
typedef struct AMrPong_const {
	/* simple ports */
	const PPingPongConjPort p0;
	
	/* data receive ports */

	/* saps */
	
	/* replicated ports */
	
	/* services */
} AMrPong_const;


/* constant for state machine data */
#define AMRPONG_HISTORY_SIZE 2

/* variable part of ActorClass (RAM) */
struct AMrPong {
	const AMrPong_const* const constData;
	
	/* data send ports */
	
	/*--------------------- attributes ---------------------*/
	
	
	/* state machine variables */
	etInt16 state;
	etInt16 history[AMRPONG_HISTORY_SIZE];
};

void AMrPong_init(AMrPong* self);

void AMrPong_receiveMessage(void* self, const void* ifitem, const etMessage* msg);


/*--------------------- operations ---------------------*/


#endif /* _HEXAGONCANDEMO_AMRPONG_H_ */

