/**
 * @author generated by eTrice
 *
 * Utils File of ActorClass AMrPong
 * 
 */

#ifndef _HEXAGONCANDEMO_AMRPONG_UTILS_H_
#define _HEXAGONCANDEMO_AMRPONG_UTILS_H_

#include "HexagonCANDemo/AMrPong.h"

/*
 * access macros for ports, operations and attributes
*/

/* simple event ports */
#define p0_ping() PPingPongConjPort_ping(&self->constData->p0)

/* data receive ports */

/* data send ports */

/* saps */

/* replicated event ports */

/* services */

/* operations */

/* attributes */

/* port operations */

#endif /* _HEXAGONCANDEMO_AMRPONG_UTILS_H_ */

