/**
 * @author generated by eTrice
 *
 * Source File of ActorClass Application
 * 
 */

#include "Application.h"

#include "modelbase/etActor.h"
#include "debugging/etLogger.h"
#include "debugging/etMSCLogger.h"
#include "etUnit/etUnit.h"
#include "base/etMemory.h"

#include "room/basic/service/can/PCANRx.h"
#include "room/basic/service/can/PCANTx.h"
#include "HexagonCANDemo/PPingPong.h"
#include "room/basic/service/timing/PTimer.h"

#include "Application_Utils.h"


/* interface item IDs */
/* empty enum not generated */


void Application_init(Application* self){
	ET_MSC_LOGGER_SYNC_ENTRY("Application", "init")
	ET_MSC_LOGGER_SYNC_EXIT
}


void Application_receiveMessage(void* self, const void* ifitem, const etMessage* msg){
	ET_MSC_LOGGER_SYNC_ENTRY("Application", "_receiveMessage")
	
	ET_MSC_LOGGER_SYNC_EXIT
}


/*--------------------- operations ---------------------*/

