/**
 * @author generated by eTrice
 *
 * Source File of ProtocolClass PPingPong
 * 
 */

#include "PPingPong.h"
#include "debugging/etMSCLogger.h"
#include "PPingPong_Utils.h"


/*--------------------- port methods */

void PPingPongPort_pong(const PPingPongPort* self) {
	ET_MSC_LOGGER_SYNC_ENTRY("PPingPongPort", "pong")
		etPort_sendMessage(self, PPingPong_OUT_pong, 0, NULL);
	ET_MSC_LOGGER_SYNC_EXIT
}

void PPingPongReplPort_pong_broadcast(const PPingPongReplPort* self) {
	int i;
	ET_MSC_LOGGER_SYNC_ENTRY("PPingPongReplPort", "pong")
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		etPort_sendMessage((&((etReplPort*)self)->ports[i].port), PPingPong_OUT_pong, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

void PPingPongReplPort_pong(const PPingPongReplPort* self, int idx__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PPingPongReplPort", "pong")
	if (0<=idx__et && idx__et<((etReplPort*)self)->size) {
		etPort_sendMessage((&((etReplPort*)self)->ports[idx__et].port), PPingPong_OUT_pong, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

etInt32 PPingPongReplPort_getReplication(const PPingPongReplPort* self) {
	return ((etReplPort*)self)->size;
}



void PPingPongConjPort_ping(const PPingPongConjPort* self) {
	ET_MSC_LOGGER_SYNC_ENTRY("PPingPongConjPort", "ping")
		etPort_sendMessage(self, PPingPong_IN_ping, 0, NULL);
	ET_MSC_LOGGER_SYNC_EXIT
}

void PPingPongConjReplPort_ping_broadcast(const PPingPongConjReplPort* self) {
	int i;
	ET_MSC_LOGGER_SYNC_ENTRY("PPingPongConjReplPort", "ping")
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		etPort_sendMessage((&((etReplPort*)self)->ports[i].port), PPingPong_IN_ping, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

void PPingPongConjReplPort_ping(const PPingPongConjReplPort* self, int idx__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PPingPongConjReplPort", "ping")
	if (0<=idx__et && idx__et<((etReplPort*)self)->size) {
		etPort_sendMessage((&((etReplPort*)self)->ports[idx__et].port), PPingPong_IN_ping, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

etInt32 PPingPongConjReplPort_getReplication(const PPingPongConjReplPort* self) {
	return ((etReplPort*)self)->size;
}



