/**
 * @author generated by eTrice
 *
 * Header File of DataClass DSerialBuffer
 * 
 */

#ifndef _ROOM_BASIC_SERVICE_LOGGING_DSERIALBUFFER_H_
#define _ROOM_BASIC_SERVICE_LOGGING_DSERIALBUFFER_H_

#include "etDatatypes.h"


		
typedef struct {
	/*--------------------- attributes ---------------------*/
	 uint16 len;
	 uint8 buffer[100]
	;
} DSerialBuffer;



/*--------------------- operations ---------------------*/

/* deep copy */
void DSerialBuffer_deepCopy(DSerialBuffer* source, DSerialBuffer* target);


#endif /* _ROOM_BASIC_SERVICE_LOGGING_DSERIALBUFFER_H_ */

