/**
 * @author generated by eTrice
 *
 * Utils File of DataClass DSerialBuffer
 * 
 */

#ifndef _ROOM_BASIC_SERVICE_LOGGING_DSERIALBUFFER_UTILS_H_
#define _ROOM_BASIC_SERVICE_LOGGING_DSERIALBUFFER_UTILS_H_

#include "DSerialBuffer.h"

/*
 * access macros for operations and attributes
*/

/* operations */

/* attributes */
#define len (self->len)
#define buffer (self->buffer)

#endif /* _ROOM_BASIC_SERVICE_LOGGING_DSERIALBUFFER_UTILS_H_ */

