/**
 * @author generated by eTrice
 *
 * Header File of ActorClass ADoorController
 * 
 */

#ifndef _ELEVATORFREERTOS_MODEL_ADOORCONTROLLER_H_
#define _ELEVATORFREERTOS_MODEL_ADOORCONTROLLER_H_

#include "etDatatypes.h"
#include "messaging/etMessage.h"

#include "ElevatorFreeRTOS_Model/PDoorControl.h"
#include "room/basic/service/timing/PTimer.h"

/*--------------------- begin user code ---------------------*/
#include "etPlatform.h"
/*--------------------- end user code ---------------------*/

typedef struct ADoorController ADoorController;

/* const part of ActorClass (ROM) */
typedef struct ADoorController_const {
	/* simple ports */
	const PDoorControlPort ControlPort;
	
	/* data receive ports */

	/* saps */
	const PTimerConjPort timer;
	
	/* replicated ports */
	
	/* services */
} ADoorController_const;


/* constant for state machine data */
#define ADOORCONTROLLER_HISTORY_SIZE 2

/* variable part of ActorClass (RAM) */
struct ADoorController {
	const ADoorController_const* const constData;
	
	/* data send ports */
	
	/*--------------------- attributes ---------------------*/
	uint8 id;
	uint8 counter;
	
	
	/* state machine variables */
	etInt16 state;
	etInt16 history[ADOORCONTROLLER_HISTORY_SIZE];
};

void ADoorController_init(ADoorController* self);

void ADoorController_receiveMessage(void* self, const void* ifitem, const etMessage* msg);


/*--------------------- operations ---------------------*/


#endif /* _ELEVATORFREERTOS_MODEL_ADOORCONTROLLER_H_ */

