/**
 * @author generated by eTrice
 *
 * Source File of ActorClass ADoorController
 * 
 */

#include "ADoorController.h"

#include "modelbase/etActor.h"
#include "debugging/etLogger.h"
#include "debugging/etMSCLogger.h"
#include "etUnit/etUnit.h"
#include "base/etMemory.h"

#include "ElevatorFreeRTOS_Model/PDoorControl.h"
#include "room/basic/service/timing/PTimer.h"

#include "ADoorController_Utils.h"


/* interface item IDs */
enum interface_items {
	IFITEM_ControlPort = 1,
	IFITEM_timer = 2
};

/* state IDs */
enum state_ids {
	NO_STATE = 0,
	STATE_TOP = 1,
	STATE_waitForId = 2,
	STATE_close = 3,
	STATE_opening = 4,
	STATE_open = 5,
	STATE_closing = 6,
	STATE_MAX = 7
};

/* transition chains */
enum chain_ids {
	CHAIN_TRANS_INITIAL_TO__waitForId = 1,
	CHAIN_TRANS_setFloor_FROM_waitForId_TO_close_BY_setFloorControlPort = 2,
	CHAIN_TRANS_tr0_FROM_close_TO_opening_BY_openControlPort = 3,
	CHAIN_TRANS_tr3_FROM_opening_TO_cp0_BY_timeouttimer = 4,
	CHAIN_TRANS_tr4_FROM_open_TO_closing_BY_timeouttimer = 5,
	CHAIN_TRANS_tr5_FROM_closing_TO_cp1_BY_timeouttimer = 6,
	CHAIN_TRANS_tr8_FROM_closing_TO_opening_BY_openControlPort = 7,
	CHAIN_TRANS_tr9_FROM_open_TO_open_BY_openControlPort_tr9 = 8
};

/* triggers */
enum triggers {
	POLLING = 0,
	TRIG_ControlPort__setFloor = IFITEM_ControlPort + EVT_SHIFT*PDoorControl_IN_setFloor,
	TRIG_ControlPort__open = IFITEM_ControlPort + EVT_SHIFT*PDoorControl_IN_open,
	TRIG_ControlPort__close = IFITEM_ControlPort + EVT_SHIFT*PDoorControl_IN_close,
	TRIG_timer__timeout = IFITEM_timer + EVT_SHIFT*PTimer_OUT_timeout
};


static void setState(ADoorController* self, etInt16 new_state) {
	self->state = new_state;
}

static etInt16 getState(ADoorController* self) {
	return self->state;
}

/* Entry and Exit Codes */

/* Action Codes */
static void action_TRANS_setFloor_FROM_waitForId_TO_close_BY_setFloorControlPort(ADoorController* self, const InterfaceItemBase* ifitem, uint8 data) {
	id=data;
	writeToDoor(id,0);
}
static void action_TRANS_tr0_FROM_close_TO_opening_BY_openControlPort(ADoorController* self, const InterfaceItemBase* ifitem) {
	timer_startTimeout(50);
	counter=0;
}
static void action_TRANS_tr1_FROM_cp0_TO_open(ADoorController* self, const InterfaceItemBase* ifitem) {
	//ControlPort.done();
	timer_startTimeout(1000);
}
static void action_TRANS_tr2_FROM_cp0_TO_opening_COND_tr2(ADoorController* self, const InterfaceItemBase* ifitem) {
	timer_startTimeout(50);
	writeToDoor(id,counter);
}
static void action_TRANS_tr3_FROM_opening_TO_cp0_BY_timeouttimer(ADoorController* self, const InterfaceItemBase* ifitem) {
	counter++;
}
static void action_TRANS_tr4_FROM_open_TO_closing_BY_timeouttimer(ADoorController* self, const InterfaceItemBase* ifitem) {
	timer_startTimeout(50);
	counter=12;
}
static void action_TRANS_tr5_FROM_closing_TO_cp1_BY_timeouttimer(ADoorController* self, const InterfaceItemBase* ifitem) {
	counter--;
}
static void action_TRANS_tr6_FROM_cp1_TO_close(ADoorController* self, const InterfaceItemBase* ifitem) {
	writeToDoor(id,0);
	ControlPort_done();
}
static void action_TRANS_tr7_FROM_cp1_TO_closing_COND_tr7(ADoorController* self, const InterfaceItemBase* ifitem) {
	timer_startTimeout(50);
	writeToDoor(id,counter);
}
static void action_TRANS_tr9_FROM_open_TO_open_BY_openControlPort_tr9(ADoorController* self, const InterfaceItemBase* ifitem) {
	timer_kill();
	timer_startTimeout(1000);
}

/**
 * calls exit codes while exiting from the current state to one of its
 * parent states while remembering the history
 * @param current__et - the current state
 * @param to - the final parent state
 */
static void exitTo(ADoorController* self, etInt16 current__et, etInt16 to) {
	while (current__et!=to) {
		switch (current__et) {
			case STATE_waitForId:
				self->history[STATE_TOP] = STATE_waitForId;
				current__et = STATE_TOP;
				break;
			case STATE_close:
				self->history[STATE_TOP] = STATE_close;
				current__et = STATE_TOP;
				break;
			case STATE_opening:
				self->history[STATE_TOP] = STATE_opening;
				current__et = STATE_TOP;
				break;
			case STATE_open:
				self->history[STATE_TOP] = STATE_open;
				current__et = STATE_TOP;
				break;
			case STATE_closing:
				self->history[STATE_TOP] = STATE_closing;
				current__et = STATE_TOP;
				break;
			default:
				/* should not occur */
				break;
		}
	}
}

/**
 * calls action, entry and exit codes along a transition chain. The generic data are cast to typed data
 * matching the trigger of this chain. The ID of the final state is returned
 * @param chain__et - the chain ID
 * @param generic_data__et - the generic data pointer
 * @return the +/- ID of the final state either with a positive sign, that indicates to execute the state's entry code, or a negative sign vice versa
 */
static etInt16 executeTransitionChain(ADoorController* self, int chain__et, const InterfaceItemBase* ifitem, void* generic_data__et) {
	switch (chain__et) {
		case CHAIN_TRANS_INITIAL_TO__waitForId:
		{
			return STATE_waitForId;
		}
		case CHAIN_TRANS_setFloor_FROM_waitForId_TO_close_BY_setFloorControlPort:
		{
			uint8 data = *((uint8*) generic_data__et);
			action_TRANS_setFloor_FROM_waitForId_TO_close_BY_setFloorControlPort(self, ifitem, data);
			return STATE_close;
		}
		case CHAIN_TRANS_tr0_FROM_close_TO_opening_BY_openControlPort:
		{
			action_TRANS_tr0_FROM_close_TO_opening_BY_openControlPort(self, ifitem);
			return STATE_opening;
		}
		case CHAIN_TRANS_tr3_FROM_opening_TO_cp0_BY_timeouttimer:
		{
			action_TRANS_tr3_FROM_opening_TO_cp0_BY_timeouttimer(self, ifitem);
			if (counter<11) {
			action_TRANS_tr2_FROM_cp0_TO_opening_COND_tr2(self, ifitem);
			return STATE_opening;}
			else {
			action_TRANS_tr1_FROM_cp0_TO_open(self, ifitem);
			return STATE_open;}
		}
		case CHAIN_TRANS_tr4_FROM_open_TO_closing_BY_timeouttimer:
		{
			action_TRANS_tr4_FROM_open_TO_closing_BY_timeouttimer(self, ifitem);
			return STATE_closing;
		}
		case CHAIN_TRANS_tr5_FROM_closing_TO_cp1_BY_timeouttimer:
		{
			action_TRANS_tr5_FROM_closing_TO_cp1_BY_timeouttimer(self, ifitem);
			if (counter>0) {
			action_TRANS_tr7_FROM_cp1_TO_closing_COND_tr7(self, ifitem);
			return STATE_closing;}
			else {
			action_TRANS_tr6_FROM_cp1_TO_close(self, ifitem);
			return STATE_close;}
		}
		case CHAIN_TRANS_tr8_FROM_closing_TO_opening_BY_openControlPort:
		{
			return STATE_opening;
		}
		case CHAIN_TRANS_tr9_FROM_open_TO_open_BY_openControlPort_tr9:
		{
			action_TRANS_tr9_FROM_open_TO_open_BY_openControlPort_tr9(self, ifitem);
			return STATE_open;
		}
			default:
				/* should not occur */
				break;
	}
	return NO_STATE;
}

/**
 * calls entry codes while entering a state's history. The ID of the final leaf state is returned
 * @param state__et - the state which is entered
 * @return - the ID of the final leaf state
 */
static etInt16 enterHistory(ADoorController* self, etInt16 state__et) {
	boolean skip_entry__et = ET_FALSE;
	if (state__et >= STATE_MAX) {
		state__et = (etInt16) (state__et - STATE_MAX);
		skip_entry__et = ET_TRUE;
	}
	while (ET_TRUE) {
		switch (state__et) {
			case STATE_waitForId:
				/* in leaf state: return state id */
				return STATE_waitForId;
			case STATE_close:
				/* in leaf state: return state id */
				return STATE_close;
			case STATE_opening:
				/* in leaf state: return state id */
				return STATE_opening;
			case STATE_open:
				/* in leaf state: return state id */
				return STATE_open;
			case STATE_closing:
				/* in leaf state: return state id */
				return STATE_closing;
			case STATE_TOP:
				state__et = self->history[STATE_TOP];
				break;
			default:
				/* should not occur */
				break;
		}
		skip_entry__et = ET_FALSE;
	}
	/* return NO_STATE; // required by CDT but detected as unreachable by JDT because of while (true) */
}

static void ADoorController_executeInitTransition(ADoorController* self) {
	int chain__et = CHAIN_TRANS_INITIAL_TO__waitForId;
	etInt16 next__et = executeTransitionChain(self, chain__et, NULL, NULL);
	next__et = enterHistory(self, next__et);
	setState(self, next__et);
}

/* receiveEvent contains the main implementation of the FSM */
static void ADoorController_receiveEvent(ADoorController* self, InterfaceItemBase* ifitem, int evt, void* generic_data__et) {
	int trigger__et = ifitem->localId + EVT_SHIFT*evt;
	int chain__et = NOT_CAUGHT;
	etInt16 catching_state__et = NO_STATE;
	((void)trigger__et);	/* avoids unused warning */
	
	if (!handleSystemEvent(ifitem, evt, generic_data__et)) {
		switch (getState(self)) {
			case STATE_waitForId:
				switch(trigger__et) {
						case TRIG_ControlPort__setFloor:
							{
								chain__et = CHAIN_TRANS_setFloor_FROM_waitForId_TO_close_BY_setFloorControlPort;
								catching_state__et = STATE_TOP;
							}
						break;
						default:
							/* should not occur */
							break;
				}
				break;
			case STATE_close:
				switch(trigger__et) {
						case TRIG_ControlPort__open:
							{
								chain__et = CHAIN_TRANS_tr0_FROM_close_TO_opening_BY_openControlPort;
								catching_state__et = STATE_TOP;
							}
						break;
						default:
							/* should not occur */
							break;
				}
				break;
			case STATE_opening:
				switch(trigger__et) {
						case TRIG_timer__timeout:
							{
								chain__et = CHAIN_TRANS_tr3_FROM_opening_TO_cp0_BY_timeouttimer;
								catching_state__et = STATE_TOP;
							}
						break;
						default:
							/* should not occur */
							break;
				}
				break;
			case STATE_open:
				switch(trigger__et) {
						case TRIG_timer__timeout:
							{
								chain__et = CHAIN_TRANS_tr4_FROM_open_TO_closing_BY_timeouttimer;
								catching_state__et = STATE_TOP;
							}
						break;
						case TRIG_ControlPort__open:
							{
								chain__et = CHAIN_TRANS_tr9_FROM_open_TO_open_BY_openControlPort_tr9;
								catching_state__et = STATE_TOP;
							}
						break;
						default:
							/* should not occur */
							break;
				}
				break;
			case STATE_closing:
				switch(trigger__et) {
						case TRIG_timer__timeout:
							{
								chain__et = CHAIN_TRANS_tr5_FROM_closing_TO_cp1_BY_timeouttimer;
								catching_state__et = STATE_TOP;
							}
						break;
						case TRIG_ControlPort__open:
							{
								chain__et = CHAIN_TRANS_tr8_FROM_closing_TO_opening_BY_openControlPort;
								catching_state__et = STATE_TOP;
							}
						break;
						default:
							/* should not occur */
							break;
				}
				break;
			default:
				/* should not occur */
				break;
		}
	}
	if (chain__et != NOT_CAUGHT) {
		exitTo(self, getState(self), catching_state__et);
		{
			etInt16 next__et = executeTransitionChain(self, chain__et, ifitem, generic_data__et);
			next__et = enterHistory(self, next__et);
			setState(self, next__et);
		}
	}
}

void ADoorController_init(ADoorController* self){
	ET_MSC_LOGGER_SYNC_ENTRY("ADoorController", "init")
	self->state = STATE_TOP;
	{
		int i;
		for (i=0; i<ADOORCONTROLLER_HISTORY_SIZE; ++i)
			self->history[i] = NO_STATE;
	}
	ADoorController_executeInitTransition(self);
	ET_MSC_LOGGER_SYNC_EXIT
}


void ADoorController_receiveMessage(void* self, const void* ifitem, const etMessage* msg){
	ET_MSC_LOGGER_SYNC_ENTRY("ADoorController", "_receiveMessage")
	
	ADoorController_receiveEvent(self, (etPort*)ifitem, msg->evtID, (void*)(((char*)msg)+MEM_CEIL(sizeof(etMessage))));
	
	ET_MSC_LOGGER_SYNC_EXIT
}


/*--------------------- operations ---------------------*/

