/**
 * @author generated by eTrice
 *
 * Source File of ActorClass AElevatorMainController
 * 
 */

#include "AElevatorMainController.h"

#include "modelbase/etActor.h"
#include "debugging/etLogger.h"
#include "debugging/etMSCLogger.h"
#include "etUnit/etUnit.h"
#include "base/etMemory.h"

#include "ElevatorFreeRTOS_Model/PCabineControl.h"
#include "ElevatorFreeRTOS_Model/PFloorControl.h"
#include "ElevatorFreeRTOS_Model/PMainControllerStatus.h"
#include "ElevatorFreeRTOS_Model/PMotorControl.h"
#include "ElevatorFreeRTOS_Model/PStartGenerator.h"
#include "room/basic/service/timing/PTimer.h"

#include "AElevatorMainController_Utils.h"


/* interface item IDs */
enum interface_items {
	IFITEM_CabinePort = 2,
	IFITEM_MotorPort = 3,
	IFITEM_FloorPort = 4,
	IFITEM_controlPort = 5,
	IFITEM_HelperPort = 1,
	IFITEM_timer = 6
};

/* state IDs */
enum state_ids {
	NO_STATE = 0,
	STATE_TOP = 1,
	STATE_idle = 2,
	STATE_goingDown = 3,
	STATE_goingUp = 4,
	STATE_idle_doorOpen = 5,
	STATE_idle_doorClosed = 6,
	STATE_goingDown_running = 7,
	STATE_goingDown_halted = 8,
	STATE_goingUp_running = 9,
	STATE_goingUp_halted = 10,
	STATE_MAX = 11
};

/* transition chains */
enum chain_ids {
	CHAIN_TRANS_INITIAL_TO__idle = 1,
	CHAIN_TRANS_tr0_FROM_tp0_TO_tp0_BY_floorReachedMotorPort_tr0 = 2,
	CHAIN_TRANS_tr1_FROM_tp1_TO_tp1_BY_requestUpFloorPort_tr1 = 3,
	CHAIN_TRANS_tr2_FROM_tp1_TO_tp1_BY_requestDownFloorPort_tr2 = 4,
	CHAIN_TRANS_tr3_FROM_tp1_TO_tp1_BY_floorRequestCabinePort_tr3 = 5,
	CHAIN_TRANS_tr10_FROM_tp2_TO_tp2_BY_checkHelperPort_tr10 = 6,
	CHAIN_TRANS_tr15_FROM_tp3_TO_tp3_BY_requestIdlecontrolPort_tr15 = 7,
	CHAIN_TRANS_tr16_FROM_tp3_TO_tp3_BY_getStatuscontrolPort_tr16 = 8,
	CHAIN_TRANS_tr17_FROM_tp3_TO_tp3_BY_requestFloorcontrolPort_tr17 = 9,
	CHAIN_TRANS_tr18_FROM_tp4_TO_tp4_BY_setIdleFloorcontrolPort_tr18 = 10,
	CHAIN_TRANS_tr13_FROM_tp4_TO_tp4_BY_setIdleTimecontrolPort_tr13 = 11,
	CHAIN_idle_TRANS_tr1_FROM_doorOpen_TO_cp0_BY_doneCabinePort = 12,
	CHAIN_idle_TRANS_tr2_FROM_doorOpen_TO_cp0_BY_doneFloorPort = 13,
	CHAIN_idle_TRANS_tr5_FROM_doorClosed_TO_tp1_BY_checkHelperPort = 14,
	CHAIN_idle_TRANS_INITIAL_TO__doorClosed = 15,
	CHAIN_idle_TRANS_tr8_FROM_doorOpen_TO_doorOpen_BY_checkHelperPort_tr8 = 16,
	CHAIN_idle_TRANS_tr10_FROM_doorClosed_TO_doorOpen_BY_doorRequestCabinePort = 17,
	CHAIN_idle_TRANS_tr11_FROM_doorOpen_TO_doorOpen_BY_doorRequestCabinePort_tr11 = 18,
	CHAIN_idle_TRANS_tr12_FROM_tp4_TO_tp4_BY_requestIdlecontrolPort_tr12 = 19,
	CHAIN_idle_TRANS_tr9_FROM_doorClosed_TO_tp1_BY_timeouttimer = 20,
	CHAIN_goingDown_TRANS_tr1_FROM_running_TO_cp0_BY_floorReachedMotorPort = 21,
	CHAIN_goingDown_TRANS_tr14_FROM_halted_TO_cp4_BY_doneCabinePort = 22,
	CHAIN_goingDown_TRANS_tr15_FROM_halted_TO_cp4_BY_doneFloorPort = 23,
	CHAIN_goingDown_TRANS_tr5_FROM_halted_TO_halted_BY_checkHelperPort_tr5 = 24,
	CHAIN_goingDown_TRANS_tr6_FROM_halted_TO_halted_BY_doorRequestCabinePort_tr6 = 25,
	CHAIN_goingUp_TRANS_tr1_FROM_running_TO_cp0_BY_floorReachedMotorPort = 26,
	CHAIN_goingUp_TRANS_tr5_FROM_halted_TO_cp1_BY_doneCabinePort = 27,
	CHAIN_goingUp_TRANS_tr6_FROM_halted_TO_cp1_BY_doneFloorPort = 28,
	CHAIN_goingUp_TRANS_tr4_FROM_halted_TO_halted_BY_checkHelperPort_tr4 = 29,
	CHAIN_goingUp_TRANS_tr14_FROM_halted_TO_halted_BY_doorRequestCabinePort_tr14 = 30
};

/* triggers */
enum triggers {
	POLLING = 0,
	TRIG_HelperPort__check = IFITEM_HelperPort + EVT_SHIFT*PStartGenerator_OUT_check,
	TRIG_HelperPort__checkDoorStatus = IFITEM_HelperPort + EVT_SHIFT*PStartGenerator_OUT_checkDoorStatus,
	TRIG_CabinePort__floorRequest = IFITEM_CabinePort + EVT_SHIFT*PCabineControl_OUT_floorRequest,
	TRIG_CabinePort__doorRequest = IFITEM_CabinePort + EVT_SHIFT*PCabineControl_OUT_doorRequest,
	TRIG_CabinePort__done = IFITEM_CabinePort + EVT_SHIFT*PCabineControl_OUT_done,
	TRIG_MotorPort__floorReached = IFITEM_MotorPort + EVT_SHIFT*PMotorControl_OUT_floorReached,
	TRIG_FloorPort__requestUp = IFITEM_FloorPort + EVT_SHIFT*PFloorControl_OUT_requestUp,
	TRIG_FloorPort__requestDown = IFITEM_FloorPort + EVT_SHIFT*PFloorControl_OUT_requestDown,
	TRIG_FloorPort__done = IFITEM_FloorPort + EVT_SHIFT*PFloorControl_OUT_done,
	TRIG_controlPort__getStatus = IFITEM_controlPort + EVT_SHIFT*PMainControllerStatus_IN_getStatus,
	TRIG_controlPort__setIdleFloor = IFITEM_controlPort + EVT_SHIFT*PMainControllerStatus_IN_setIdleFloor,
	TRIG_controlPort__setIdleTime = IFITEM_controlPort + EVT_SHIFT*PMainControllerStatus_IN_setIdleTime,
	TRIG_controlPort__requestIdle = IFITEM_controlPort + EVT_SHIFT*PMainControllerStatus_IN_requestIdle,
	TRIG_controlPort__requestFloor = IFITEM_controlPort + EVT_SHIFT*PMainControllerStatus_IN_requestFloor,
	TRIG_timer__timeout = IFITEM_timer + EVT_SHIFT*PTimer_OUT_timeout
};


static void setState(AElevatorMainController* self, etInt16 new_state) {
	self->state = new_state;
}

static etInt16 getState(AElevatorMainController* self) {
	return self->state;
}

/* Entry and Exit Codes */
static void entry_idle(AElevatorMainController* self) {
	if(idleRequest){
		idleRequest=0;
		clearAllRequests();
		controlPort_idle();
		}
}
static void entry_idle_doorOpen(AElevatorMainController* self) {
	reportState=4;
}
static void entry_idle_doorClosed(AElevatorMainController* self) {
	reportState=3;
	
	if ( (floor!=idleFloor) && (idleTime > 0) ) {
		timer_startTimeout(idleTime * 1000);	
	}
	
	//if ( (floor!=idleFloor) && (idleTime > 0) ) {
	//	timer.startTimeout(idleTime * 1000);	
	//}
	//transitioncode:
	//upRequests[idleFloor]=1;
}
static void entry_goingDown_running(AElevatorMainController* self) {
	MotorPort_goDownOneFloor();
	reportState=2;
}
static void entry_goingDown_halted(AElevatorMainController* self) {
	reportState=4;
}
static void entry_goingUp(AElevatorMainController* self) {
	reportState=1;
}
static void entry_goingUp_running(AElevatorMainController* self) {
	MotorPort_goUpOneFloor();
	reportState=1;
}
static void entry_goingUp_halted(AElevatorMainController* self) {
	reportState=4;
}

/* Action Codes */
static void action_TRANS_INITIAL_TO__idle(AElevatorMainController* self) {
	unsigned char i;
	for(i=0;i<5;i++){
		FloorPort_setFloor(i, i);
		upRequests[i]=0;
		downRequests[i]=0;
	}
	floor=0;
	MotorPort_goUpOneFloor();
	idleRequest=0;
	reportState=0;
	idleFloor=2;
	idleTime=10;
}
static void action_TRANS_tr0_FROM_tp0_TO_tp0_BY_floorReachedMotorPort_tr0(AElevatorMainController* self, const InterfaceItemBase* ifitem, uint8 data) {
	CabinePort_set7seg(data+1);
	floor=data;
}
static void action_TRANS_tr7_FROM_cp0_TO_idle_tp0(AElevatorMainController* self, const InterfaceItemBase* ifitem) {
	FloorPort_openDoor(floor);
	CabinePort_openDoor();
	clearFloorRequests();
}
static void action_TRANS_tr1_FROM_tp1_TO_tp1_BY_requestUpFloorPort_tr1(AElevatorMainController* self, const InterfaceItemBase* ifitem) {
	unsigned char idx=((etReplSubPort*)ifitem)->index;
	FloorPort_requestUpAck(idx);
	upRequests[idx]=1;
	HelperPort_requestCheck();
}
static void action_TRANS_tr2_FROM_tp1_TO_tp1_BY_requestDownFloorPort_tr2(AElevatorMainController* self, const InterfaceItemBase* ifitem) {
	unsigned char idx=((etReplSubPort*)ifitem)->index;
	FloorPort_requestDownAck(idx);
	downRequests[idx]=1;
	HelperPort_requestCheck();
}
static void action_TRANS_tr3_FROM_tp1_TO_tp1_BY_floorRequestCabinePort_tr3(AElevatorMainController* self, const InterfaceItemBase* ifitem, uint8 data) {
	CabinePort_floorRequestAck(data);
	upRequests[data]=1;
	downRequests[data]=1;
	HelperPort_requestCheck();
}
static void action_TRANS_tr15_FROM_tp3_TO_tp3_BY_requestIdlecontrolPort_tr15(AElevatorMainController* self, const InterfaceItemBase* ifitem) {
	idleRequest=1;
}
static void action_TRANS_tr16_FROM_tp3_TO_tp3_BY_getStatuscontrolPort_tr16(AElevatorMainController* self, const InterfaceItemBase* ifitem) {
	uint32 d;
	uint8 r=0, i, mask;
	
	d = floor;
	d<<=8;
	d |= reportState;
	d<<=8;
	
	mask=1;
	for(i=0;i<5;i++){
		if(upRequests[i] || downRequests[i]) r|=mask;
		mask<<=1;
		}
	d |= r;
	
	controlPort_status(d);
}
static void action_TRANS_tr17_FROM_tp3_TO_tp3_BY_requestFloorcontrolPort_tr17(AElevatorMainController* self, const InterfaceItemBase* ifitem) {
	floorRequest=1;
}
static void action_TRANS_tr18_FROM_tp4_TO_tp4_BY_setIdleFloorcontrolPort_tr18(AElevatorMainController* self, const InterfaceItemBase* ifitem, uint8 data) {
	if (data < 5){
		idleFloor=data;
		}
}
static void action_TRANS_tr13_FROM_tp4_TO_tp4_BY_setIdleTimecontrolPort_tr13(AElevatorMainController* self, const InterfaceItemBase* ifitem, uint8 data) {
	if (data < 60){
		idleTime=data;
		}
}
static void action_idle_TRANS_tr0_FROM_tp0_TO_doorOpen(AElevatorMainController* self, const InterfaceItemBase* ifitem) {
	doorStatus=0;
}
static void action_idle_TRANS_tr1_FROM_doorOpen_TO_cp0_BY_doneCabinePort(AElevatorMainController* self, const InterfaceItemBase* ifitem) {
	doorStatus++;
}
static void action_idle_TRANS_tr2_FROM_doorOpen_TO_cp0_BY_doneFloorPort(AElevatorMainController* self, const InterfaceItemBase* ifitem) {
	doorStatus++;
}
static void action_idle_TRANS_tr4_FROM_cp0_TO_doorClosed_COND_tr4(AElevatorMainController* self, const InterfaceItemBase* ifitem) {
	if (isRequestAbove() || isRequestBelow()){
	HelperPort_requestCheck();
	}
}
static void action_idle_TRANS_tr5_FROM_doorClosed_TO_tp1_BY_checkHelperPort(AElevatorMainController* self, const InterfaceItemBase* ifitem) {
	timer_kill();
}
static void action_idle_TRANS_tr8_FROM_doorOpen_TO_doorOpen_BY_checkHelperPort_tr8(AElevatorMainController* self, const InterfaceItemBase* ifitem) {
	if (isRequestHere()){
		CabinePort_openDoor();
		FloorPort_openDoor(floor);
		doorStatus=0;
		clearFloorRequests();
	}
}
static void action_idle_TRANS_tr10_FROM_doorClosed_TO_doorOpen_BY_doorRequestCabinePort(AElevatorMainController* self, const InterfaceItemBase* ifitem) {
	FloorPort_openDoor(floor);
	CabinePort_openDoor();
	doorStatus=0;
	timer_kill();
}
static void action_idle_TRANS_tr11_FROM_doorOpen_TO_doorOpen_BY_doorRequestCabinePort_tr11(AElevatorMainController* self, const InterfaceItemBase* ifitem) {
	FloorPort_openDoor(floor);
	CabinePort_openDoor();
	doorStatus=0;
}
static void action_idle_TRANS_tr12_FROM_tp4_TO_tp4_BY_requestIdlecontrolPort_tr12(AElevatorMainController* self, const InterfaceItemBase* ifitem) {
	controlPort_idle();
}
static void action_idle_TRANS_tr9_FROM_doorClosed_TO_tp1_BY_timeouttimer(AElevatorMainController* self, const InterfaceItemBase* ifitem) {
	upRequests[idleFloor]=1;
}
static void action_goingDown_TRANS_tr1_FROM_running_TO_cp0_BY_floorReachedMotorPort(AElevatorMainController* self, const InterfaceItemBase* ifitem, uint8 data) {
	floor=data;
	CabinePort_set7seg(data+1);
}
static void action_goingDown_TRANS_tr3_FROM_cp0_TO_halted_COND_tr3(AElevatorMainController* self, const InterfaceItemBase* ifitem, uint8 data) {
	clearFloorRequests();
	if (floorRequest){
		floorRequest=0;
		controlPort_floor(floor);}
	
	FloorPort_openDoor(floor);
	CabinePort_openDoor();
	doorStatus=0;
}
static void action_goingDown_TRANS_tr14_FROM_halted_TO_cp4_BY_doneCabinePort(AElevatorMainController* self, const InterfaceItemBase* ifitem) {
	doorStatus++;
}
static void action_goingDown_TRANS_tr15_FROM_halted_TO_cp4_BY_doneFloorPort(AElevatorMainController* self, const InterfaceItemBase* ifitem) {
	doorStatus++;
}
static void action_goingDown_TRANS_tr5_FROM_halted_TO_halted_BY_checkHelperPort_tr5(AElevatorMainController* self, const InterfaceItemBase* ifitem) {
	if (isRequestHere()){
		CabinePort_openDoor();
		FloorPort_openDoor(floor);
		doorStatus=0;
		clearFloorRequests();
	}
}
static void action_goingDown_TRANS_tr6_FROM_halted_TO_halted_BY_doorRequestCabinePort_tr6(AElevatorMainController* self, const InterfaceItemBase* ifitem) {
	FloorPort_openDoor(floor);
	CabinePort_openDoor();
	doorStatus=0;
}
static void action_goingUp_TRANS_tr1_FROM_running_TO_cp0_BY_floorReachedMotorPort(AElevatorMainController* self, const InterfaceItemBase* ifitem, uint8 data) {
	floor=data;
	CabinePort_set7seg(data+1);
}
static void action_goingUp_TRANS_tr3_FROM_cp0_TO_halted_COND_tr3(AElevatorMainController* self, const InterfaceItemBase* ifitem, uint8 data) {
	clearFloorRequests();
	if (floorRequest){
		floorRequest=0;
		controlPort_floor(floor);}
	
	FloorPort_openDoor(floor);
	CabinePort_openDoor();
	doorStatus=0;
}
static void action_goingUp_TRANS_tr5_FROM_halted_TO_cp1_BY_doneCabinePort(AElevatorMainController* self, const InterfaceItemBase* ifitem) {
	doorStatus++;
}
static void action_goingUp_TRANS_tr6_FROM_halted_TO_cp1_BY_doneFloorPort(AElevatorMainController* self, const InterfaceItemBase* ifitem) {
	doorStatus++;
}
static void action_goingUp_TRANS_tr4_FROM_halted_TO_halted_BY_checkHelperPort_tr4(AElevatorMainController* self, const InterfaceItemBase* ifitem) {
	if (isRequestHere()){
		CabinePort_openDoor();
		FloorPort_openDoor(floor);
		doorStatus=0;
		clearFloorRequests();
	}
}
static void action_goingUp_TRANS_tr14_FROM_halted_TO_halted_BY_doorRequestCabinePort_tr14(AElevatorMainController* self, const InterfaceItemBase* ifitem) {
	FloorPort_openDoor(floor);
	CabinePort_openDoor();
	doorStatus=0;
}

/**
 * calls exit codes while exiting from the current state to one of its
 * parent states while remembering the history
 * @param current__et - the current state
 * @param to - the final parent state
 * @param handler__et - entry and exit codes are called only if not handler (for handler TransitionPoints)
 */
static void exitTo(AElevatorMainController* self, etInt16 current__et, etInt16 to, boolean handler__et) {
	while (current__et!=to) {
		switch (current__et) {
			case STATE_idle:
				self->history[STATE_TOP] = STATE_idle;
				current__et = STATE_TOP;
				break;
			case STATE_idle_doorOpen:
				self->history[STATE_idle] = STATE_idle_doorOpen;
				current__et = STATE_idle;
				break;
			case STATE_idle_doorClosed:
				self->history[STATE_idle] = STATE_idle_doorClosed;
				current__et = STATE_idle;
				break;
			case STATE_goingDown:
				self->history[STATE_TOP] = STATE_goingDown;
				current__et = STATE_TOP;
				break;
			case STATE_goingDown_running:
				self->history[STATE_goingDown] = STATE_goingDown_running;
				current__et = STATE_goingDown;
				break;
			case STATE_goingDown_halted:
				self->history[STATE_goingDown] = STATE_goingDown_halted;
				current__et = STATE_goingDown;
				break;
			case STATE_goingUp:
				self->history[STATE_TOP] = STATE_goingUp;
				current__et = STATE_TOP;
				break;
			case STATE_goingUp_running:
				self->history[STATE_goingUp] = STATE_goingUp_running;
				current__et = STATE_goingUp;
				break;
			case STATE_goingUp_halted:
				self->history[STATE_goingUp] = STATE_goingUp_halted;
				current__et = STATE_goingUp;
				break;
			default:
				/* should not occur */
				break;
		}
	}
}

/**
 * calls action, entry and exit codes along a transition chain. The generic data are cast to typed data
 * matching the trigger of this chain. The ID of the final state is returned
 * @param chain__et - the chain ID
 * @param generic_data__et - the generic data pointer
 * @return the +/- ID of the final state either with a positive sign, that indicates to execute the state's entry code, or a negative sign vice versa
 */
static etInt16 executeTransitionChain(AElevatorMainController* self, int chain__et, const InterfaceItemBase* ifitem, void* generic_data__et) {
	switch (chain__et) {
		case CHAIN_TRANS_INITIAL_TO__idle:
		{
			action_TRANS_INITIAL_TO__idle(self);
			return STATE_idle;
		}
		case CHAIN_TRANS_tr0_FROM_tp0_TO_tp0_BY_floorReachedMotorPort_tr0:
		{
			uint8 data = *((uint8*) generic_data__et);
			action_TRANS_tr0_FROM_tp0_TO_tp0_BY_floorReachedMotorPort_tr0(self, ifitem, data);
			return STATE_TOP + STATE_MAX;
		}
		case CHAIN_TRANS_tr1_FROM_tp1_TO_tp1_BY_requestUpFloorPort_tr1:
		{
			action_TRANS_tr1_FROM_tp1_TO_tp1_BY_requestUpFloorPort_tr1(self, ifitem);
			return STATE_TOP + STATE_MAX;
		}
		case CHAIN_TRANS_tr2_FROM_tp1_TO_tp1_BY_requestDownFloorPort_tr2:
		{
			action_TRANS_tr2_FROM_tp1_TO_tp1_BY_requestDownFloorPort_tr2(self, ifitem);
			return STATE_TOP + STATE_MAX;
		}
		case CHAIN_TRANS_tr3_FROM_tp1_TO_tp1_BY_floorRequestCabinePort_tr3:
		{
			uint8 data = *((uint8*) generic_data__et);
			action_TRANS_tr3_FROM_tp1_TO_tp1_BY_floorRequestCabinePort_tr3(self, ifitem, data);
			return STATE_TOP + STATE_MAX;
		}
		case CHAIN_TRANS_tr10_FROM_tp2_TO_tp2_BY_checkHelperPort_tr10:
		{
			return STATE_TOP + STATE_MAX;
		}
		case CHAIN_TRANS_tr15_FROM_tp3_TO_tp3_BY_requestIdlecontrolPort_tr15:
		{
			action_TRANS_tr15_FROM_tp3_TO_tp3_BY_requestIdlecontrolPort_tr15(self, ifitem);
			return STATE_TOP + STATE_MAX;
		}
		case CHAIN_TRANS_tr16_FROM_tp3_TO_tp3_BY_getStatuscontrolPort_tr16:
		{
			action_TRANS_tr16_FROM_tp3_TO_tp3_BY_getStatuscontrolPort_tr16(self, ifitem);
			return STATE_TOP + STATE_MAX;
		}
		case CHAIN_TRANS_tr17_FROM_tp3_TO_tp3_BY_requestFloorcontrolPort_tr17:
		{
			action_TRANS_tr17_FROM_tp3_TO_tp3_BY_requestFloorcontrolPort_tr17(self, ifitem);
			return STATE_TOP + STATE_MAX;
		}
		case CHAIN_TRANS_tr18_FROM_tp4_TO_tp4_BY_setIdleFloorcontrolPort_tr18:
		{
			uint8 data = *((uint8*) generic_data__et);
			action_TRANS_tr18_FROM_tp4_TO_tp4_BY_setIdleFloorcontrolPort_tr18(self, ifitem, data);
			return STATE_TOP + STATE_MAX;
		}
		case CHAIN_TRANS_tr13_FROM_tp4_TO_tp4_BY_setIdleTimecontrolPort_tr13:
		{
			uint8 data = *((uint8*) generic_data__et);
			action_TRANS_tr13_FROM_tp4_TO_tp4_BY_setIdleTimecontrolPort_tr13(self, ifitem, data);
			return STATE_TOP + STATE_MAX;
		}
		case CHAIN_idle_TRANS_tr1_FROM_doorOpen_TO_cp0_BY_doneCabinePort:
		{
			action_idle_TRANS_tr1_FROM_doorOpen_TO_cp0_BY_doneCabinePort(self, ifitem);
			if (doorStatus>1) {
			action_idle_TRANS_tr4_FROM_cp0_TO_doorClosed_COND_tr4(self, ifitem);
			return STATE_idle_doorClosed;}
			else {
			return STATE_idle_doorOpen;}
		}
		case CHAIN_idle_TRANS_tr2_FROM_doorOpen_TO_cp0_BY_doneFloorPort:
		{
			action_idle_TRANS_tr2_FROM_doorOpen_TO_cp0_BY_doneFloorPort(self, ifitem);
			if (doorStatus>1) {
			action_idle_TRANS_tr4_FROM_cp0_TO_doorClosed_COND_tr4(self, ifitem);
			return STATE_idle_doorClosed;}
			else {
			return STATE_idle_doorOpen;}
		}
		case CHAIN_idle_TRANS_tr5_FROM_doorClosed_TO_tp1_BY_checkHelperPort:
		{
			action_idle_TRANS_tr5_FROM_doorClosed_TO_tp1_BY_checkHelperPort(self, ifitem);
			if (isRequestBelow()) {
			return STATE_goingDown_running;}
			else if (isRequestAbove()) {
			entry_goingUp(self);
			return STATE_goingUp_running;}
			else {
			action_TRANS_tr7_FROM_cp0_TO_idle_tp0(self, ifitem);
			entry_idle(self);
			action_idle_TRANS_tr0_FROM_tp0_TO_doorOpen(self, ifitem);
			return STATE_idle_doorOpen;}
		}
		case CHAIN_idle_TRANS_INITIAL_TO__doorClosed:
		{
			return STATE_idle_doorClosed;
		}
		case CHAIN_idle_TRANS_tr8_FROM_doorOpen_TO_doorOpen_BY_checkHelperPort_tr8:
		{
			action_idle_TRANS_tr8_FROM_doorOpen_TO_doorOpen_BY_checkHelperPort_tr8(self, ifitem);
			return STATE_idle_doorOpen;
		}
		case CHAIN_idle_TRANS_tr10_FROM_doorClosed_TO_doorOpen_BY_doorRequestCabinePort:
		{
			action_idle_TRANS_tr10_FROM_doorClosed_TO_doorOpen_BY_doorRequestCabinePort(self, ifitem);
			return STATE_idle_doorOpen;
		}
		case CHAIN_idle_TRANS_tr11_FROM_doorOpen_TO_doorOpen_BY_doorRequestCabinePort_tr11:
		{
			action_idle_TRANS_tr11_FROM_doorOpen_TO_doorOpen_BY_doorRequestCabinePort_tr11(self, ifitem);
			return STATE_idle_doorOpen;
		}
		case CHAIN_idle_TRANS_tr12_FROM_tp4_TO_tp4_BY_requestIdlecontrolPort_tr12:
		{
			action_idle_TRANS_tr12_FROM_tp4_TO_tp4_BY_requestIdlecontrolPort_tr12(self, ifitem);
			return STATE_idle + STATE_MAX;
		}
		case CHAIN_idle_TRANS_tr9_FROM_doorClosed_TO_tp1_BY_timeouttimer:
		{
			action_idle_TRANS_tr9_FROM_doorClosed_TO_tp1_BY_timeouttimer(self, ifitem);
			if (isRequestBelow()) {
			return STATE_goingDown_running;}
			else if (isRequestAbove()) {
			entry_goingUp(self);
			return STATE_goingUp_running;}
			else {
			action_TRANS_tr7_FROM_cp0_TO_idle_tp0(self, ifitem);
			entry_idle(self);
			action_idle_TRANS_tr0_FROM_tp0_TO_doorOpen(self, ifitem);
			return STATE_idle_doorOpen;}
		}
		case CHAIN_goingDown_TRANS_tr1_FROM_running_TO_cp0_BY_floorReachedMotorPort:
		{
			uint8 data = *((uint8*) generic_data__et);
			action_goingDown_TRANS_tr1_FROM_running_TO_cp0_BY_floorReachedMotorPort(self, ifitem, data);
			if (downRequests[floor] || !isRequestBelow()) {
			action_goingDown_TRANS_tr3_FROM_cp0_TO_halted_COND_tr3(self, ifitem, data);
			return STATE_goingDown_halted;}
			else {
			return STATE_goingDown_running;}
		}
		case CHAIN_goingDown_TRANS_tr14_FROM_halted_TO_cp4_BY_doneCabinePort:
		{
			action_goingDown_TRANS_tr14_FROM_halted_TO_cp4_BY_doneCabinePort(self, ifitem);
			if (doorStatus>1) {
			if (idleRequest) {
			entry_idle(self);
			return STATE_idle_doorClosed;}
			else {
			if (isRequestBelow()) {
			return STATE_goingDown_running;}
			else {
			if (isRequestAbove()) {
			entry_goingUp(self);
			return STATE_goingUp_running;}
			else {
			entry_idle(self);
			return STATE_idle_doorClosed;}
			}
			}
			}
			else {
			return STATE_goingDown_halted;}
		}
		case CHAIN_goingDown_TRANS_tr15_FROM_halted_TO_cp4_BY_doneFloorPort:
		{
			action_goingDown_TRANS_tr15_FROM_halted_TO_cp4_BY_doneFloorPort(self, ifitem);
			if (doorStatus>1) {
			if (idleRequest) {
			entry_idle(self);
			return STATE_idle_doorClosed;}
			else {
			if (isRequestBelow()) {
			return STATE_goingDown_running;}
			else {
			if (isRequestAbove()) {
			entry_goingUp(self);
			return STATE_goingUp_running;}
			else {
			entry_idle(self);
			return STATE_idle_doorClosed;}
			}
			}
			}
			else {
			return STATE_goingDown_halted;}
		}
		case CHAIN_goingDown_TRANS_tr5_FROM_halted_TO_halted_BY_checkHelperPort_tr5:
		{
			action_goingDown_TRANS_tr5_FROM_halted_TO_halted_BY_checkHelperPort_tr5(self, ifitem);
			return STATE_goingDown_halted;
		}
		case CHAIN_goingDown_TRANS_tr6_FROM_halted_TO_halted_BY_doorRequestCabinePort_tr6:
		{
			action_goingDown_TRANS_tr6_FROM_halted_TO_halted_BY_doorRequestCabinePort_tr6(self, ifitem);
			return STATE_goingDown_halted;
		}
		case CHAIN_goingUp_TRANS_tr1_FROM_running_TO_cp0_BY_floorReachedMotorPort:
		{
			uint8 data = *((uint8*) generic_data__et);
			action_goingUp_TRANS_tr1_FROM_running_TO_cp0_BY_floorReachedMotorPort(self, ifitem, data);
			if (upRequests[floor] || !isRequestAbove()) {
			action_goingUp_TRANS_tr3_FROM_cp0_TO_halted_COND_tr3(self, ifitem, data);
			return STATE_goingUp_halted;}
			else {
			return STATE_goingUp_running;}
		}
		case CHAIN_goingUp_TRANS_tr5_FROM_halted_TO_cp1_BY_doneCabinePort:
		{
			action_goingUp_TRANS_tr5_FROM_halted_TO_cp1_BY_doneCabinePort(self, ifitem);
			if (doorStatus>1) {
			if (idleRequest) {
			entry_idle(self);
			return STATE_idle_doorClosed;}
			else {
			if (isRequestAbove()) {
			return STATE_goingUp_running;}
			else {
			if (isRequestBelow()) {
			return STATE_goingDown_running;}
			else {
			entry_idle(self);
			return STATE_idle_doorClosed;}
			}
			}
			}
			else {
			return STATE_goingUp_halted;}
		}
		case CHAIN_goingUp_TRANS_tr6_FROM_halted_TO_cp1_BY_doneFloorPort:
		{
			action_goingUp_TRANS_tr6_FROM_halted_TO_cp1_BY_doneFloorPort(self, ifitem);
			if (doorStatus>1) {
			if (idleRequest) {
			entry_idle(self);
			return STATE_idle_doorClosed;}
			else {
			if (isRequestAbove()) {
			return STATE_goingUp_running;}
			else {
			if (isRequestBelow()) {
			return STATE_goingDown_running;}
			else {
			entry_idle(self);
			return STATE_idle_doorClosed;}
			}
			}
			}
			else {
			return STATE_goingUp_halted;}
		}
		case CHAIN_goingUp_TRANS_tr4_FROM_halted_TO_halted_BY_checkHelperPort_tr4:
		{
			action_goingUp_TRANS_tr4_FROM_halted_TO_halted_BY_checkHelperPort_tr4(self, ifitem);
			return STATE_goingUp_halted;
		}
		case CHAIN_goingUp_TRANS_tr14_FROM_halted_TO_halted_BY_doorRequestCabinePort_tr14:
		{
			action_goingUp_TRANS_tr14_FROM_halted_TO_halted_BY_doorRequestCabinePort_tr14(self, ifitem);
			return STATE_goingUp_halted;
		}
			default:
				/* should not occur */
				break;
	}
	return NO_STATE;
}

/**
 * calls entry codes while entering a state's history. The ID of the final leaf state is returned
 * @param state__et - the state which is entered
 * @param handler__et - entry code is executed if not handler
 * @return - the ID of the final leaf state
 */
static etInt16 enterHistory(AElevatorMainController* self, etInt16 state__et, boolean handler__et) {
	boolean skip_entry__et = ET_FALSE;
	if (state__et >= STATE_MAX) {
		state__et = (etInt16) (state__et - STATE_MAX);
		skip_entry__et = ET_TRUE;
	}
	while (ET_TRUE) {
		switch (state__et) {
			case STATE_idle:
				if (!(skip_entry__et || handler__et)) entry_idle(self);
				/* state has a sub graph */
				/* with init transition */
				if (self->history[STATE_idle]==NO_STATE) {
					state__et = executeTransitionChain(self, CHAIN_idle_TRANS_INITIAL_TO__doorClosed, NULL, NULL);
				}
				else {
					state__et = self->history[STATE_idle];
				}
				break;
			case STATE_idle_doorOpen:
				if (!(skip_entry__et || handler__et)) entry_idle_doorOpen(self);
				/* in leaf state: return state id */
				return STATE_idle_doorOpen;
			case STATE_idle_doorClosed:
				if (!(skip_entry__et || handler__et)) entry_idle_doorClosed(self);
				/* in leaf state: return state id */
				return STATE_idle_doorClosed;
			case STATE_goingDown:
				/* state has a sub graph */
				/* without init transition */
				state__et = self->history[STATE_goingDown];
				break;
			case STATE_goingDown_running:
				if (!(skip_entry__et || handler__et)) entry_goingDown_running(self);
				/* in leaf state: return state id */
				return STATE_goingDown_running;
			case STATE_goingDown_halted:
				if (!(skip_entry__et || handler__et)) entry_goingDown_halted(self);
				/* in leaf state: return state id */
				return STATE_goingDown_halted;
			case STATE_goingUp:
				if (!(skip_entry__et || handler__et)) entry_goingUp(self);
				/* state has a sub graph */
				/* without init transition */
				state__et = self->history[STATE_goingUp];
				break;
			case STATE_goingUp_running:
				if (!(skip_entry__et || handler__et)) entry_goingUp_running(self);
				/* in leaf state: return state id */
				return STATE_goingUp_running;
			case STATE_goingUp_halted:
				if (!(skip_entry__et || handler__et)) entry_goingUp_halted(self);
				/* in leaf state: return state id */
				return STATE_goingUp_halted;
			case STATE_TOP:
				state__et = self->history[STATE_TOP];
				break;
			default:
				/* should not occur */
				break;
		}
		skip_entry__et = ET_FALSE;
	}
	/* return NO_STATE; // required by CDT but detected as unreachable by JDT because of while (true) */
}

static void AElevatorMainController_executeInitTransition(AElevatorMainController* self) {
	int chain__et = CHAIN_TRANS_INITIAL_TO__idle;
	etInt16 next__et = executeTransitionChain(self, chain__et, NULL, NULL);
	next__et = enterHistory(self, next__et, ET_FALSE);
	setState(self, next__et);
}

/* receiveEvent contains the main implementation of the FSM */
static void AElevatorMainController_receiveEvent(AElevatorMainController* self, InterfaceItemBase* ifitem, int evt, void* generic_data__et) {
	int trigger__et = ifitem->localId + EVT_SHIFT*evt;
	int chain__et = NOT_CAUGHT;
	etInt16 catching_state__et = NO_STATE;
	boolean is_handler__et = ET_FALSE;
	((void)trigger__et);	/* avoids unused warning */
	
	if (!handleSystemEvent(ifitem, evt, generic_data__et)) {
		switch (getState(self)) {
			case STATE_idle_doorOpen:
				switch(trigger__et) {
						case TRIG_CabinePort__done:
							{
								chain__et = CHAIN_idle_TRANS_tr1_FROM_doorOpen_TO_cp0_BY_doneCabinePort;
								catching_state__et = STATE_idle;
							}
						break;
						case TRIG_FloorPort__done:
							{
								chain__et = CHAIN_idle_TRANS_tr2_FROM_doorOpen_TO_cp0_BY_doneFloorPort;
								catching_state__et = STATE_idle;
							}
						break;
						case TRIG_HelperPort__check:
							{
								chain__et = CHAIN_idle_TRANS_tr8_FROM_doorOpen_TO_doorOpen_BY_checkHelperPort_tr8;
								catching_state__et = STATE_idle;
							}
						break;
						case TRIG_CabinePort__doorRequest:
							{
								chain__et = CHAIN_idle_TRANS_tr11_FROM_doorOpen_TO_doorOpen_BY_doorRequestCabinePort_tr11;
								catching_state__et = STATE_idle;
							}
						break;
						case TRIG_controlPort__requestIdle:
							{
								chain__et = CHAIN_idle_TRANS_tr12_FROM_tp4_TO_tp4_BY_requestIdlecontrolPort_tr12;
								catching_state__et = STATE_idle;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_MotorPort__floorReached:
							{
								chain__et = CHAIN_TRANS_tr0_FROM_tp0_TO_tp0_BY_floorReachedMotorPort_tr0;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_FloorPort__requestUp:
							{
								chain__et = CHAIN_TRANS_tr1_FROM_tp1_TO_tp1_BY_requestUpFloorPort_tr1;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_FloorPort__requestDown:
							{
								chain__et = CHAIN_TRANS_tr2_FROM_tp1_TO_tp1_BY_requestDownFloorPort_tr2;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_CabinePort__floorRequest:
							{
								chain__et = CHAIN_TRANS_tr3_FROM_tp1_TO_tp1_BY_floorRequestCabinePort_tr3;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_controlPort__getStatus:
							{
								chain__et = CHAIN_TRANS_tr16_FROM_tp3_TO_tp3_BY_getStatuscontrolPort_tr16;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_controlPort__requestFloor:
							{
								chain__et = CHAIN_TRANS_tr17_FROM_tp3_TO_tp3_BY_requestFloorcontrolPort_tr17;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_controlPort__setIdleFloor:
							{
								chain__et = CHAIN_TRANS_tr18_FROM_tp4_TO_tp4_BY_setIdleFloorcontrolPort_tr18;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_controlPort__setIdleTime:
							{
								chain__et = CHAIN_TRANS_tr13_FROM_tp4_TO_tp4_BY_setIdleTimecontrolPort_tr13;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						default:
							/* should not occur */
							break;
				}
				break;
			case STATE_idle_doorClosed:
				switch(trigger__et) {
						case TRIG_HelperPort__check:
							{
								chain__et = CHAIN_idle_TRANS_tr5_FROM_doorClosed_TO_tp1_BY_checkHelperPort;
								catching_state__et = STATE_idle;
							}
						break;
						case TRIG_CabinePort__doorRequest:
							{
								chain__et = CHAIN_idle_TRANS_tr10_FROM_doorClosed_TO_doorOpen_BY_doorRequestCabinePort;
								catching_state__et = STATE_idle;
							}
						break;
						case TRIG_timer__timeout:
							{
								chain__et = CHAIN_idle_TRANS_tr9_FROM_doorClosed_TO_tp1_BY_timeouttimer;
								catching_state__et = STATE_idle;
							}
						break;
						case TRIG_controlPort__requestIdle:
							{
								chain__et = CHAIN_idle_TRANS_tr12_FROM_tp4_TO_tp4_BY_requestIdlecontrolPort_tr12;
								catching_state__et = STATE_idle;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_MotorPort__floorReached:
							{
								chain__et = CHAIN_TRANS_tr0_FROM_tp0_TO_tp0_BY_floorReachedMotorPort_tr0;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_FloorPort__requestUp:
							{
								chain__et = CHAIN_TRANS_tr1_FROM_tp1_TO_tp1_BY_requestUpFloorPort_tr1;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_FloorPort__requestDown:
							{
								chain__et = CHAIN_TRANS_tr2_FROM_tp1_TO_tp1_BY_requestDownFloorPort_tr2;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_CabinePort__floorRequest:
							{
								chain__et = CHAIN_TRANS_tr3_FROM_tp1_TO_tp1_BY_floorRequestCabinePort_tr3;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_controlPort__getStatus:
							{
								chain__et = CHAIN_TRANS_tr16_FROM_tp3_TO_tp3_BY_getStatuscontrolPort_tr16;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_controlPort__requestFloor:
							{
								chain__et = CHAIN_TRANS_tr17_FROM_tp3_TO_tp3_BY_requestFloorcontrolPort_tr17;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_controlPort__setIdleFloor:
							{
								chain__et = CHAIN_TRANS_tr18_FROM_tp4_TO_tp4_BY_setIdleFloorcontrolPort_tr18;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_controlPort__setIdleTime:
							{
								chain__et = CHAIN_TRANS_tr13_FROM_tp4_TO_tp4_BY_setIdleTimecontrolPort_tr13;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						default:
							/* should not occur */
							break;
				}
				break;
			case STATE_goingDown_running:
				switch(trigger__et) {
						case TRIG_MotorPort__floorReached:
							{
								chain__et = CHAIN_goingDown_TRANS_tr1_FROM_running_TO_cp0_BY_floorReachedMotorPort;
								catching_state__et = STATE_goingDown;
							}
						break;
						case TRIG_FloorPort__requestUp:
							{
								chain__et = CHAIN_TRANS_tr1_FROM_tp1_TO_tp1_BY_requestUpFloorPort_tr1;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_FloorPort__requestDown:
							{
								chain__et = CHAIN_TRANS_tr2_FROM_tp1_TO_tp1_BY_requestDownFloorPort_tr2;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_CabinePort__floorRequest:
							{
								chain__et = CHAIN_TRANS_tr3_FROM_tp1_TO_tp1_BY_floorRequestCabinePort_tr3;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_HelperPort__check:
							{
								chain__et = CHAIN_TRANS_tr10_FROM_tp2_TO_tp2_BY_checkHelperPort_tr10;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_controlPort__requestIdle:
							{
								chain__et = CHAIN_TRANS_tr15_FROM_tp3_TO_tp3_BY_requestIdlecontrolPort_tr15;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_controlPort__getStatus:
							{
								chain__et = CHAIN_TRANS_tr16_FROM_tp3_TO_tp3_BY_getStatuscontrolPort_tr16;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_controlPort__requestFloor:
							{
								chain__et = CHAIN_TRANS_tr17_FROM_tp3_TO_tp3_BY_requestFloorcontrolPort_tr17;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_controlPort__setIdleFloor:
							{
								chain__et = CHAIN_TRANS_tr18_FROM_tp4_TO_tp4_BY_setIdleFloorcontrolPort_tr18;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_controlPort__setIdleTime:
							{
								chain__et = CHAIN_TRANS_tr13_FROM_tp4_TO_tp4_BY_setIdleTimecontrolPort_tr13;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						default:
							/* should not occur */
							break;
				}
				break;
			case STATE_goingDown_halted:
				switch(trigger__et) {
						case TRIG_CabinePort__done:
							{
								chain__et = CHAIN_goingDown_TRANS_tr14_FROM_halted_TO_cp4_BY_doneCabinePort;
								catching_state__et = STATE_goingDown;
							}
						break;
						case TRIG_FloorPort__done:
							{
								chain__et = CHAIN_goingDown_TRANS_tr15_FROM_halted_TO_cp4_BY_doneFloorPort;
								catching_state__et = STATE_goingDown;
							}
						break;
						case TRIG_HelperPort__check:
							{
								chain__et = CHAIN_goingDown_TRANS_tr5_FROM_halted_TO_halted_BY_checkHelperPort_tr5;
								catching_state__et = STATE_goingDown;
							}
						break;
						case TRIG_CabinePort__doorRequest:
							{
								chain__et = CHAIN_goingDown_TRANS_tr6_FROM_halted_TO_halted_BY_doorRequestCabinePort_tr6;
								catching_state__et = STATE_goingDown;
							}
						break;
						case TRIG_MotorPort__floorReached:
							{
								chain__et = CHAIN_TRANS_tr0_FROM_tp0_TO_tp0_BY_floorReachedMotorPort_tr0;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_FloorPort__requestUp:
							{
								chain__et = CHAIN_TRANS_tr1_FROM_tp1_TO_tp1_BY_requestUpFloorPort_tr1;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_FloorPort__requestDown:
							{
								chain__et = CHAIN_TRANS_tr2_FROM_tp1_TO_tp1_BY_requestDownFloorPort_tr2;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_CabinePort__floorRequest:
							{
								chain__et = CHAIN_TRANS_tr3_FROM_tp1_TO_tp1_BY_floorRequestCabinePort_tr3;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_controlPort__requestIdle:
							{
								chain__et = CHAIN_TRANS_tr15_FROM_tp3_TO_tp3_BY_requestIdlecontrolPort_tr15;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_controlPort__getStatus:
							{
								chain__et = CHAIN_TRANS_tr16_FROM_tp3_TO_tp3_BY_getStatuscontrolPort_tr16;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_controlPort__requestFloor:
							{
								chain__et = CHAIN_TRANS_tr17_FROM_tp3_TO_tp3_BY_requestFloorcontrolPort_tr17;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_controlPort__setIdleFloor:
							{
								chain__et = CHAIN_TRANS_tr18_FROM_tp4_TO_tp4_BY_setIdleFloorcontrolPort_tr18;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_controlPort__setIdleTime:
							{
								chain__et = CHAIN_TRANS_tr13_FROM_tp4_TO_tp4_BY_setIdleTimecontrolPort_tr13;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						default:
							/* should not occur */
							break;
				}
				break;
			case STATE_goingUp_running:
				switch(trigger__et) {
						case TRIG_MotorPort__floorReached:
							{
								chain__et = CHAIN_goingUp_TRANS_tr1_FROM_running_TO_cp0_BY_floorReachedMotorPort;
								catching_state__et = STATE_goingUp;
							}
						break;
						case TRIG_FloorPort__requestUp:
							{
								chain__et = CHAIN_TRANS_tr1_FROM_tp1_TO_tp1_BY_requestUpFloorPort_tr1;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_FloorPort__requestDown:
							{
								chain__et = CHAIN_TRANS_tr2_FROM_tp1_TO_tp1_BY_requestDownFloorPort_tr2;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_CabinePort__floorRequest:
							{
								chain__et = CHAIN_TRANS_tr3_FROM_tp1_TO_tp1_BY_floorRequestCabinePort_tr3;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_HelperPort__check:
							{
								chain__et = CHAIN_TRANS_tr10_FROM_tp2_TO_tp2_BY_checkHelperPort_tr10;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_controlPort__requestIdle:
							{
								chain__et = CHAIN_TRANS_tr15_FROM_tp3_TO_tp3_BY_requestIdlecontrolPort_tr15;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_controlPort__getStatus:
							{
								chain__et = CHAIN_TRANS_tr16_FROM_tp3_TO_tp3_BY_getStatuscontrolPort_tr16;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_controlPort__requestFloor:
							{
								chain__et = CHAIN_TRANS_tr17_FROM_tp3_TO_tp3_BY_requestFloorcontrolPort_tr17;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_controlPort__setIdleFloor:
							{
								chain__et = CHAIN_TRANS_tr18_FROM_tp4_TO_tp4_BY_setIdleFloorcontrolPort_tr18;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_controlPort__setIdleTime:
							{
								chain__et = CHAIN_TRANS_tr13_FROM_tp4_TO_tp4_BY_setIdleTimecontrolPort_tr13;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						default:
							/* should not occur */
							break;
				}
				break;
			case STATE_goingUp_halted:
				switch(trigger__et) {
						case TRIG_CabinePort__done:
							{
								chain__et = CHAIN_goingUp_TRANS_tr5_FROM_halted_TO_cp1_BY_doneCabinePort;
								catching_state__et = STATE_goingUp;
							}
						break;
						case TRIG_FloorPort__done:
							{
								chain__et = CHAIN_goingUp_TRANS_tr6_FROM_halted_TO_cp1_BY_doneFloorPort;
								catching_state__et = STATE_goingUp;
							}
						break;
						case TRIG_HelperPort__check:
							{
								chain__et = CHAIN_goingUp_TRANS_tr4_FROM_halted_TO_halted_BY_checkHelperPort_tr4;
								catching_state__et = STATE_goingUp;
							}
						break;
						case TRIG_CabinePort__doorRequest:
							{
								chain__et = CHAIN_goingUp_TRANS_tr14_FROM_halted_TO_halted_BY_doorRequestCabinePort_tr14;
								catching_state__et = STATE_goingUp;
							}
						break;
						case TRIG_MotorPort__floorReached:
							{
								chain__et = CHAIN_TRANS_tr0_FROM_tp0_TO_tp0_BY_floorReachedMotorPort_tr0;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_FloorPort__requestUp:
							{
								chain__et = CHAIN_TRANS_tr1_FROM_tp1_TO_tp1_BY_requestUpFloorPort_tr1;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_FloorPort__requestDown:
							{
								chain__et = CHAIN_TRANS_tr2_FROM_tp1_TO_tp1_BY_requestDownFloorPort_tr2;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_CabinePort__floorRequest:
							{
								chain__et = CHAIN_TRANS_tr3_FROM_tp1_TO_tp1_BY_floorRequestCabinePort_tr3;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_controlPort__requestIdle:
							{
								chain__et = CHAIN_TRANS_tr15_FROM_tp3_TO_tp3_BY_requestIdlecontrolPort_tr15;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_controlPort__getStatus:
							{
								chain__et = CHAIN_TRANS_tr16_FROM_tp3_TO_tp3_BY_getStatuscontrolPort_tr16;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_controlPort__requestFloor:
							{
								chain__et = CHAIN_TRANS_tr17_FROM_tp3_TO_tp3_BY_requestFloorcontrolPort_tr17;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_controlPort__setIdleFloor:
							{
								chain__et = CHAIN_TRANS_tr18_FROM_tp4_TO_tp4_BY_setIdleFloorcontrolPort_tr18;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_controlPort__setIdleTime:
							{
								chain__et = CHAIN_TRANS_tr13_FROM_tp4_TO_tp4_BY_setIdleTimecontrolPort_tr13;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						default:
							/* should not occur */
							break;
				}
				break;
			default:
				/* should not occur */
				break;
		}
	}
	if (chain__et != NOT_CAUGHT) {
		exitTo(self, getState(self), catching_state__et, is_handler__et);
		{
			etInt16 next__et = executeTransitionChain(self, chain__et, ifitem, generic_data__et);
			next__et = enterHistory(self, next__et, is_handler__et);
			setState(self, next__et);
		}
	}
}

void AElevatorMainController_init(AElevatorMainController* self){
	ET_MSC_LOGGER_SYNC_ENTRY("AElevatorMainController", "init")
	self->state = STATE_TOP;
	{
		int i;
		for (i=0; i<AELEVATORMAINCONTROLLER_HISTORY_SIZE; ++i)
			self->history[i] = NO_STATE;
	}
	AElevatorMainController_executeInitTransition(self);
	ET_MSC_LOGGER_SYNC_EXIT
}


void AElevatorMainController_receiveMessage(void* self, const void* ifitem, const etMessage* msg){
	ET_MSC_LOGGER_SYNC_ENTRY("AElevatorMainController", "_receiveMessage")
	
	AElevatorMainController_receiveEvent(self, (etPort*)ifitem, msg->evtID, (void*)(((char*)msg)+MEM_CEIL(sizeof(etMessage))));
	
	ET_MSC_LOGGER_SYNC_EXIT
}


/*--------------------- operations ---------------------*/
void AElevatorMainController_clearFloorRequests(AElevatorMainController* self) {
	
					FloorPort_requestsClear(floor);
					CabinePort_floorRequestClear(floor);
					upRequests[floor]=0;
					downRequests[floor]=0;
}
void AElevatorMainController_clearAllRequests(AElevatorMainController* self) {
	
					uint8 i;
					for(i=0;i<5;i++){
						FloorPort_requestsClear(i);
						CabinePort_floorRequestClear(i);			
						upRequests[i]=0;
						downRequests[i]=0;
						}
}
uint8 AElevatorMainController_isRequestHere(AElevatorMainController* self) {
	
					if(upRequests[floor] || downRequests[floor]) return 1;
					return 0;	
}
uint8 AElevatorMainController_isRequestAbove(AElevatorMainController* self) {
	
					signed char i;
					if (floor == 4) return 0;
					for(i=floor+1;i<5;i++){
						if(upRequests[i] || downRequests[i]) return 1;
					}
					return 0;
}
uint8 AElevatorMainController_isRequestBelow(AElevatorMainController* self) {
	
					signed char i;
					if (floor == 0) return 0;
					for(i=floor-1;i>=0;i--){
						if(upRequests[i] || downRequests[i]) return 1;
					}
					return 0;
}

