/**
 * @author generated by eTrice
 *
 * Header File of ActorClass AFloorController
 * 
 */

#ifndef _ELEVATORFREERTOS_MODEL_AFLOORCONTROLLER_H_
#define _ELEVATORFREERTOS_MODEL_AFLOORCONTROLLER_H_

#include "etDatatypes.h"
#include "messaging/etMessage.h"

#include "ElevatorFreeRTOS_Model/PButtonControl.h"
#include "ElevatorFreeRTOS_Model/PDoorControl.h"
#include "ElevatorFreeRTOS_Model/PFloorControl.h"
#include "room/basic/service/timing/PTimer.h"

/*--------------------- begin user code ---------------------*/
#include "etPlatform.h"
/*--------------------- end user code ---------------------*/

typedef struct AFloorController AFloorController;

/* const part of ActorClass (ROM) */
typedef struct AFloorController_const {
	/* simple ports */
	const PFloorControlPort ControlPort;
	const PButtonControlConjPort UpButtonPort;
	const PButtonControlConjPort DownButtonPort;
	const PDoorControlConjPort DoorPort;
	
	/* data receive ports */

	/* saps */
	
	/* replicated ports */
	
	/* services */
} AFloorController_const;


/* constant for state machine data */
#define AFLOORCONTROLLER_HISTORY_SIZE 2

/* variable part of ActorClass (RAM) */
struct AFloorController {
	const AFloorController_const* const constData;
	
	/* data send ports */
	
	/*--------------------- attributes ---------------------*/
	uint8 floor;
	
	
	/* state machine variables */
	etInt16 state;
	etInt16 history[AFLOORCONTROLLER_HISTORY_SIZE];
};

void AFloorController_init(AFloorController* self);

void AFloorController_receiveMessage(void* self, const void* ifitem, const etMessage* msg);


/*--------------------- operations ---------------------*/


#endif /* _ELEVATORFREERTOS_MODEL_AFLOORCONTROLLER_H_ */

