/**
 * @author generated by eTrice
 *
 * Header File of ActorClass AMotorController
 * 
 */

#ifndef _ELEVATORFREERTOS_MODEL_AMOTORCONTROLLER_H_
#define _ELEVATORFREERTOS_MODEL_AMOTORCONTROLLER_H_

#include "etDatatypes.h"
#include "messaging/etMessage.h"

#include "ElevatorFreeRTOS_Model/PMotorControl.h"
#include "room/basic/service/timing/PTimer.h"

/*--------------------- begin user code ---------------------*/
#include "etPlatform.h"
/*--------------------- end user code ---------------------*/

typedef struct AMotorController AMotorController;

/* const part of ActorClass (ROM) */
typedef struct AMotorController_const {
	/* simple ports */
	const PMotorControlPort ControlPort;
	
	/* data receive ports */

	/* saps */
	const PTimerConjPort timer;
	
	/* replicated ports */
	
	/* services */
} AMotorController_const;


/* constant for state machine data */
#define AMOTORCONTROLLER_HISTORY_SIZE 2

/* variable part of ActorClass (RAM) */
struct AMotorController {
	const AMotorController_const* const constData;
	
	/* data send ports */
	
	/*--------------------- attributes ---------------------*/
	
	
	/* state machine variables */
	etInt16 state;
	etInt16 history[AMOTORCONTROLLER_HISTORY_SIZE];
};

void AMotorController_init(AMotorController* self);

void AMotorController_receiveMessage(void* self, const void* ifitem, const etMessage* msg);


/*--------------------- operations ---------------------*/


#endif /* _ELEVATORFREERTOS_MODEL_AMOTORCONTROLLER_H_ */

