/**
 * @author generated by eTrice
 *
 * Source File of ActorClass AStartGenerator
 * 
 */

#include "AStartGenerator.h"

#include "modelbase/etActor.h"
#include "debugging/etLogger.h"
#include "debugging/etMSCLogger.h"
#include "etUnit/etUnit.h"
#include "base/etMemory.h"

#include "ElevatorFreeRTOS_Model/PStartGenerator.h"

#include "AStartGenerator_Utils.h"


/* interface item IDs */
enum interface_items {
	IFITEM_ControlPort = 1
};

/* state IDs */
enum state_ids {
	NO_STATE = 0,
	STATE_TOP = 1,
	STATE_running = 2,
	STATE_MAX = 3
};

/* transition chains */
enum chain_ids {
	CHAIN_TRANS_INITIAL_TO__running = 1,
	CHAIN_TRANS_tr0_FROM_running_TO_running_BY_requestCheckControlPort_tr0 = 2,
	CHAIN_TRANS_tr1_FROM_running_TO_running_BY_requestCheckDoorStatusControlPort_tr1 = 3
};

/* triggers */
enum triggers {
	POLLING = 0,
	TRIG_ControlPort__requestCheck = IFITEM_ControlPort + EVT_SHIFT*PStartGenerator_IN_requestCheck,
	TRIG_ControlPort__requestCheckDoorStatus = IFITEM_ControlPort + EVT_SHIFT*PStartGenerator_IN_requestCheckDoorStatus
};


static void setState(AStartGenerator* self, etInt16 new_state) {
	self->state = new_state;
}

static etInt16 getState(AStartGenerator* self) {
	return self->state;
}

/* Entry and Exit Codes */

/* Action Codes */
static void action_TRANS_tr0_FROM_running_TO_running_BY_requestCheckControlPort_tr0(AStartGenerator* self, const InterfaceItemBase* ifitem) {
	ControlPort_check();
}
static void action_TRANS_tr1_FROM_running_TO_running_BY_requestCheckDoorStatusControlPort_tr1(AStartGenerator* self, const InterfaceItemBase* ifitem) {
	ControlPort_checkDoorStatus();
}

/**
 * calls exit codes while exiting from the current state to one of its
 * parent states while remembering the history
 * @param current__et - the current state
 * @param to - the final parent state
 */
static void exitTo(AStartGenerator* self, etInt16 current__et, etInt16 to) {
	while (current__et!=to) {
		switch (current__et) {
			case STATE_running:
				self->history[STATE_TOP] = STATE_running;
				current__et = STATE_TOP;
				break;
			default:
				/* should not occur */
				break;
		}
	}
}

/**
 * calls action, entry and exit codes along a transition chain. The generic data are cast to typed data
 * matching the trigger of this chain. The ID of the final state is returned
 * @param chain__et - the chain ID
 * @param generic_data__et - the generic data pointer
 * @return the +/- ID of the final state either with a positive sign, that indicates to execute the state's entry code, or a negative sign vice versa
 */
static etInt16 executeTransitionChain(AStartGenerator* self, int chain__et, const InterfaceItemBase* ifitem, void* generic_data__et) {
	switch (chain__et) {
		case CHAIN_TRANS_INITIAL_TO__running:
		{
			return STATE_running;
		}
		case CHAIN_TRANS_tr0_FROM_running_TO_running_BY_requestCheckControlPort_tr0:
		{
			action_TRANS_tr0_FROM_running_TO_running_BY_requestCheckControlPort_tr0(self, ifitem);
			return STATE_running;
		}
		case CHAIN_TRANS_tr1_FROM_running_TO_running_BY_requestCheckDoorStatusControlPort_tr1:
		{
			action_TRANS_tr1_FROM_running_TO_running_BY_requestCheckDoorStatusControlPort_tr1(self, ifitem);
			return STATE_running;
		}
			default:
				/* should not occur */
				break;
	}
	return NO_STATE;
}

/**
 * calls entry codes while entering a state's history. The ID of the final leaf state is returned
 * @param state__et - the state which is entered
 * @return - the ID of the final leaf state
 */
static etInt16 enterHistory(AStartGenerator* self, etInt16 state__et) {
	boolean skip_entry__et = ET_FALSE;
	if (state__et >= STATE_MAX) {
		state__et = (etInt16) (state__et - STATE_MAX);
		skip_entry__et = ET_TRUE;
	}
	while (ET_TRUE) {
		switch (state__et) {
			case STATE_running:
				/* in leaf state: return state id */
				return STATE_running;
			case STATE_TOP:
				state__et = self->history[STATE_TOP];
				break;
			default:
				/* should not occur */
				break;
		}
		skip_entry__et = ET_FALSE;
	}
	/* return NO_STATE; // required by CDT but detected as unreachable by JDT because of while (true) */
}

static void AStartGenerator_executeInitTransition(AStartGenerator* self) {
	int chain__et = CHAIN_TRANS_INITIAL_TO__running;
	etInt16 next__et = executeTransitionChain(self, chain__et, NULL, NULL);
	next__et = enterHistory(self, next__et);
	setState(self, next__et);
}

/* receiveEvent contains the main implementation of the FSM */
static void AStartGenerator_receiveEvent(AStartGenerator* self, InterfaceItemBase* ifitem, int evt, void* generic_data__et) {
	int trigger__et = ifitem->localId + EVT_SHIFT*evt;
	int chain__et = NOT_CAUGHT;
	etInt16 catching_state__et = NO_STATE;
	((void)trigger__et);	/* avoids unused warning */
	
	if (!handleSystemEvent(ifitem, evt, generic_data__et)) {
		switch (getState(self)) {
			case STATE_running:
				switch(trigger__et) {
						case TRIG_ControlPort__requestCheck:
							{
								chain__et = CHAIN_TRANS_tr0_FROM_running_TO_running_BY_requestCheckControlPort_tr0;
								catching_state__et = STATE_TOP;
							}
						break;
						case TRIG_ControlPort__requestCheckDoorStatus:
							{
								chain__et = CHAIN_TRANS_tr1_FROM_running_TO_running_BY_requestCheckDoorStatusControlPort_tr1;
								catching_state__et = STATE_TOP;
							}
						break;
						default:
							/* should not occur */
							break;
				}
				break;
			default:
				/* should not occur */
				break;
		}
	}
	if (chain__et != NOT_CAUGHT) {
		exitTo(self, getState(self), catching_state__et);
		{
			etInt16 next__et = executeTransitionChain(self, chain__et, ifitem, generic_data__et);
			next__et = enterHistory(self, next__et);
			setState(self, next__et);
		}
	}
}

void AStartGenerator_init(AStartGenerator* self){
	ET_MSC_LOGGER_SYNC_ENTRY("AStartGenerator", "init")
	self->state = STATE_TOP;
	{
		int i;
		for (i=0; i<ASTARTGENERATOR_HISTORY_SIZE; ++i)
			self->history[i] = NO_STATE;
	}
	AStartGenerator_executeInitTransition(self);
	ET_MSC_LOGGER_SYNC_EXIT
}


void AStartGenerator_receiveMessage(void* self, const void* ifitem, const etMessage* msg){
	ET_MSC_LOGGER_SYNC_ENTRY("AStartGenerator", "_receiveMessage")
	
	AStartGenerator_receiveEvent(self, (etPort*)ifitem, msg->evtID, (void*)(((char*)msg)+MEM_CEIL(sizeof(etMessage))));
	
	ET_MSC_LOGGER_SYNC_EXIT
}


/*--------------------- operations ---------------------*/

