/**
 * @author generated by eTrice
 *
 * Instance File of Node msp430FreeRTOS with SubSystem elevator_subSysRef
 * - instantiation of all actor instances and port instances
 * - configuration of data and connection of ports
 */

#include "messaging/etMessageService.h"

/* include all referenced ActorClasses */
#include "ElevatorFreeRTOS_Model/AStartGenerator.h"
#include "ElevatorFreeRTOS_Model/AButtonControllerRelMsg.h"
#include "ElevatorFreeRTOS_Model/ElevatorTop.h"
#include "room/basic/service/timing/ATimingService.h"
#include "ElevatorFreeRTOS_Model/AElevatorMainController.h"
#include "ElevatorFreeRTOS_Model/ADoorController.h"
#include "ElevatorFreeRTOS_Model/AFloorController.h"
#include "ElevatorFreeRTOS_Model/AMotorController.h"
#include "ElevatorFreeRTOS_Model/AButtonController.h"
#include "ElevatorFreeRTOS_Model/Test.h"
#include "ElevatorFreeRTOS_Model/ACabineControllerWithIndication.h"

/* include all referenced ProtcolClasses */

/* instantiation of message services and message buffers */
/* PhysicalThreadLowPrio */
#define PHYSICALTHREADLOWPRIO_POOL_SIZE		100
#define PHYSICALTHREADLOWPRIO_BLOCK_SIZE	32
static uint8 msgBuffer_PhysicalThreadLowPrio[PHYSICALTHREADLOWPRIO_POOL_SIZE * PHYSICALTHREADLOWPRIO_BLOCK_SIZE]; 
static etMessageService msgService_PhysicalThreadLowPrio;

/* declarations of all ActorClass instances (const and variable structs) */

/* forward declaration of variable actor structs */
static ElevatorTop _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator;
static AFloorController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_0;
static ADoorController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_0_door;
static AButtonController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_0_buttons_0;
static AButtonController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_0_buttons_1;
static AFloorController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_1;
static ADoorController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_1_door;
static AButtonController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_1_buttons_0;
static AButtonController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_1_buttons_1;
static AFloorController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_2;
static ADoorController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_2_door;
static AButtonController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_2_buttons_0;
static AButtonController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_2_buttons_1;
static AFloorController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_3;
static ADoorController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_3_door;
static AButtonController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_3_buttons_0;
static AButtonController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_3_buttons_1;
static AFloorController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_4;
static ADoorController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_4_door;
static AButtonController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_4_buttons_0;
static AButtonController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_4_buttons_1;
static AMotorController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_motor;
static ACabineControllerWithIndication _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine;
static ADoorController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_door;
static AButtonController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_buttons_0;
static AButtonController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_buttons_1;
static AButtonController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_buttons_2;
static AButtonController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_buttons_3;
static AButtonController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_buttons_4;
static AButtonControllerRelMsg _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_doorButton;
static AElevatorMainController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_top;
static AStartGenerator _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_top_helper;
static Test _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_ref0;
static ATimingService _ElevatorFreeRTOS_LogSys_elevator_subSysRef_timingService;

/* forward declaration of variable port structs */
/* nothing to do */
static PTimerConjPort_var _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_0_door_timer_var={
	0		/* status */
							};
static PTimerConjPort_var _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_0_buttons_0_timer_var={
	0		/* status */
							};
static PTimerConjPort_var _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_0_buttons_1_timer_var={
	0		/* status */
							};
static PTimerConjPort_var _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_1_door_timer_var={
	0		/* status */
							};
static PTimerConjPort_var _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_1_buttons_0_timer_var={
	0		/* status */
							};
static PTimerConjPort_var _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_1_buttons_1_timer_var={
	0		/* status */
							};
static PTimerConjPort_var _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_2_door_timer_var={
	0		/* status */
							};
static PTimerConjPort_var _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_2_buttons_0_timer_var={
	0		/* status */
							};
static PTimerConjPort_var _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_2_buttons_1_timer_var={
	0		/* status */
							};
static PTimerConjPort_var _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_3_door_timer_var={
	0		/* status */
							};
static PTimerConjPort_var _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_3_buttons_0_timer_var={
	0		/* status */
							};
static PTimerConjPort_var _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_3_buttons_1_timer_var={
	0		/* status */
							};
static PTimerConjPort_var _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_4_door_timer_var={
	0		/* status */
							};
static PTimerConjPort_var _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_4_buttons_0_timer_var={
	0		/* status */
							};
static PTimerConjPort_var _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_4_buttons_1_timer_var={
	0		/* status */
							};
static PTimerConjPort_var _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_motor_timer_var={
	0		/* status */
							};
static PTimerConjPort_var _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_timer_var={
	0		/* status */
							};
static PTimerConjPort_var _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_door_timer_var={
	0		/* status */
							};
static PTimerConjPort_var _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_buttons_0_timer_var={
	0		/* status */
							};
static PTimerConjPort_var _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_buttons_1_timer_var={
	0		/* status */
							};
static PTimerConjPort_var _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_buttons_2_timer_var={
	0		/* status */
							};
static PTimerConjPort_var _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_buttons_3_timer_var={
	0		/* status */
							};
static PTimerConjPort_var _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_buttons_4_timer_var={
	0		/* status */
							};
static PTimerConjPort_var _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_doorButton_timer_var={
	0		/* status */
							};
static PTimerConjPort_var _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_top_timer_var={
	0		/* status */
							};
static PTimerConjPort_var _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_ref0_timer_var={
	0		/* status */
							};


/* instance _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator */
/* no ports/saps/services - nothing to initialize statically */

/* instance _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_0 */
static const AFloorController_const _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_0_const = {
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	{NULL, &msgService_PhysicalThreadLowPrio, 109+BASE_ADDRESS, 4} /* Port ControlPort */
	,{NULL, &msgService_PhysicalThreadLowPrio, 14+BASE_ADDRESS, 1} /* Port UpButtonPort */
	,{NULL, &msgService_PhysicalThreadLowPrio, 11+BASE_ADDRESS, 2} /* Port DownButtonPort */
	,{NULL, &msgService_PhysicalThreadLowPrio, 8+BASE_ADDRESS, 3} /* Port DoorPort */
	
	/* data receive ports */
	
	/* saps */
	
	/* replicated ports */
	
	/* services */
};
static AFloorController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_0 = {
	&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_0_const,
	
	/* data send ports */
	
	/* attributes */
	0		/* floor */
	
	/* state and history are initialized in init function */
};

/* instance _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_0_door */
static const ADoorController_const _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_0_door_const = {
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	{NULL, &msgService_PhysicalThreadLowPrio, 6+BASE_ADDRESS, 1} /* Port ControlPort */
	
	/* data receive ports */
	
	/* saps */
	,{&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_0_door_timer_var, &msgService_PhysicalThreadLowPrio, 122+BASE_ADDRESS, 2} /* Port timer */
	
	/* replicated ports */
	
	/* services */
};
static ADoorController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_0_door = {
	&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_0_door_const,
	
	/* data send ports */
	
	/* attributes */
	0		/* id */,
	0		/* counter */
	
	/* state and history are initialized in init function */
};

/* instance _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_0_buttons_0 */
static const AButtonController_const _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_0_buttons_0_const = {
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	{NULL, &msgService_PhysicalThreadLowPrio, 5+BASE_ADDRESS, 1} /* Port ControlPort */
	
	/* data receive ports */
	
	/* saps */
	,{&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_0_buttons_0_timer_var, &msgService_PhysicalThreadLowPrio, 123+BASE_ADDRESS, 2} /* Port timer */
	
	/* replicated ports */
	
	/* services */
};
static AButtonController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_0_buttons_0 = {
	&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_0_buttons_0_const,
	
	/* data send ports */
	
	/* attributes */
	0		/* buttonId */,
	0		/* ledId */,
	0		/* floor */
	
	/* state and history are initialized in init function */
};

/* instance _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_0_buttons_1 */
static const AButtonController_const _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_0_buttons_1_const = {
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	{NULL, &msgService_PhysicalThreadLowPrio, 4+BASE_ADDRESS, 1} /* Port ControlPort */
	
	/* data receive ports */
	
	/* saps */
	,{&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_0_buttons_1_timer_var, &msgService_PhysicalThreadLowPrio, 124+BASE_ADDRESS, 2} /* Port timer */
	
	/* replicated ports */
	
	/* services */
};
static AButtonController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_0_buttons_1 = {
	&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_0_buttons_1_const,
	
	/* data send ports */
	
	/* attributes */
	0		/* buttonId */,
	0		/* ledId */,
	0		/* floor */
	
	/* state and history are initialized in init function */
};

/* instance _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_1 */
static const AFloorController_const _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_1_const = {
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	{NULL, &msgService_PhysicalThreadLowPrio, 110+BASE_ADDRESS, 4} /* Port ControlPort */
	,{NULL, &msgService_PhysicalThreadLowPrio, 28+BASE_ADDRESS, 1} /* Port UpButtonPort */
	,{NULL, &msgService_PhysicalThreadLowPrio, 25+BASE_ADDRESS, 2} /* Port DownButtonPort */
	,{NULL, &msgService_PhysicalThreadLowPrio, 22+BASE_ADDRESS, 3} /* Port DoorPort */
	
	/* data receive ports */
	
	/* saps */
	
	/* replicated ports */
	
	/* services */
};
static AFloorController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_1 = {
	&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_1_const,
	
	/* data send ports */
	
	/* attributes */
	0		/* floor */
	
	/* state and history are initialized in init function */
};

/* instance _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_1_door */
static const ADoorController_const _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_1_door_const = {
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	{NULL, &msgService_PhysicalThreadLowPrio, 20+BASE_ADDRESS, 1} /* Port ControlPort */
	
	/* data receive ports */
	
	/* saps */
	,{&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_1_door_timer_var, &msgService_PhysicalThreadLowPrio, 125+BASE_ADDRESS, 2} /* Port timer */
	
	/* replicated ports */
	
	/* services */
};
static ADoorController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_1_door = {
	&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_1_door_const,
	
	/* data send ports */
	
	/* attributes */
	0		/* id */,
	0		/* counter */
	
	/* state and history are initialized in init function */
};

/* instance _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_1_buttons_0 */
static const AButtonController_const _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_1_buttons_0_const = {
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	{NULL, &msgService_PhysicalThreadLowPrio, 19+BASE_ADDRESS, 1} /* Port ControlPort */
	
	/* data receive ports */
	
	/* saps */
	,{&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_1_buttons_0_timer_var, &msgService_PhysicalThreadLowPrio, 126+BASE_ADDRESS, 2} /* Port timer */
	
	/* replicated ports */
	
	/* services */
};
static AButtonController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_1_buttons_0 = {
	&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_1_buttons_0_const,
	
	/* data send ports */
	
	/* attributes */
	0		/* buttonId */,
	0		/* ledId */,
	0		/* floor */
	
	/* state and history are initialized in init function */
};

/* instance _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_1_buttons_1 */
static const AButtonController_const _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_1_buttons_1_const = {
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	{NULL, &msgService_PhysicalThreadLowPrio, 18+BASE_ADDRESS, 1} /* Port ControlPort */
	
	/* data receive ports */
	
	/* saps */
	,{&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_1_buttons_1_timer_var, &msgService_PhysicalThreadLowPrio, 127+BASE_ADDRESS, 2} /* Port timer */
	
	/* replicated ports */
	
	/* services */
};
static AButtonController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_1_buttons_1 = {
	&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_1_buttons_1_const,
	
	/* data send ports */
	
	/* attributes */
	0		/* buttonId */,
	0		/* ledId */,
	0		/* floor */
	
	/* state and history are initialized in init function */
};

/* instance _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_2 */
static const AFloorController_const _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_2_const = {
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	{NULL, &msgService_PhysicalThreadLowPrio, 111+BASE_ADDRESS, 4} /* Port ControlPort */
	,{NULL, &msgService_PhysicalThreadLowPrio, 42+BASE_ADDRESS, 1} /* Port UpButtonPort */
	,{NULL, &msgService_PhysicalThreadLowPrio, 39+BASE_ADDRESS, 2} /* Port DownButtonPort */
	,{NULL, &msgService_PhysicalThreadLowPrio, 36+BASE_ADDRESS, 3} /* Port DoorPort */
	
	/* data receive ports */
	
	/* saps */
	
	/* replicated ports */
	
	/* services */
};
static AFloorController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_2 = {
	&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_2_const,
	
	/* data send ports */
	
	/* attributes */
	0		/* floor */
	
	/* state and history are initialized in init function */
};

/* instance _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_2_door */
static const ADoorController_const _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_2_door_const = {
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	{NULL, &msgService_PhysicalThreadLowPrio, 34+BASE_ADDRESS, 1} /* Port ControlPort */
	
	/* data receive ports */
	
	/* saps */
	,{&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_2_door_timer_var, &msgService_PhysicalThreadLowPrio, 128+BASE_ADDRESS, 2} /* Port timer */
	
	/* replicated ports */
	
	/* services */
};
static ADoorController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_2_door = {
	&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_2_door_const,
	
	/* data send ports */
	
	/* attributes */
	0		/* id */,
	0		/* counter */
	
	/* state and history are initialized in init function */
};

/* instance _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_2_buttons_0 */
static const AButtonController_const _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_2_buttons_0_const = {
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	{NULL, &msgService_PhysicalThreadLowPrio, 33+BASE_ADDRESS, 1} /* Port ControlPort */
	
	/* data receive ports */
	
	/* saps */
	,{&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_2_buttons_0_timer_var, &msgService_PhysicalThreadLowPrio, 129+BASE_ADDRESS, 2} /* Port timer */
	
	/* replicated ports */
	
	/* services */
};
static AButtonController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_2_buttons_0 = {
	&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_2_buttons_0_const,
	
	/* data send ports */
	
	/* attributes */
	0		/* buttonId */,
	0		/* ledId */,
	0		/* floor */
	
	/* state and history are initialized in init function */
};

/* instance _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_2_buttons_1 */
static const AButtonController_const _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_2_buttons_1_const = {
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	{NULL, &msgService_PhysicalThreadLowPrio, 32+BASE_ADDRESS, 1} /* Port ControlPort */
	
	/* data receive ports */
	
	/* saps */
	,{&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_2_buttons_1_timer_var, &msgService_PhysicalThreadLowPrio, 130+BASE_ADDRESS, 2} /* Port timer */
	
	/* replicated ports */
	
	/* services */
};
static AButtonController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_2_buttons_1 = {
	&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_2_buttons_1_const,
	
	/* data send ports */
	
	/* attributes */
	0		/* buttonId */,
	0		/* ledId */,
	0		/* floor */
	
	/* state and history are initialized in init function */
};

/* instance _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_3 */
static const AFloorController_const _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_3_const = {
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	{NULL, &msgService_PhysicalThreadLowPrio, 112+BASE_ADDRESS, 4} /* Port ControlPort */
	,{NULL, &msgService_PhysicalThreadLowPrio, 56+BASE_ADDRESS, 1} /* Port UpButtonPort */
	,{NULL, &msgService_PhysicalThreadLowPrio, 53+BASE_ADDRESS, 2} /* Port DownButtonPort */
	,{NULL, &msgService_PhysicalThreadLowPrio, 50+BASE_ADDRESS, 3} /* Port DoorPort */
	
	/* data receive ports */
	
	/* saps */
	
	/* replicated ports */
	
	/* services */
};
static AFloorController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_3 = {
	&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_3_const,
	
	/* data send ports */
	
	/* attributes */
	0		/* floor */
	
	/* state and history are initialized in init function */
};

/* instance _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_3_door */
static const ADoorController_const _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_3_door_const = {
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	{NULL, &msgService_PhysicalThreadLowPrio, 48+BASE_ADDRESS, 1} /* Port ControlPort */
	
	/* data receive ports */
	
	/* saps */
	,{&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_3_door_timer_var, &msgService_PhysicalThreadLowPrio, 131+BASE_ADDRESS, 2} /* Port timer */
	
	/* replicated ports */
	
	/* services */
};
static ADoorController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_3_door = {
	&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_3_door_const,
	
	/* data send ports */
	
	/* attributes */
	0		/* id */,
	0		/* counter */
	
	/* state and history are initialized in init function */
};

/* instance _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_3_buttons_0 */
static const AButtonController_const _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_3_buttons_0_const = {
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	{NULL, &msgService_PhysicalThreadLowPrio, 47+BASE_ADDRESS, 1} /* Port ControlPort */
	
	/* data receive ports */
	
	/* saps */
	,{&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_3_buttons_0_timer_var, &msgService_PhysicalThreadLowPrio, 132+BASE_ADDRESS, 2} /* Port timer */
	
	/* replicated ports */
	
	/* services */
};
static AButtonController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_3_buttons_0 = {
	&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_3_buttons_0_const,
	
	/* data send ports */
	
	/* attributes */
	0		/* buttonId */,
	0		/* ledId */,
	0		/* floor */
	
	/* state and history are initialized in init function */
};

/* instance _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_3_buttons_1 */
static const AButtonController_const _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_3_buttons_1_const = {
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	{NULL, &msgService_PhysicalThreadLowPrio, 46+BASE_ADDRESS, 1} /* Port ControlPort */
	
	/* data receive ports */
	
	/* saps */
	,{&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_3_buttons_1_timer_var, &msgService_PhysicalThreadLowPrio, 133+BASE_ADDRESS, 2} /* Port timer */
	
	/* replicated ports */
	
	/* services */
};
static AButtonController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_3_buttons_1 = {
	&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_3_buttons_1_const,
	
	/* data send ports */
	
	/* attributes */
	0		/* buttonId */,
	0		/* ledId */,
	0		/* floor */
	
	/* state and history are initialized in init function */
};

/* instance _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_4 */
static const AFloorController_const _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_4_const = {
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	{NULL, &msgService_PhysicalThreadLowPrio, 113+BASE_ADDRESS, 4} /* Port ControlPort */
	,{NULL, &msgService_PhysicalThreadLowPrio, 70+BASE_ADDRESS, 1} /* Port UpButtonPort */
	,{NULL, &msgService_PhysicalThreadLowPrio, 67+BASE_ADDRESS, 2} /* Port DownButtonPort */
	,{NULL, &msgService_PhysicalThreadLowPrio, 64+BASE_ADDRESS, 3} /* Port DoorPort */
	
	/* data receive ports */
	
	/* saps */
	
	/* replicated ports */
	
	/* services */
};
static AFloorController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_4 = {
	&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_4_const,
	
	/* data send ports */
	
	/* attributes */
	0		/* floor */
	
	/* state and history are initialized in init function */
};

/* instance _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_4_door */
static const ADoorController_const _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_4_door_const = {
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	{NULL, &msgService_PhysicalThreadLowPrio, 62+BASE_ADDRESS, 1} /* Port ControlPort */
	
	/* data receive ports */
	
	/* saps */
	,{&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_4_door_timer_var, &msgService_PhysicalThreadLowPrio, 134+BASE_ADDRESS, 2} /* Port timer */
	
	/* replicated ports */
	
	/* services */
};
static ADoorController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_4_door = {
	&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_4_door_const,
	
	/* data send ports */
	
	/* attributes */
	0		/* id */,
	0		/* counter */
	
	/* state and history are initialized in init function */
};

/* instance _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_4_buttons_0 */
static const AButtonController_const _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_4_buttons_0_const = {
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	{NULL, &msgService_PhysicalThreadLowPrio, 61+BASE_ADDRESS, 1} /* Port ControlPort */
	
	/* data receive ports */
	
	/* saps */
	,{&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_4_buttons_0_timer_var, &msgService_PhysicalThreadLowPrio, 135+BASE_ADDRESS, 2} /* Port timer */
	
	/* replicated ports */
	
	/* services */
};
static AButtonController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_4_buttons_0 = {
	&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_4_buttons_0_const,
	
	/* data send ports */
	
	/* attributes */
	0		/* buttonId */,
	0		/* ledId */,
	0		/* floor */
	
	/* state and history are initialized in init function */
};

/* instance _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_4_buttons_1 */
static const AButtonController_const _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_4_buttons_1_const = {
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	{NULL, &msgService_PhysicalThreadLowPrio, 60+BASE_ADDRESS, 1} /* Port ControlPort */
	
	/* data receive ports */
	
	/* saps */
	,{&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_4_buttons_1_timer_var, &msgService_PhysicalThreadLowPrio, 136+BASE_ADDRESS, 2} /* Port timer */
	
	/* replicated ports */
	
	/* services */
};
static AButtonController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_4_buttons_1 = {
	&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_4_buttons_1_const,
	
	/* data send ports */
	
	/* attributes */
	0		/* buttonId */,
	0		/* ledId */,
	0		/* floor */
	
	/* state and history are initialized in init function */
};

/* instance _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_motor */
static const AMotorController_const _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_motor_const = {
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	{NULL, &msgService_PhysicalThreadLowPrio, 108+BASE_ADDRESS, 1} /* Port ControlPort */
	
	/* data receive ports */
	
	/* saps */
	,{&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_motor_timer_var, &msgService_PhysicalThreadLowPrio, 137+BASE_ADDRESS, 2} /* Port timer */
	
	/* replicated ports */
	
	/* services */
};
static AMotorController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_motor = {
	&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_motor_const,
	
	/* data send ports */
	
	/* attributes */
	
	/* state and history are initialized in init function */
};

/* instance _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine */
static const etReplSubPort _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_repl_sub_ports[5] = {
	/* Replicated Sub Ports: {varData, msgService, peerAddress, localId, index} */
	{{NULL,&msgService_PhysicalThreadLowPrio, 88+BASE_ADDRESS, 2},0}, /* Repl Sub Port ButtonPort idx +0*/
	{{NULL,&msgService_PhysicalThreadLowPrio, 91+BASE_ADDRESS, 2},1}, /* Repl Sub Port ButtonPort idx +1*/
	{{NULL,&msgService_PhysicalThreadLowPrio, 94+BASE_ADDRESS, 2},2}, /* Repl Sub Port ButtonPort idx +2*/
	{{NULL,&msgService_PhysicalThreadLowPrio, 97+BASE_ADDRESS, 2},3}, /* Repl Sub Port ButtonPort idx +3*/
	{{NULL,&msgService_PhysicalThreadLowPrio, 100+BASE_ADDRESS, 2},4} /* Repl Sub Port ButtonPort idx +4*/
};
static const ACabineControllerWithIndication_const _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_const = {
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	{NULL, &msgService_PhysicalThreadLowPrio, 107+BASE_ADDRESS, 4} /* Port ControlPort */
	,{NULL, &msgService_PhysicalThreadLowPrio, 85+BASE_ADDRESS, 1} /* Port DoorPort */
	,{NULL, &msgService_PhysicalThreadLowPrio, 103+BASE_ADDRESS, 3} /* Port DoorButtonPort */
	
	/* data receive ports */
	
	/* saps */
	,{&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_timer_var, &msgService_PhysicalThreadLowPrio, 138+BASE_ADDRESS, 5} /* Port timer */
	
	/* replicated ports */
	,{5, _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_repl_sub_ports+0}
	
	/* services */
};
static ACabineControllerWithIndication _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine = {
	&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_const,
	
	/* data send ports */
	
	/* attributes */
	0		/* indicatorPattern */
	
	/* state and history are initialized in init function */
};

/* instance _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_door */
static const ADoorController_const _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_door_const = {
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	{NULL, &msgService_PhysicalThreadLowPrio, 77+BASE_ADDRESS, 1} /* Port ControlPort */
	
	/* data receive ports */
	
	/* saps */
	,{&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_door_timer_var, &msgService_PhysicalThreadLowPrio, 139+BASE_ADDRESS, 2} /* Port timer */
	
	/* replicated ports */
	
	/* services */
};
static ADoorController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_door = {
	&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_door_const,
	
	/* data send ports */
	
	/* attributes */
	0		/* id */,
	0		/* counter */
	
	/* state and history are initialized in init function */
};

/* instance _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_buttons_0 */
static const AButtonController_const _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_buttons_0_const = {
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	{NULL, &msgService_PhysicalThreadLowPrio, 78+BASE_ADDRESS, 1} /* Port ControlPort */
	
	/* data receive ports */
	
	/* saps */
	,{&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_buttons_0_timer_var, &msgService_PhysicalThreadLowPrio, 140+BASE_ADDRESS, 2} /* Port timer */
	
	/* replicated ports */
	
	/* services */
};
static AButtonController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_buttons_0 = {
	&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_buttons_0_const,
	
	/* data send ports */
	
	/* attributes */
	0		/* buttonId */,
	0		/* ledId */,
	0		/* floor */
	
	/* state and history are initialized in init function */
};

/* instance _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_buttons_1 */
static const AButtonController_const _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_buttons_1_const = {
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	{NULL, &msgService_PhysicalThreadLowPrio, 79+BASE_ADDRESS, 1} /* Port ControlPort */
	
	/* data receive ports */
	
	/* saps */
	,{&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_buttons_1_timer_var, &msgService_PhysicalThreadLowPrio, 141+BASE_ADDRESS, 2} /* Port timer */
	
	/* replicated ports */
	
	/* services */
};
static AButtonController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_buttons_1 = {
	&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_buttons_1_const,
	
	/* data send ports */
	
	/* attributes */
	0		/* buttonId */,
	0		/* ledId */,
	0		/* floor */
	
	/* state and history are initialized in init function */
};

/* instance _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_buttons_2 */
static const AButtonController_const _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_buttons_2_const = {
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	{NULL, &msgService_PhysicalThreadLowPrio, 80+BASE_ADDRESS, 1} /* Port ControlPort */
	
	/* data receive ports */
	
	/* saps */
	,{&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_buttons_2_timer_var, &msgService_PhysicalThreadLowPrio, 142+BASE_ADDRESS, 2} /* Port timer */
	
	/* replicated ports */
	
	/* services */
};
static AButtonController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_buttons_2 = {
	&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_buttons_2_const,
	
	/* data send ports */
	
	/* attributes */
	0		/* buttonId */,
	0		/* ledId */,
	0		/* floor */
	
	/* state and history are initialized in init function */
};

/* instance _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_buttons_3 */
static const AButtonController_const _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_buttons_3_const = {
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	{NULL, &msgService_PhysicalThreadLowPrio, 81+BASE_ADDRESS, 1} /* Port ControlPort */
	
	/* data receive ports */
	
	/* saps */
	,{&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_buttons_3_timer_var, &msgService_PhysicalThreadLowPrio, 143+BASE_ADDRESS, 2} /* Port timer */
	
	/* replicated ports */
	
	/* services */
};
static AButtonController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_buttons_3 = {
	&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_buttons_3_const,
	
	/* data send ports */
	
	/* attributes */
	0		/* buttonId */,
	0		/* ledId */,
	0		/* floor */
	
	/* state and history are initialized in init function */
};

/* instance _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_buttons_4 */
static const AButtonController_const _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_buttons_4_const = {
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	{NULL, &msgService_PhysicalThreadLowPrio, 82+BASE_ADDRESS, 1} /* Port ControlPort */
	
	/* data receive ports */
	
	/* saps */
	,{&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_buttons_4_timer_var, &msgService_PhysicalThreadLowPrio, 144+BASE_ADDRESS, 2} /* Port timer */
	
	/* replicated ports */
	
	/* services */
};
static AButtonController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_buttons_4 = {
	&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_buttons_4_const,
	
	/* data send ports */
	
	/* attributes */
	0		/* buttonId */,
	0		/* ledId */,
	0		/* floor */
	
	/* state and history are initialized in init function */
};

/* instance _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_doorButton */
static const AButtonControllerRelMsg_const _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_doorButton_const = {
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	{NULL, &msgService_PhysicalThreadLowPrio, 83+BASE_ADDRESS, 1} /* Port ControlPort */
	
	/* data receive ports */
	
	/* saps */
	,{&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_doorButton_timer_var, &msgService_PhysicalThreadLowPrio, 145+BASE_ADDRESS, 2} /* Port timer */
	
	/* replicated ports */
	
	/* services */
};
static AButtonControllerRelMsg _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_doorButton = {
	&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_doorButton_const,
	
	/* data send ports */
	
	/* attributes */
	0		/* buttonId */,
	0		/* ledId */,
	0		/* floor */
	
	/* state and history are initialized in init function */
};

/* instance _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_top */
static const etReplSubPort _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_top_repl_sub_ports[5] = {
	/* Replicated Sub Ports: {varData, msgService, peerAddress, localId, index} */
	{{NULL,&msgService_PhysicalThreadLowPrio, 3+BASE_ADDRESS, 4},0}, /* Repl Sub Port FloorPort idx +0*/
	{{NULL,&msgService_PhysicalThreadLowPrio, 17+BASE_ADDRESS, 4},1}, /* Repl Sub Port FloorPort idx +1*/
	{{NULL,&msgService_PhysicalThreadLowPrio, 31+BASE_ADDRESS, 4},2}, /* Repl Sub Port FloorPort idx +2*/
	{{NULL,&msgService_PhysicalThreadLowPrio, 45+BASE_ADDRESS, 4},3}, /* Repl Sub Port FloorPort idx +3*/
	{{NULL,&msgService_PhysicalThreadLowPrio, 59+BASE_ADDRESS, 4},4} /* Repl Sub Port FloorPort idx +4*/
};
static const AElevatorMainController_const _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_top_const = {
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	{NULL, &msgService_PhysicalThreadLowPrio, 76+BASE_ADDRESS, 2} /* Port CabinePort */
	,{NULL, &msgService_PhysicalThreadLowPrio, 73+BASE_ADDRESS, 3} /* Port MotorPort */
	,{NULL, NULL, 0+BASE_ADDRESS, 5} /* Port controlPort */
	,{NULL, &msgService_PhysicalThreadLowPrio, 118+BASE_ADDRESS, 1} /* Port HelperPort */
	
	/* data receive ports */
	
	/* saps */
	,{&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_top_timer_var, &msgService_PhysicalThreadLowPrio, 146+BASE_ADDRESS, 6} /* Port timer */
	
	/* replicated ports */
	,{5, _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_top_repl_sub_ports+0}
	
	/* services */
};
static AElevatorMainController _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_top = {
	&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_top_const,
	
	/* data send ports */
	
	/* attributes */
	0		/* floor */,
	0		/* doorStatus */,
	{0, 0, 0, 0, 0}		/* upRequests[5] */,
	{0, 0, 0, 0, 0}		/* downRequests[5] */,
	0		/* idleTime */,
	0		/* idleFloor */,
	0		/* reportState */,
	0		/* idleRequest */,
	0		/* floorRequest */
	
	/* state and history are initialized in init function */
};

/* instance _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_top_helper */
static const AStartGenerator_const _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_top_helper_const = {
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	{NULL, &msgService_PhysicalThreadLowPrio, 115+BASE_ADDRESS, 1} /* Port ControlPort */
	
	/* data receive ports */
	
	/* saps */
	
	/* replicated ports */
	
	/* services */
};
static AStartGenerator _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_top_helper = {
	&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_top_helper_const,
	
	/* data send ports */
	
	/* attributes */
	
	/* state and history are initialized in init function */
};

/* instance _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_ref0 */
static const Test_const _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_ref0_const = {
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	
	/* data receive ports */
	
	/* saps */
	{&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_ref0_timer_var, &msgService_PhysicalThreadLowPrio, 147+BASE_ADDRESS, 1} /* Port timer */
	
	/* replicated ports */
	
	/* services */
};
static Test _ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_ref0 = {
	&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_ref0_const,
	
	/* data send ports */
	
	/* attributes */
	
	/* state and history are initialized in init function */
};

/* instance _ElevatorFreeRTOS_LogSys_elevator_subSysRef_timingService */
static const etReplSubPort _ElevatorFreeRTOS_LogSys_elevator_subSysRef_timingService_repl_sub_ports[26] = {
	/* Replicated Sub Ports: {varData, msgService, peerAddress, localId, index} */
	{{NULL,&msgService_PhysicalThreadLowPrio, 9+BASE_ADDRESS, 1},0}, /* Repl Sub Port timer idx +0*/
	{{NULL,&msgService_PhysicalThreadLowPrio, 12+BASE_ADDRESS, 1},1}, /* Repl Sub Port timer idx +1*/
	{{NULL,&msgService_PhysicalThreadLowPrio, 15+BASE_ADDRESS, 1},2}, /* Repl Sub Port timer idx +2*/
	{{NULL,&msgService_PhysicalThreadLowPrio, 23+BASE_ADDRESS, 1},3}, /* Repl Sub Port timer idx +3*/
	{{NULL,&msgService_PhysicalThreadLowPrio, 26+BASE_ADDRESS, 1},4}, /* Repl Sub Port timer idx +4*/
	{{NULL,&msgService_PhysicalThreadLowPrio, 29+BASE_ADDRESS, 1},5}, /* Repl Sub Port timer idx +5*/
	{{NULL,&msgService_PhysicalThreadLowPrio, 37+BASE_ADDRESS, 1},6}, /* Repl Sub Port timer idx +6*/
	{{NULL,&msgService_PhysicalThreadLowPrio, 40+BASE_ADDRESS, 1},7}, /* Repl Sub Port timer idx +7*/
	{{NULL,&msgService_PhysicalThreadLowPrio, 43+BASE_ADDRESS, 1},8}, /* Repl Sub Port timer idx +8*/
	{{NULL,&msgService_PhysicalThreadLowPrio, 51+BASE_ADDRESS, 1},9}, /* Repl Sub Port timer idx +9*/
	{{NULL,&msgService_PhysicalThreadLowPrio, 54+BASE_ADDRESS, 1},10}, /* Repl Sub Port timer idx +10*/
	{{NULL,&msgService_PhysicalThreadLowPrio, 57+BASE_ADDRESS, 1},11}, /* Repl Sub Port timer idx +11*/
	{{NULL,&msgService_PhysicalThreadLowPrio, 65+BASE_ADDRESS, 1},12}, /* Repl Sub Port timer idx +12*/
	{{NULL,&msgService_PhysicalThreadLowPrio, 68+BASE_ADDRESS, 1},13}, /* Repl Sub Port timer idx +13*/
	{{NULL,&msgService_PhysicalThreadLowPrio, 71+BASE_ADDRESS, 1},14}, /* Repl Sub Port timer idx +14*/
	{{NULL,&msgService_PhysicalThreadLowPrio, 74+BASE_ADDRESS, 1},15}, /* Repl Sub Port timer idx +15*/
	{{NULL,&msgService_PhysicalThreadLowPrio, 105+BASE_ADDRESS, 1},16}, /* Repl Sub Port timer idx +16*/
	{{NULL,&msgService_PhysicalThreadLowPrio, 86+BASE_ADDRESS, 1},17}, /* Repl Sub Port timer idx +17*/
	{{NULL,&msgService_PhysicalThreadLowPrio, 89+BASE_ADDRESS, 1},18}, /* Repl Sub Port timer idx +18*/
	{{NULL,&msgService_PhysicalThreadLowPrio, 92+BASE_ADDRESS, 1},19}, /* Repl Sub Port timer idx +19*/
	{{NULL,&msgService_PhysicalThreadLowPrio, 95+BASE_ADDRESS, 1},20}, /* Repl Sub Port timer idx +20*/
	{{NULL,&msgService_PhysicalThreadLowPrio, 98+BASE_ADDRESS, 1},21}, /* Repl Sub Port timer idx +21*/
	{{NULL,&msgService_PhysicalThreadLowPrio, 101+BASE_ADDRESS, 1},22}, /* Repl Sub Port timer idx +22*/
	{{NULL,&msgService_PhysicalThreadLowPrio, 104+BASE_ADDRESS, 1},23}, /* Repl Sub Port timer idx +23*/
	{{NULL,&msgService_PhysicalThreadLowPrio, 116+BASE_ADDRESS, 1},24}, /* Repl Sub Port timer idx +24*/
	{{NULL,&msgService_PhysicalThreadLowPrio, 120+BASE_ADDRESS, 1},25} /* Repl Sub Port timer idx +25*/
};
static const ATimingService_const _ElevatorFreeRTOS_LogSys_elevator_subSysRef_timingService_const = {
	/* Ports: {varData, msgService, peerAddress, localId} */
	/* simple ports */
	
	/* data receive ports */
	
	/* saps */
	
	/* replicated ports */
	
	/* services */
	{26, _ElevatorFreeRTOS_LogSys_elevator_subSysRef_timingService_repl_sub_ports+0}
};
static ATimingService _ElevatorFreeRTOS_LogSys_elevator_subSysRef_timingService = {
	&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_timingService_const,
	
	/* data send ports */
	
	/* attributes */
	
	/* state and history are initialized in init function */
};

