/**
 * @author generated by eTrice
 *
 * this class contains the main function running Node msp430FreeRTOS with SubSystem elevator_subSysRef
 * it instantiates Node msp430FreeRTOS with SubSystem elevator_subSysRef and starts and ends the lifecycle
 */

#include <string.h>

#include "msp430FreeRTOS_elevator_subSysRef.h"

#include "debugging/etLogger.h"
#include "debugging/etMSCLogger.h"
#include "debugging/etDataLogger.h"

#include "osal/etPlatformLifecycle.h"

/**
 * main function
 * creates component and starts and stops the lifecycle
 */

int main(int argc, char** argv) {
	etBool runAsTest = ET_FALSE;

	if (argc>1 && strcmp(argv[1], "-headless")==0)
		runAsTest = ET_TRUE;
	if (argc>1 && strcmp(argv[1], "-run_as_test")==0)
		runAsTest = ET_TRUE;

	etUserEntry(); /* platform specific */
	
	etLogger_logInfo("***   T H E   B E G I N   ***");
	ET_MSC_LOGGER_OPEN("main");

	/* startup sequence  of lifecycle */
	msp430FreeRTOS_elevator_subSysRef_init(); 		/* lifecycle init */
	msp430FreeRTOS_elevator_subSysRef_start(); 	/* lifecycle start */

	etUserPreRun(); /* platform specific */

	/* run Scheduler */
	msp430FreeRTOS_elevator_subSysRef_run(runAsTest);

	etUserPostRun(); /* platform specific */

	/* shutdown sequence of lifecycle */
	msp430FreeRTOS_elevator_subSysRef_stop(); 		/* lifecycle stop */
	msp430FreeRTOS_elevator_subSysRef_destroy(); 	/* lifecycle destroy */

	ET_MSC_LOGGER_CLOSE
	etLogger_logInfo("***   T H E   E N D   ***");

	etUserExit(); /* platform specific */

	return 0;
}

