/**
 * @author generated by eTrice
 *
 * Source File of ActorClass Test
 * 
 */

#include "Test.h"

#include "modelbase/etActor.h"
#include "debugging/etLogger.h"
#include "debugging/etMSCLogger.h"
#include "etUnit/etUnit.h"
#include "base/etMemory.h"

#include "room/basic/service/timing/PTimer.h"

#include "Test_Utils.h"


/* interface item IDs */
enum interface_items {
	IFITEM_timer = 1
};

/* state IDs */
enum state_ids {
	NO_STATE = 0,
	STATE_TOP = 1,
	STATE_state0 = 2,
	STATE_MAX = 3
};

/* transition chains */
enum chain_ids {
	CHAIN_TRANS_INITIAL_TO__state0 = 1,
	CHAIN_TRANS_tr0_FROM_state0_TO_state0_BY_timeouttimer_tr0 = 2
};

/* triggers */
enum triggers {
	POLLING = 0,
	TRIG_timer__timeout = IFITEM_timer + EVT_SHIFT*PTimer_OUT_timeout
};


static void setState(Test* self, etInt16 new_state) {
	self->state = new_state;
}

static etInt16 getState(Test* self) {
	return self->state;
}

/* Entry and Exit Codes */

/* Action Codes */
static void action_TRANS_INITIAL_TO__state0(Test* self) {
	timer_startTimer(1000);
}
static void action_TRANS_tr0_FROM_state0_TO_state0_BY_timeouttimer_tr0(Test* self, const InterfaceItemBase* ifitem) {
	P10OUT ^= 0x40;
}

/**
 * calls exit codes while exiting from the current state to one of its
 * parent states while remembering the history
 * @param current__et - the current state
 * @param to - the final parent state
 */
static void exitTo(Test* self, etInt16 current__et, etInt16 to) {
	while (current__et!=to) {
		switch (current__et) {
			case STATE_state0:
				self->history[STATE_TOP] = STATE_state0;
				current__et = STATE_TOP;
				break;
			default:
				/* should not occur */
				break;
		}
	}
}

/**
 * calls action, entry and exit codes along a transition chain. The generic data are cast to typed data
 * matching the trigger of this chain. The ID of the final state is returned
 * @param chain__et - the chain ID
 * @param generic_data__et - the generic data pointer
 * @return the +/- ID of the final state either with a positive sign, that indicates to execute the state's entry code, or a negative sign vice versa
 */
static etInt16 executeTransitionChain(Test* self, int chain__et, const InterfaceItemBase* ifitem, void* generic_data__et) {
	switch (chain__et) {
		case CHAIN_TRANS_INITIAL_TO__state0:
		{
			action_TRANS_INITIAL_TO__state0(self);
			return STATE_state0;
		}
		case CHAIN_TRANS_tr0_FROM_state0_TO_state0_BY_timeouttimer_tr0:
		{
			action_TRANS_tr0_FROM_state0_TO_state0_BY_timeouttimer_tr0(self, ifitem);
			return STATE_state0;
		}
			default:
				/* should not occur */
				break;
	}
	return NO_STATE;
}

/**
 * calls entry codes while entering a state's history. The ID of the final leaf state is returned
 * @param state__et - the state which is entered
 * @return - the ID of the final leaf state
 */
static etInt16 enterHistory(Test* self, etInt16 state__et) {
	boolean skip_entry__et = ET_FALSE;
	if (state__et >= STATE_MAX) {
		state__et = (etInt16) (state__et - STATE_MAX);
		skip_entry__et = ET_TRUE;
	}
	while (ET_TRUE) {
		switch (state__et) {
			case STATE_state0:
				/* in leaf state: return state id */
				return STATE_state0;
			case STATE_TOP:
				state__et = self->history[STATE_TOP];
				break;
			default:
				/* should not occur */
				break;
		}
		skip_entry__et = ET_FALSE;
	}
	/* return NO_STATE; // required by CDT but detected as unreachable by JDT because of while (true) */
}

static void Test_executeInitTransition(Test* self) {
	int chain__et = CHAIN_TRANS_INITIAL_TO__state0;
	etInt16 next__et = executeTransitionChain(self, chain__et, NULL, NULL);
	next__et = enterHistory(self, next__et);
	setState(self, next__et);
}

/* receiveEvent contains the main implementation of the FSM */
static void Test_receiveEvent(Test* self, InterfaceItemBase* ifitem, int evt, void* generic_data__et) {
	int trigger__et = ifitem->localId + EVT_SHIFT*evt;
	int chain__et = NOT_CAUGHT;
	etInt16 catching_state__et = NO_STATE;
	((void)trigger__et);	/* avoids unused warning */
	
	if (!handleSystemEvent(ifitem, evt, generic_data__et)) {
		switch (getState(self)) {
			case STATE_state0:
				switch(trigger__et) {
						case TRIG_timer__timeout:
							{
								chain__et = CHAIN_TRANS_tr0_FROM_state0_TO_state0_BY_timeouttimer_tr0;
								catching_state__et = STATE_TOP;
							}
						break;
						default:
							/* should not occur */
							break;
				}
				break;
			default:
				/* should not occur */
				break;
		}
	}
	if (chain__et != NOT_CAUGHT) {
		exitTo(self, getState(self), catching_state__et);
		{
			etInt16 next__et = executeTransitionChain(self, chain__et, ifitem, generic_data__et);
			next__et = enterHistory(self, next__et);
			setState(self, next__et);
		}
	}
}

void Test_init(Test* self){
	ET_MSC_LOGGER_SYNC_ENTRY("Test", "init")
	self->state = STATE_TOP;
	{
		int i;
		for (i=0; i<TEST_HISTORY_SIZE; ++i)
			self->history[i] = NO_STATE;
	}
	Test_executeInitTransition(self);
	ET_MSC_LOGGER_SYNC_EXIT
}


void Test_receiveMessage(void* self, const void* ifitem, const etMessage* msg){
	ET_MSC_LOGGER_SYNC_ENTRY("Test", "_receiveMessage")
	
	Test_receiveEvent(self, (etPort*)ifitem, msg->evtID, (void*)(((char*)msg)+MEM_CEIL(sizeof(etMessage))));
	
	ET_MSC_LOGGER_SYNC_EXIT
}


/*--------------------- operations ---------------------*/

