/**
 * @author generated by eTrice
 *
 * Header File of ActorClass Test
 * 
 */

#ifndef _ELEVATORFREERTOS_MODEL_TEST_H_
#define _ELEVATORFREERTOS_MODEL_TEST_H_

#include "etDatatypes.h"
#include "messaging/etMessage.h"

#include "room/basic/service/timing/PTimer.h"

/*--------------------- begin user code ---------------------*/
#include "msp430f5438a.h"
/*--------------------- end user code ---------------------*/

typedef struct Test Test;

/* const part of ActorClass (ROM) */
typedef struct Test_const {
	/* simple ports */
	
	/* data receive ports */

	/* saps */
	const PTimerConjPort timer;
	
	/* replicated ports */
	
	/* services */
} Test_const;


/* constant for state machine data */
#define TEST_HISTORY_SIZE 2

/* variable part of ActorClass (RAM) */
struct Test {
	const Test_const* const constData;
	
	/* data send ports */
	
	/*--------------------- attributes ---------------------*/
	
	
	/* state machine variables */
	etInt16 state;
	etInt16 history[TEST_HISTORY_SIZE];
};

void Test_init(Test* self);

void Test_receiveMessage(void* self, const void* ifitem, const etMessage* msg);


/*--------------------- operations ---------------------*/


#endif /* _ELEVATORFREERTOS_MODEL_TEST_H_ */

