/**
 * @author generated by eTrice
 *
 * Utils File of ActorClass Application
 * 
 */

#ifndef _HEXAGON_APPLICATION_UTILS_H_
#define _HEXAGON_APPLICATION_UTILS_H_

#include "hexagon/Application.h"

/*
 * access macros for ports, operations and attributes
*/

/* simple event ports */

/* data receive ports */

/* data send ports */

/* saps */

/* replicated event ports */

/* services */

/* operations */

/* attributes */

#endif /* _HEXAGON_APPLICATION_UTILS_H_ */

