/**
 * @author generated by eTrice
 *
 * Source File of ActorClass Application
 * 
 */

#include "Application.h"

#include "modelbase/etActor.h"
#include "debugging/etLogger.h"
#include "debugging/etMSCLogger.h"
#include "etUnit/etUnit.h"
#include "base/etMemory.h"

#include "hexagon/PBlinkyControl.h"
#include "hexagon/PButtonControlProtocoll.h"
#include "hexagon/PButtonProtocoll.h"
#include "DaveInterface/PGUI.h"
#include "DaveInterface/PIO004.h"
#include "room/basic/service/timing/PTimer.h"

#include "Application_Utils.h"


/* interface item IDs */
enum interface_items {
	IFITEM_blinkyPort = 1,
	IFITEM_buttonControlPort = 2,
	IFITEM_buttonPort = 3
};

/* state IDs */
enum state_ids {
	NO_STATE = 0,
	STATE_TOP = 1,
	STATE_running = 2,
	STATE_halted = 3,
	STATE_MAX = 4
};

/* transition chains */
enum chain_ids {
	CHAIN_TRANS_INITIAL_TO__running = 1,
	CHAIN_TRANS_tr1_FROM_running_TO_halted_BY_pressedbuttonPort = 2,
	CHAIN_TRANS_tr0_FROM_halted_TO_running_BY_pressedbuttonPort = 3
};

/* triggers */
enum triggers {
	POLLING = 0,
	TRIG_buttonPort__pressed = IFITEM_buttonPort + EVT_SHIFT*PButtonProtocoll_OUT_pressed,
	TRIG_buttonPort__released = IFITEM_buttonPort + EVT_SHIFT*PButtonProtocoll_OUT_released,
	TRIG_buttonPort__longPressed = IFITEM_buttonPort + EVT_SHIFT*PButtonProtocoll_OUT_longPressed
};

/* state names */
static char* stateStrings[] = {"<no state>","<top>","running",
"halted"
};

static void setState(Application* self, etInt16 new_state) {
	self->state = new_state;
	ET_MSC_LOGGER_CHANGE_STATE(self->constData->instName, stateStrings[new_state])
}

static etInt16 getState(Application* self) {
	return self->state;
}

/* Entry and Exit Codes */

/* Action Codes */
static void action_TRANS_INITIAL_TO__running(Application* self) {
	buttonControlPort_setInstance(2);
}
static void action_TRANS_tr1_FROM_running_TO_halted_BY_pressedbuttonPort(Application* self, const InterfaceItemBase* ifitem) {
	blinkyPort_start();
}
static void action_TRANS_tr0_FROM_halted_TO_running_BY_pressedbuttonPort(Application* self, const InterfaceItemBase* ifitem) {
	blinkyPort_stop();
}

/**
 * calls exit codes while exiting from the current state to one of its
 * parent states while remembering the history
 * @param current__et - the current state
 * @param to - the final parent state
 */
static void exitTo(Application* self, etInt16 current__et, etInt16 to) {
	while (current__et!=to) {
		switch (current__et) {
			case STATE_running:
				self->history[STATE_TOP] = STATE_running;
				current__et = STATE_TOP;
				break;
			case STATE_halted:
				self->history[STATE_TOP] = STATE_halted;
				current__et = STATE_TOP;
				break;
			default:
				/* should not occur */
				break;
		}
	}
}

/**
 * calls action, entry and exit codes along a transition chain. The generic data are cast to typed data
 * matching the trigger of this chain. The ID of the final state is returned
 * @param chain__et - the chain ID
 * @param generic_data__et - the generic data pointer
 * @return the +/- ID of the final state either with a positive sign, that indicates to execute the state's entry code, or a negative sign vice versa
 */
static etInt16 executeTransitionChain(Application* self, int chain__et, const InterfaceItemBase* ifitem, void* generic_data__et) {
	switch (chain__et) {
		case CHAIN_TRANS_INITIAL_TO__running:
		{
			action_TRANS_INITIAL_TO__running(self);
			return STATE_running;
		}
		case CHAIN_TRANS_tr1_FROM_running_TO_halted_BY_pressedbuttonPort:
		{
			action_TRANS_tr1_FROM_running_TO_halted_BY_pressedbuttonPort(self, ifitem);
			return STATE_halted;
		}
		case CHAIN_TRANS_tr0_FROM_halted_TO_running_BY_pressedbuttonPort:
		{
			action_TRANS_tr0_FROM_halted_TO_running_BY_pressedbuttonPort(self, ifitem);
			return STATE_running;
		}
			default:
				/* should not occur */
				break;
	}
	return NO_STATE;
}

/**
 * calls entry codes while entering a state's history. The ID of the final leaf state is returned
 * @param state__et - the state which is entered
 * @return - the ID of the final leaf state
 */
static etInt16 enterHistory(Application* self, etInt16 state__et) {
	boolean skip_entry__et = ET_FALSE;
	if (state__et >= STATE_MAX) {
		state__et = (etInt16) (state__et - STATE_MAX);
		skip_entry__et = ET_TRUE;
	}
	while (ET_TRUE) {
		switch (state__et) {
			case STATE_running:
				/* in leaf state: return state id */
				return STATE_running;
			case STATE_halted:
				/* in leaf state: return state id */
				return STATE_halted;
			case STATE_TOP:
				state__et = self->history[STATE_TOP];
				break;
			default:
				/* should not occur */
				break;
		}
		skip_entry__et = ET_FALSE;
	}
	/* return NO_STATE; // required by CDT but detected as unreachable by JDT because of while (true) */
}

static void Application_executeInitTransition(Application* self) {
	int chain__et = CHAIN_TRANS_INITIAL_TO__running;
	etInt16 next__et = executeTransitionChain(self, chain__et, NULL, NULL);
	next__et = enterHistory(self, next__et);
	setState(self, next__et);
}

/* receiveEvent contains the main implementation of the FSM */
static void Application_receiveEvent(Application* self, InterfaceItemBase* ifitem, int evt, void* generic_data__et) {
	int trigger__et = ifitem->localId + EVT_SHIFT*evt;
	int chain__et = NOT_CAUGHT;
	etInt16 catching_state__et = NO_STATE;
	((void)trigger__et);	/* avoids unused warning */
	
	if (!handleSystemEvent(ifitem, evt, generic_data__et)) {
		switch (getState(self)) {
			case STATE_running:
				switch(trigger__et) {
						case TRIG_buttonPort__pressed:
							{
								chain__et = CHAIN_TRANS_tr1_FROM_running_TO_halted_BY_pressedbuttonPort;
								catching_state__et = STATE_TOP;
							}
						break;
						default:
							/* should not occur */
							break;
				}
				break;
			case STATE_halted:
				switch(trigger__et) {
						case TRIG_buttonPort__pressed:
							{
								chain__et = CHAIN_TRANS_tr0_FROM_halted_TO_running_BY_pressedbuttonPort;
								catching_state__et = STATE_TOP;
							}
						break;
						default:
							/* should not occur */
							break;
				}
				break;
			default:
				/* should not occur */
				break;
		}
	}
	if (chain__et != NOT_CAUGHT) {
		exitTo(self, getState(self), catching_state__et);
		{
			etInt16 next__et = executeTransitionChain(self, chain__et, ifitem, generic_data__et);
			next__et = enterHistory(self, next__et);
			setState(self, next__et);
		}
	}
}

void Application_init(Application* self){
	ET_MSC_LOGGER_SYNC_ENTRY("Application", "init")
	self->state = STATE_TOP;
	{
		int i;
		for (i=0; i<APPLICATION_HISTORY_SIZE; ++i)
			self->history[i] = NO_STATE;
	}
	Application_executeInitTransition(self);
	ET_MSC_LOGGER_SYNC_EXIT
}


void Application_receiveMessage(void* self, const void* ifitem, const etMessage* msg){
	ET_MSC_LOGGER_SYNC_ENTRY("Application", "_receiveMessage")
	
	Application_receiveEvent(self, (etPort*)ifitem, msg->evtID, (void*)(((char*)msg)+MEM_CEIL(sizeof(etMessage))));
	
	ET_MSC_LOGGER_SYNC_EXIT
}


/*--------------------- operations ---------------------*/

