/**
 * @author generated by eTrice
 *
 * Source File of Node nodeRef1 with SubSystem main
 * 
 */

#include <stdio.h>
#include <string.h>


#include "nodeRef1_main.h"

#include "debugging/etLogger.h"
#include "debugging/etMSCLogger.h"
#include "debugging/etDataLogger.h"
#include "messaging/etSystemProtocol.h"
#include "osal/etTimer.h"
#include "osal/etSema.h"
#include "runtime/etRuntime.h"
#include "etRuntimeConfig.h"


/* data for Node nodeRef1 with SubSystem main */
typedef struct nodeRef1_main {
	char *name;
	volatile int shutdownRequest;
} nodeRef1_main;

static nodeRef1_main nodeRef1_mainInst = {"nodeRef1_main", 0};

static void nodeRef1_main_initActorInstances(void);
static void nodeRef1_main_constructActorInstances(void);

/* include instances for all classes */
#include "nodeRef1_main_Inst.h"
#include "nodeRef1_main_Disp.h"

static void nodeRef1_main_initMessageServices(void) {
	ET_MSC_LOGGER_SYNC_ENTRY("nodeRef1_main", "initMessageServices")
	{
		etTime interval;
		
		/* initialization of all message services */
		interval.sec = 0;
		interval.nSec = 10000000;
		etMessageService_init(
			&msgService_PhysicalThread1,
			msgBuffer_PhysicalThread1,
			PHYSICALTHREAD1_POOL_SIZE,
			PHYSICALTHREAD1_BLOCK_SIZE,
			1024,
			0,
			interval,
			MsgDispatcher_PhysicalThread1_receiveMessage,
			EXECMODE_MIXED);
			
	}
	
	ET_MSC_LOGGER_SYNC_EXIT
}

static void nodeRef1_main_startMessageServices(void) {
	ET_MSC_LOGGER_SYNC_ENTRY("nodeRef1_main", "startMessageServices")
	
	etMessageService_start(&msgService_PhysicalThread1);
	
	ET_MSC_LOGGER_SYNC_EXIT
}

static void nodeRef1_main_stopMessageServices(void) {
	ET_MSC_LOGGER_SYNC_ENTRY("nodeRef1_main", "stopMessageServices")
	
	etMessageService_stop(&msgService_PhysicalThread1);
	
	ET_MSC_LOGGER_SYNC_EXIT
}

static void nodeRef1_main_destroyMessageServices(void) {
	ET_MSC_LOGGER_SYNC_ENTRY("nodeRef1_main", "destroyMessageServices")
	
	etMessageService_destroy(&msgService_PhysicalThread1);
	
	ET_MSC_LOGGER_SYNC_EXIT
}

void nodeRef1_main_init(void) {
	ET_MSC_LOGGER_SYNC_ENTRY("nodeRef1_main", "init")
	etLogger_logInfoF("%s_init", nodeRef1_mainInst.name);
	
	/* construct all actors */
	nodeRef1_main_constructActorInstances();
	
	/* initialization of all message services */
	nodeRef1_main_initMessageServices();
	
	/* init all actors */
	nodeRef1_main_initActorInstances();
	
	
	ET_MSC_LOGGER_SYNC_EXIT
}

void nodeRef1_main_start(void) {
	ET_MSC_LOGGER_SYNC_ENTRY("nodeRef1_main", "start")
	etLogger_logInfoF("%s_start", nodeRef1_mainInst.name);
	nodeRef1_main_startMessageServices();
	ET_MSC_LOGGER_SYNC_EXIT
}

void nodeRef1_main_run(etBool runAsTest) {
#ifdef ET_RUNNER_ACTIVATE 
	ET_MSC_LOGGER_SYNC_ENTRY("nodeRef1_main", "run")
	
	if (runAsTest) {
		etSema_waitForWakeup(etRuntime_getTerminateSemaphore());
	}
	else {
		printf("type quit to exit\n");
		fflush(stdout);
		while (ET_TRUE) {
			char line[64];

			if (fgets(line, 64, stdin) != NULL) {
				if (strncmp(line, "quit", 4)==0)
					break;
			}
		}
	}
	
	ET_MSC_LOGGER_SYNC_EXIT
#endif	
}

void nodeRef1_main_stop(void){
	ET_MSC_LOGGER_SYNC_ENTRY("nodeRef1_main", "stop")
	etLogger_logInfoF("%s_stop", nodeRef1_mainInst.name);

	nodeRef1_main_stopMessageServices();
	
	ET_MSC_LOGGER_SYNC_EXIT
}

void nodeRef1_main_destroy(void){
	ET_MSC_LOGGER_SYNC_ENTRY("nodeRef1_main", "destroy")
	etLogger_logInfoF("%s_destroy", nodeRef1_mainInst.name);
	
	nodeRef1_main_destroyMessageServices();
	
	ET_MSC_LOGGER_SYNC_EXIT
}

void nodeRef1_main_shutdown(void){
	ET_MSC_LOGGER_SYNC_ENTRY("nodeRef1_main", "shutdown")
	etLogger_logInfoF("%s_shutdown", nodeRef1_mainInst.name);
	
	nodeRef1_mainInst.shutdownRequest = 1;
	
	ET_MSC_LOGGER_SYNC_EXIT
}


static void nodeRef1_main_constructActorInstances(void){
	ET_MSC_LOGGER_SYNC_ENTRY("nodeRef1_main", "constructActorInstances")
	
	
	ET_MSC_LOGGER_SYNC_EXIT
}

static void nodeRef1_main_initActorInstances(void){
	ET_MSC_LOGGER_SYNC_ENTRY("nodeRef1_main", "initActorInstances")
	
	Application_init(&_hexagon_main_appl);
	ABlinky_init(&_hexagon_main_appl_blinky);
	ATimingService_init(&_hexagon_main_timingService);
	
	ET_MSC_LOGGER_SYNC_EXIT
}
