/**
 * @author generated by eTrice
 *
 * Header File of DataClass DCANMsg
 * 
 */

#ifndef _ROOM_BASIC_SERVICE_CAN_DCANMSG_H_
#define _ROOM_BASIC_SERVICE_CAN_DCANMSG_H_

#include "etDatatypes.h"


		
typedef struct {
	/*--------------------- attributes ---------------------*/
	uint32 id;
	uint8 len;
	uint8 data[8];
} DCANMsg;



/*--------------------- operations ---------------------*/

/* deep copy */
void DCANMsg_deepCopy(DCANMsg* source, DCANMsg* target);


#endif /* _ROOM_BASIC_SERVICE_CAN_DCANMSG_H_ */

