/**
 * @author generated by eTrice
 *
 * Source File of DataClass DCANData
 * 
 */

#include <string.h>

#include "DCANData.h"
#include "DCANData_Utils.h"



/*--------------------- operations ---------------------*/

void DCANData_deepCopy(DCANData* source, DCANData* target) {
	memcpy(target, source, sizeof(DCANData));
}


