/**
 * @author generated by eTrice
 *
 * Source File of DataClass DCANMsg
 * 
 */

#include <string.h>

#include "DCANMsg.h"
#include "DCANMsg_Utils.h"



/*--------------------- operations ---------------------*/

void DCANMsg_deepCopy(DCANMsg* source, DCANMsg* target) {
	memcpy(target, source, sizeof(DCANMsg));
}


