/**
 * @author generated by eTrice
 *
 * Utils File of DataClass DCANMsg
 * 
 */

#ifndef _ROOM_BASIC_SERVICE_CAN_DCANMSG_UTILS_H_
#define _ROOM_BASIC_SERVICE_CAN_DCANMSG_UTILS_H_

#include "room/basic/service/can/DCANMsg.h"

/*
 * access macros for operations and attributes
*/

/* operations */

/* attributes */
#define id (self->id)
#define len (self->len)
#define data (self->data)

#endif /* _ROOM_BASIC_SERVICE_CAN_DCANMSG_UTILS_H_ */

