/**
 * @author generated by eTrice
 *
 * Utils File of DataClass DCANData
 * 
 */

#ifndef _ROOM_BASIC_SERVICE_CAN_DCANDATA_UTILS_H_
#define _ROOM_BASIC_SERVICE_CAN_DCANDATA_UTILS_H_

#include "room/basic/service/can/DCANData.h"

/*
 * access macros for operations and attributes
*/

/* operations */

/* attributes */
#define channel (self->channel)

#endif /* _ROOM_BASIC_SERVICE_CAN_DCANDATA_UTILS_H_ */

