/**
 * @author generated by eTrice
 *
 * Utils File of ProtocolClass PCANRx
 * 
 */

#ifndef _ROOM_BASIC_SERVICE_CAN_PCANRX_UTILS_H_
#define _ROOM_BASIC_SERVICE_CAN_PCANRX_UTILS_H_

#include "room/basic/service/can/PCANRx.h"

/*
 * access macros for operations and attributes
*/

/* conjugate port class */

/* operations */

/* attributes */
#define pChannel (((PCANRxConjPort_var*)(self->varData))->pChannel)

#endif /* _ROOM_BASIC_SERVICE_CAN_PCANRX_UTILS_H_ */

