/**
 * @author generated by eTrice
 *
 * Source File of ProtocolClass PCANRx
 * 
 */

#include "PCANRx.h"
#include "debugging/etMSCLogger.h"
#include "PCANRx_Utils.h"


/*--------------------- port methods */

void PCANRxPort_msgReceived(const PCANRxPort* self, pclCANMsg* data__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PCANRxPort", "msgReceived")
		etPort_sendMessage(self, PCANRx_OUT_msgReceived, sizeof(pclCANMsg), data__et);
	ET_MSC_LOGGER_SYNC_EXIT
}

void PCANRxReplPort_msgReceived_broadcast(const PCANRxReplPort* self, pclCANMsg* data__et) {
	int i;
	ET_MSC_LOGGER_SYNC_ENTRY("PCANRxReplPort", "msgReceived")
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		etPort_sendMessage((&((etReplPort*)self)->ports[i].port), PCANRx_OUT_msgReceived, sizeof(pclCANMsg), data__et);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

void PCANRxReplPort_msgReceived(const PCANRxReplPort* self, int idx__et, pclCANMsg* data__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PCANRxReplPort", "msgReceived")
	if (0<=idx__et && idx__et<((etReplPort*)self)->size) {
		etPort_sendMessage((&((etReplPort*)self)->ports[idx__et].port), PCANRx_OUT_msgReceived, sizeof(pclCANMsg), data__et);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

etInt32 PCANRxReplPort_getReplication(const PCANRxReplPort* self) {
	return ((etReplPort*)self)->size;
}



void PCANRxConjPort_init(const PCANRxConjPort* self, uint32 data__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PCANRxConjPort", "init")
	if(data__et != ET_CAN_CHANNEL_NOT_DEFINED) pChannel = data__et;
	etPort_sendMessage(self, PCANRx_IN_init, sizeof(uint32), &pChannel);
	ET_MSC_LOGGER_SYNC_EXIT
}

void PCANRxConjReplPort_init_broadcast(const PCANRxConjReplPort* self, uint32 data__et) {
	int i;
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		PCANRxConjPort_init(&((etReplPort*)self)->ports[i].port, data__et);
	}					
}

void PCANRxConjReplPort_init(const PCANRxConjReplPort* self, int idx__et, uint32 data__et) {
	PCANRxConjPort_init(&((etReplPort*)self)->ports[idx__et].port, data__et);
}


void PCANRxConjPort_readMsg(const PCANRxConjPort* self) {
	ET_MSC_LOGGER_SYNC_ENTRY("PCANRxConjPort", "readMsg")
		etPort_sendMessage(self, PCANRx_IN_readMsg, 0, NULL);
	ET_MSC_LOGGER_SYNC_EXIT
}

void PCANRxConjReplPort_readMsg_broadcast(const PCANRxConjReplPort* self) {
	int i;
	ET_MSC_LOGGER_SYNC_ENTRY("PCANRxConjReplPort", "readMsg")
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		etPort_sendMessage((&((etReplPort*)self)->ports[i].port), PCANRx_IN_readMsg, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

void PCANRxConjReplPort_readMsg(const PCANRxConjReplPort* self, int idx__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PCANRxConjReplPort", "readMsg")
	if (0<=idx__et && idx__et<((etReplPort*)self)->size) {
		etPort_sendMessage((&((etReplPort*)self)->ports[idx__et].port), PCANRx_IN_readMsg, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}


void PCANRxConjPort_listenOnMsg(const PCANRxConjPort* self, pclCANMsg* data__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PCANRxConjPort", "listenOnMsg")
		etPort_sendMessage(self, PCANRx_IN_listenOnMsg, sizeof(pclCANMsg), data__et);
	ET_MSC_LOGGER_SYNC_EXIT
}

void PCANRxConjReplPort_listenOnMsg_broadcast(const PCANRxConjReplPort* self, pclCANMsg* data__et) {
	int i;
	ET_MSC_LOGGER_SYNC_ENTRY("PCANRxConjReplPort", "listenOnMsg")
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		etPort_sendMessage((&((etReplPort*)self)->ports[i].port), PCANRx_IN_listenOnMsg, sizeof(pclCANMsg), data__et);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

void PCANRxConjReplPort_listenOnMsg(const PCANRxConjReplPort* self, int idx__et, pclCANMsg* data__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PCANRxConjReplPort", "listenOnMsg")
	if (0<=idx__et && idx__et<((etReplPort*)self)->size) {
		etPort_sendMessage((&((etReplPort*)self)->ports[idx__et].port), PCANRx_IN_listenOnMsg, sizeof(pclCANMsg), data__et);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}


void PCANRxConjPort_transmitRequest(const PCANRxConjPort* self) {
	ET_MSC_LOGGER_SYNC_ENTRY("PCANRxConjPort", "transmitRequest")
		etPort_sendMessage(self, PCANRx_IN_transmitRequest, 0, NULL);
	ET_MSC_LOGGER_SYNC_EXIT
}

void PCANRxConjReplPort_transmitRequest_broadcast(const PCANRxConjReplPort* self) {
	int i;
	ET_MSC_LOGGER_SYNC_ENTRY("PCANRxConjReplPort", "transmitRequest")
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		etPort_sendMessage((&((etReplPort*)self)->ports[i].port), PCANRx_IN_transmitRequest, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

void PCANRxConjReplPort_transmitRequest(const PCANRxConjReplPort* self, int idx__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PCANRxConjReplPort", "transmitRequest")
	if (0<=idx__et && idx__et<((etReplPort*)self)->size) {
		etPort_sendMessage((&((etReplPort*)self)->ports[idx__et].port), PCANRx_IN_transmitRequest, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

/* begin PCANRxConjPort specific */

/*--------------------- operations ---------------------*/
/* end PCANRxConjPort specific */

etInt32 PCANRxConjReplPort_getReplication(const PCANRxConjReplPort* self) {
	return ((etReplPort*)self)->size;
}



