/**
 * @author generated by eTrice
 *
 * Header File of ActorClass AButtonControllerRelMsg
 * 
 */

#ifndef _ELEVATORFREERTOS_MODEL_ABUTTONCONTROLLERRELMSG_H_
#define _ELEVATORFREERTOS_MODEL_ABUTTONCONTROLLERRELMSG_H_

#include "etDatatypes.h"
#include "messaging/etMessage.h"

#include "ElevatorFreeRTOS_Model/PButtonControl.h"
#include "room/basic/service/timing/PTimer.h"

/*--------------------- begin user code ---------------------*/
#include "etPlatform.h"
/*--------------------- end user code ---------------------*/

typedef struct AButtonControllerRelMsg AButtonControllerRelMsg;

/* const part of ActorClass (ROM) */
typedef struct AButtonControllerRelMsg_const {
	/* simple ports */
	const PButtonControlPort ControlPort;
	
	/* data receive ports */

	/* saps */
	const PTimerConjPort timer;
	
	/* replicated ports */
	
	/* services */
} AButtonControllerRelMsg_const;


/* constant for state machine data */
#define ABUTTONCONTROLLERRELMSG_HISTORY_SIZE 2

/* variable part of ActorClass (RAM) */
struct AButtonControllerRelMsg {
	const AButtonControllerRelMsg_const* const constData;
	
	/* data send ports */
	
	/*--------------------- attributes ---------------------*/
	uint8 buttonId;
	uint8 ledId;
	uint8 floor;
	
	
	/* state machine variables */
	etInt16 state;
	etInt16 history[ABUTTONCONTROLLERRELMSG_HISTORY_SIZE];
};

void AButtonControllerRelMsg_init(AButtonControllerRelMsg* self);

void AButtonControllerRelMsg_receiveMessage(void* self, const void* ifitem, const etMessage* msg);


/*--------------------- operations ---------------------*/
void AButtonControllerRelMsg_repeatPressed(AButtonControllerRelMsg* self);


#endif /* _ELEVATORFREERTOS_MODEL_ABUTTONCONTROLLERRELMSG_H_ */

