/**
 * @author generated by eTrice
 *
 * Source File of ActorClass ACabineController
 * 
 */

#include "ACabineController.h"

#include "modelbase/etActor.h"
#include "debugging/etLogger.h"
#include "debugging/etMSCLogger.h"
#include "etUnit/etUnit.h"
#include "base/etMemory.h"

#include "ElevatorFreeRTOS_Model/PButtonControl.h"
#include "ElevatorFreeRTOS_Model/PCabineControl.h"
#include "ElevatorFreeRTOS_Model/PDoorControl.h"
#include "room/basic/service/timing/PTimer.h"

#include "ACabineController_Utils.h"


/* interface item IDs */
enum interface_items {
	IFITEM_ControlPort = 4,
	IFITEM_DoorPort = 1,
	IFITEM_ButtonPort = 2,
	IFITEM_DoorButtonPort = 3
};

/* state IDs */
enum state_ids {
	NO_STATE = 0,
	STATE_TOP = 1,
	STATE_doorClosed = 2,
	STATE_doorMoving = 3,
	STATE_MAX = 4
};

/* transition chains */
enum chain_ids {
	CHAIN_TRANS_INITIAL_TO__doorClosed = 1,
	CHAIN_TRANS_tr0_FROM_tp0_TO_tp0_BY_set7segControlPort_tr0 = 2,
	CHAIN_TRANS_tr1_FROM_doorClosed_TO_doorMoving_BY_openDoorControlPort = 3,
	CHAIN_TRANS_tr2_FROM_doorMoving_TO_doorClosed_BY_doneDoorPort = 4,
	CHAIN_TRANS_tr7_FROM_tp2_TO_tp2_BY_floorRequestAckControlPort_tr7 = 5,
	CHAIN_TRANS_tr5_FROM_tp2_TO_tp2_BY_pressedButtonPort_tr5 = 6,
	CHAIN_TRANS_tr6_FROM_tp2_TO_tp2_BY_floorRequestClearControlPort_tr6 = 7,
	CHAIN_TRANS_tr3_FROM_doorMoving_TO_doorMoving_BY_openDoorControlPort_tr3 = 8,
	CHAIN_TRANS_tr4_FROM_tp1_TO_tp1_BY_pressedDoorButtonPort_tr4 = 9
};

/* triggers */
enum triggers {
	POLLING = 0,
	TRIG_DoorPort__done = IFITEM_DoorPort + EVT_SHIFT*PDoorControl_OUT_done,
	TRIG_ButtonPort__pressed = IFITEM_ButtonPort + EVT_SHIFT*PButtonControl_OUT_pressed,
	TRIG_ButtonPort__released = IFITEM_ButtonPort + EVT_SHIFT*PButtonControl_OUT_released,
	TRIG_DoorButtonPort__pressed = IFITEM_DoorButtonPort + EVT_SHIFT*PButtonControl_OUT_pressed,
	TRIG_DoorButtonPort__released = IFITEM_DoorButtonPort + EVT_SHIFT*PButtonControl_OUT_released,
	TRIG_ControlPort__set7seg = IFITEM_ControlPort + EVT_SHIFT*PCabineControl_IN_set7seg,
	TRIG_ControlPort__openDoor = IFITEM_ControlPort + EVT_SHIFT*PCabineControl_IN_openDoor,
	TRIG_ControlPort__closeDoor = IFITEM_ControlPort + EVT_SHIFT*PCabineControl_IN_closeDoor,
	TRIG_ControlPort__floorRequestAck = IFITEM_ControlPort + EVT_SHIFT*PCabineControl_IN_floorRequestAck,
	TRIG_ControlPort__floorRequestClear = IFITEM_ControlPort + EVT_SHIFT*PCabineControl_IN_floorRequestClear,
	TRIG_ControlPort__startIndicateFloors = IFITEM_ControlPort + EVT_SHIFT*PCabineControl_IN_startIndicateFloors,
	TRIG_ControlPort__stopIndicateFloors = IFITEM_ControlPort + EVT_SHIFT*PCabineControl_IN_stopIndicateFloors
};


static void setState(ACabineController* self, etInt16 new_state) {
	self->state = new_state;
}

static etInt16 getState(ACabineController* self) {
	return self->state;
}

/* Entry and Exit Codes */

/* Action Codes */
static void action_TRANS_INITIAL_TO__doorClosed(ACabineController* self) {
	unsigned char i;
	for (i=0;i<5;i++){
		ButtonPort_setFloor(i, i);
		ButtonPort_setButtonId(i, CABINE_BUTTON_ID);
		ButtonPort_setLedId(i, CABINE_SWITCH_LED);
	}
	DoorPort_setFloor(5);
	
	DoorButtonPort_setButtonId(CABINE_DOOR_BUTTON_ID);
	DoorButtonPort_setFloor(0);
	DoorButtonPort_setLedId(0);
}
static void action_TRANS_tr0_FROM_tp0_TO_tp0_BY_set7segControlPort_tr0(ACabineController* self, const InterfaceItemBase* ifitem, uint8 data) {
	writeTo7Seg(data);
}
static void action_TRANS_tr1_FROM_doorClosed_TO_doorMoving_BY_openDoorControlPort(ACabineController* self, const InterfaceItemBase* ifitem) {
	DoorPort_open();
}
static void action_TRANS_tr2_FROM_doorMoving_TO_doorClosed_BY_doneDoorPort(ACabineController* self, const InterfaceItemBase* ifitem) {
	ControlPort_done();
}
static void action_TRANS_tr7_FROM_tp2_TO_tp2_BY_floorRequestAckControlPort_tr7(ACabineController* self, const InterfaceItemBase* ifitem, uint8 data) {
	ButtonPort_ledOn(data);
}
static void action_TRANS_tr5_FROM_tp2_TO_tp2_BY_pressedButtonPort_tr5(ACabineController* self, const InterfaceItemBase* ifitem) {
	unsigned char idx=((etReplSubPort*)ifitem)->index;
	ControlPort_floorRequest(idx);
}
static void action_TRANS_tr6_FROM_tp2_TO_tp2_BY_floorRequestClearControlPort_tr6(ACabineController* self, const InterfaceItemBase* ifitem, uint8 data) {
	ButtonPort_ledOff(data);
}
static void action_TRANS_tr3_FROM_doorMoving_TO_doorMoving_BY_openDoorControlPort_tr3(ACabineController* self, const InterfaceItemBase* ifitem) {
	DoorPort_open();
}
static void action_TRANS_tr4_FROM_tp1_TO_tp1_BY_pressedDoorButtonPort_tr4(ACabineController* self, const InterfaceItemBase* ifitem) {
	ControlPort_doorRequest();
}

/**
 * calls exit codes while exiting from the current state to one of its
 * parent states while remembering the history
 * @param current__et - the current state
 * @param to - the final parent state
 * @param handler__et - entry and exit codes are called only if not handler (for handler TransitionPoints)
 */
static void exitTo(ACabineController* self, etInt16 current__et, etInt16 to, boolean handler__et) {
	while (current__et!=to) {
		switch (current__et) {
			case STATE_doorClosed:
				self->history[STATE_TOP] = STATE_doorClosed;
				current__et = STATE_TOP;
				break;
			case STATE_doorMoving:
				self->history[STATE_TOP] = STATE_doorMoving;
				current__et = STATE_TOP;
				break;
			default:
				/* should not occur */
				break;
		}
	}
}

/**
 * calls action, entry and exit codes along a transition chain. The generic data are cast to typed data
 * matching the trigger of this chain. The ID of the final state is returned
 * @param chain__et - the chain ID
 * @param generic_data__et - the generic data pointer
 * @return the +/- ID of the final state either with a positive sign, that indicates to execute the state's entry code, or a negative sign vice versa
 */
static etInt16 executeTransitionChain(ACabineController* self, int chain__et, const InterfaceItemBase* ifitem, void* generic_data__et) {
	switch (chain__et) {
		case CHAIN_TRANS_INITIAL_TO__doorClosed:
		{
			action_TRANS_INITIAL_TO__doorClosed(self);
			return STATE_doorClosed;
		}
		case CHAIN_TRANS_tr0_FROM_tp0_TO_tp0_BY_set7segControlPort_tr0:
		{
			uint8 data = *((uint8*) generic_data__et);
			action_TRANS_tr0_FROM_tp0_TO_tp0_BY_set7segControlPort_tr0(self, ifitem, data);
			return STATE_TOP + STATE_MAX;
		}
		case CHAIN_TRANS_tr1_FROM_doorClosed_TO_doorMoving_BY_openDoorControlPort:
		{
			action_TRANS_tr1_FROM_doorClosed_TO_doorMoving_BY_openDoorControlPort(self, ifitem);
			return STATE_doorMoving;
		}
		case CHAIN_TRANS_tr2_FROM_doorMoving_TO_doorClosed_BY_doneDoorPort:
		{
			action_TRANS_tr2_FROM_doorMoving_TO_doorClosed_BY_doneDoorPort(self, ifitem);
			return STATE_doorClosed;
		}
		case CHAIN_TRANS_tr7_FROM_tp2_TO_tp2_BY_floorRequestAckControlPort_tr7:
		{
			uint8 data = *((uint8*) generic_data__et);
			action_TRANS_tr7_FROM_tp2_TO_tp2_BY_floorRequestAckControlPort_tr7(self, ifitem, data);
			return STATE_TOP + STATE_MAX;
		}
		case CHAIN_TRANS_tr5_FROM_tp2_TO_tp2_BY_pressedButtonPort_tr5:
		{
			action_TRANS_tr5_FROM_tp2_TO_tp2_BY_pressedButtonPort_tr5(self, ifitem);
			return STATE_TOP + STATE_MAX;
		}
		case CHAIN_TRANS_tr6_FROM_tp2_TO_tp2_BY_floorRequestClearControlPort_tr6:
		{
			uint8 data = *((uint8*) generic_data__et);
			action_TRANS_tr6_FROM_tp2_TO_tp2_BY_floorRequestClearControlPort_tr6(self, ifitem, data);
			return STATE_TOP + STATE_MAX;
		}
		case CHAIN_TRANS_tr3_FROM_doorMoving_TO_doorMoving_BY_openDoorControlPort_tr3:
		{
			action_TRANS_tr3_FROM_doorMoving_TO_doorMoving_BY_openDoorControlPort_tr3(self, ifitem);
			return STATE_doorMoving;
		}
		case CHAIN_TRANS_tr4_FROM_tp1_TO_tp1_BY_pressedDoorButtonPort_tr4:
		{
			action_TRANS_tr4_FROM_tp1_TO_tp1_BY_pressedDoorButtonPort_tr4(self, ifitem);
			return STATE_TOP + STATE_MAX;
		}
			default:
				/* should not occur */
				break;
	}
	return NO_STATE;
}

/**
 * calls entry codes while entering a state's history. The ID of the final leaf state is returned
 * @param state__et - the state which is entered
 * @param handler__et - entry code is executed if not handler
 * @return - the ID of the final leaf state
 */
static etInt16 enterHistory(ACabineController* self, etInt16 state__et, boolean handler__et) {
	boolean skip_entry__et = ET_FALSE;
	if (state__et >= STATE_MAX) {
		state__et = (etInt16) (state__et - STATE_MAX);
		skip_entry__et = ET_TRUE;
	}
	while (ET_TRUE) {
		switch (state__et) {
			case STATE_doorClosed:
				/* in leaf state: return state id */
				return STATE_doorClosed;
			case STATE_doorMoving:
				/* in leaf state: return state id */
				return STATE_doorMoving;
			case STATE_TOP:
				state__et = self->history[STATE_TOP];
				break;
			default:
				/* should not occur */
				break;
		}
		skip_entry__et = ET_FALSE;
	}
	/* return NO_STATE; // required by CDT but detected as unreachable by JDT because of while (true) */
}

static void ACabineController_executeInitTransition(ACabineController* self) {
	int chain__et = CHAIN_TRANS_INITIAL_TO__doorClosed;
	etInt16 next__et = executeTransitionChain(self, chain__et, NULL, NULL);
	next__et = enterHistory(self, next__et, ET_FALSE);
	setState(self, next__et);
}

/* receiveEvent contains the main implementation of the FSM */
static void ACabineController_receiveEvent(ACabineController* self, InterfaceItemBase* ifitem, int evt, void* generic_data__et) {
	int trigger__et = ifitem->localId + EVT_SHIFT*evt;
	int chain__et = NOT_CAUGHT;
	etInt16 catching_state__et = NO_STATE;
	boolean is_handler__et = ET_FALSE;
	((void)trigger__et);	/* avoids unused warning */
	
	if (!handleSystemEvent(ifitem, evt, generic_data__et)) {
		switch (getState(self)) {
			case STATE_doorClosed:
				switch(trigger__et) {
						case TRIG_ControlPort__openDoor:
							{
								chain__et = CHAIN_TRANS_tr1_FROM_doorClosed_TO_doorMoving_BY_openDoorControlPort;
								catching_state__et = STATE_TOP;
							}
						break;
						case TRIG_ControlPort__set7seg:
							{
								chain__et = CHAIN_TRANS_tr0_FROM_tp0_TO_tp0_BY_set7segControlPort_tr0;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_ControlPort__floorRequestAck:
							{
								chain__et = CHAIN_TRANS_tr7_FROM_tp2_TO_tp2_BY_floorRequestAckControlPort_tr7;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_ButtonPort__pressed:
							{
								chain__et = CHAIN_TRANS_tr5_FROM_tp2_TO_tp2_BY_pressedButtonPort_tr5;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_ControlPort__floorRequestClear:
							{
								chain__et = CHAIN_TRANS_tr6_FROM_tp2_TO_tp2_BY_floorRequestClearControlPort_tr6;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_DoorButtonPort__pressed:
							{
								chain__et = CHAIN_TRANS_tr4_FROM_tp1_TO_tp1_BY_pressedDoorButtonPort_tr4;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						default:
							/* should not occur */
							break;
				}
				break;
			case STATE_doorMoving:
				switch(trigger__et) {
						case TRIG_DoorPort__done:
							{
								chain__et = CHAIN_TRANS_tr2_FROM_doorMoving_TO_doorClosed_BY_doneDoorPort;
								catching_state__et = STATE_TOP;
							}
						break;
						case TRIG_ControlPort__openDoor:
							{
								chain__et = CHAIN_TRANS_tr3_FROM_doorMoving_TO_doorMoving_BY_openDoorControlPort_tr3;
								catching_state__et = STATE_TOP;
							}
						break;
						case TRIG_ControlPort__set7seg:
							{
								chain__et = CHAIN_TRANS_tr0_FROM_tp0_TO_tp0_BY_set7segControlPort_tr0;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_ControlPort__floorRequestAck:
							{
								chain__et = CHAIN_TRANS_tr7_FROM_tp2_TO_tp2_BY_floorRequestAckControlPort_tr7;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_ButtonPort__pressed:
							{
								chain__et = CHAIN_TRANS_tr5_FROM_tp2_TO_tp2_BY_pressedButtonPort_tr5;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_ControlPort__floorRequestClear:
							{
								chain__et = CHAIN_TRANS_tr6_FROM_tp2_TO_tp2_BY_floorRequestClearControlPort_tr6;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_DoorButtonPort__pressed:
							{
								chain__et = CHAIN_TRANS_tr4_FROM_tp1_TO_tp1_BY_pressedDoorButtonPort_tr4;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						default:
							/* should not occur */
							break;
				}
				break;
			default:
				/* should not occur */
				break;
		}
	}
	if (chain__et != NOT_CAUGHT) {
		exitTo(self, getState(self), catching_state__et, is_handler__et);
		{
			etInt16 next__et = executeTransitionChain(self, chain__et, ifitem, generic_data__et);
			next__et = enterHistory(self, next__et, is_handler__et);
			setState(self, next__et);
		}
	}
}

void ACabineController_init(ACabineController* self){
	ET_MSC_LOGGER_SYNC_ENTRY("ACabineController", "init")
	self->state = STATE_TOP;
	{
		int i;
		for (i=0; i<ACABINECONTROLLER_HISTORY_SIZE; ++i)
			self->history[i] = NO_STATE;
	}
	ACabineController_executeInitTransition(self);
	ET_MSC_LOGGER_SYNC_EXIT
}


void ACabineController_receiveMessage(void* self, const void* ifitem, const etMessage* msg){
	ET_MSC_LOGGER_SYNC_ENTRY("ACabineController", "_receiveMessage")
	
	ACabineController_receiveEvent(self, (etPort*)ifitem, msg->evtID, (void*)(((char*)msg)+MEM_CEIL(sizeof(etMessage))));
	
	ET_MSC_LOGGER_SYNC_EXIT
}


/*--------------------- operations ---------------------*/

