/**
 * @author generated by eTrice
 *
 * Header File of ActorClass ACabineControllerWithIndication
 * 
 */

#ifndef _ELEVATORFREERTOS_MODEL_ACABINECONTROLLERWITHINDICATION_H_
#define _ELEVATORFREERTOS_MODEL_ACABINECONTROLLERWITHINDICATION_H_

#include "etDatatypes.h"
#include "messaging/etMessage.h"

#include "ElevatorFreeRTOS_Model/PButtonControl.h"
#include "ElevatorFreeRTOS_Model/PCabineControl.h"
#include "ElevatorFreeRTOS_Model/PDoorControl.h"
#include "room/basic/service/timing/PTimer.h"

/*--------------------- begin user code ---------------------*/
#include "etPlatform.h"
/*--------------------- end user code ---------------------*/

typedef struct ACabineControllerWithIndication ACabineControllerWithIndication;

/* const part of ActorClass (ROM) */
typedef struct ACabineControllerWithIndication_const {
	/* simple ports */
	const PCabineControlPort ControlPort;
	const PDoorControlConjPort DoorPort;
	const PButtonControlConjPort DoorButtonPort;
	
	/* data receive ports */

	/* saps */
	const PTimerConjPort timer;
	
	/* replicated ports */
	const etReplPort ButtonPort;
	
	/* services */
} ACabineControllerWithIndication_const;


/* constant for state machine data */
#define ACABINECONTROLLERWITHINDICATION_HISTORY_SIZE 2

/* variable part of ActorClass (RAM) */
struct ACabineControllerWithIndication {
	const ACabineControllerWithIndication_const* const constData;
	
	/* data send ports */
	
	/*--------------------- attributes ---------------------*/
	uint8 indicatorPattern;
	
	
	/* state machine variables */
	etInt16 state;
	etInt16 history[ACABINECONTROLLERWITHINDICATION_HISTORY_SIZE];
};

void ACabineControllerWithIndication_init(ACabineControllerWithIndication* self);

void ACabineControllerWithIndication_receiveMessage(void* self, const void* ifitem, const etMessage* msg);


/*--------------------- operations ---------------------*/


#endif /* _ELEVATORFREERTOS_MODEL_ACABINECONTROLLERWITHINDICATION_H_ */

