/**
 * @author generated by eTrice
 *
 * Source File of ActorClass AFloorController
 * 
 */

#include "AFloorController.h"

#include "modelbase/etActor.h"
#include "debugging/etLogger.h"
#include "debugging/etMSCLogger.h"
#include "etUnit/etUnit.h"
#include "base/etMemory.h"

#include "ElevatorFreeRTOS_Model/PButtonControl.h"
#include "ElevatorFreeRTOS_Model/PDoorControl.h"
#include "ElevatorFreeRTOS_Model/PFloorControl.h"
#include "room/basic/service/timing/PTimer.h"

#include "AFloorController_Utils.h"


/* interface item IDs */
enum interface_items {
	IFITEM_ControlPort = 4,
	IFITEM_UpButtonPort = 1,
	IFITEM_DownButtonPort = 2,
	IFITEM_DoorPort = 3
};

/* state IDs */
enum state_ids {
	NO_STATE = 0,
	STATE_TOP = 1,
	STATE_doorClosed = 2,
	STATE_doorMoving = 3,
	STATE_MAX = 4
};

/* transition chains */
enum chain_ids {
	CHAIN_TRANS_INITIAL_TO__doorClosed = 1,
	CHAIN_TRANS_tr0_FROM_tp0_TO_tp0_BY_setFloorControlPort_tr0 = 2,
	CHAIN_TRANS_tr1_FROM_doorClosed_TO_doorMoving_BY_openDoorControlPort = 3,
	CHAIN_TRANS_tr2_FROM_doorMoving_TO_doorClosed_BY_doneDoorPort = 4,
	CHAIN_TRANS_tr5_FROM_tp1_TO_tp1_BY_requestUpAckControlPort_tr5 = 5,
	CHAIN_TRANS_tr6_FROM_tp1_TO_tp1_BY_requestDownAckControlPort_tr6 = 6,
	CHAIN_TRANS_tr7_FROM_tp2_TO_tp2_BY_pressedUpButtonPort_tr7 = 7,
	CHAIN_TRANS_tr8_FROM_tp2_TO_tp2_BY_pressedDownButtonPort_tr8 = 8,
	CHAIN_TRANS_tr9_FROM_tp1_TO_tp1_BY_requestsClearControlPort_tr9 = 9,
	CHAIN_TRANS_tr3_FROM_doorMoving_TO_doorMoving_BY_openDoorControlPort_tr3 = 10
};

/* triggers */
enum triggers {
	POLLING = 0,
	TRIG_UpButtonPort__pressed = IFITEM_UpButtonPort + EVT_SHIFT*PButtonControl_OUT_pressed,
	TRIG_UpButtonPort__released = IFITEM_UpButtonPort + EVT_SHIFT*PButtonControl_OUT_released,
	TRIG_DownButtonPort__pressed = IFITEM_DownButtonPort + EVT_SHIFT*PButtonControl_OUT_pressed,
	TRIG_DownButtonPort__released = IFITEM_DownButtonPort + EVT_SHIFT*PButtonControl_OUT_released,
	TRIG_DoorPort__done = IFITEM_DoorPort + EVT_SHIFT*PDoorControl_OUT_done,
	TRIG_ControlPort__setFloor = IFITEM_ControlPort + EVT_SHIFT*PFloorControl_IN_setFloor,
	TRIG_ControlPort__openDoor = IFITEM_ControlPort + EVT_SHIFT*PFloorControl_IN_openDoor,
	TRIG_ControlPort__closeDoor = IFITEM_ControlPort + EVT_SHIFT*PFloorControl_IN_closeDoor,
	TRIG_ControlPort__requestUpAck = IFITEM_ControlPort + EVT_SHIFT*PFloorControl_IN_requestUpAck,
	TRIG_ControlPort__requestDownAck = IFITEM_ControlPort + EVT_SHIFT*PFloorControl_IN_requestDownAck,
	TRIG_ControlPort__requestsClear = IFITEM_ControlPort + EVT_SHIFT*PFloorControl_IN_requestsClear
};


static void setState(AFloorController* self, etInt16 new_state) {
	self->state = new_state;
}

static etInt16 getState(AFloorController* self) {
	return self->state;
}

/* Entry and Exit Codes */

/* Action Codes */
static void action_TRANS_tr0_FROM_tp0_TO_tp0_BY_setFloorControlPort_tr0(AFloorController* self, const InterfaceItemBase* ifitem, uint8 data) {
	floor=data;
	UpButtonPort_setFloor(data);
	UpButtonPort_setButtonId(UP_BUTTON_ID);
	UpButtonPort_setLedId(UP_SWITCH_LED);
	
	DownButtonPort_setFloor(data);
	DownButtonPort_setButtonId(DOWN_BUTTON_ID);
	DownButtonPort_setLedId(DOWN_SWITCH_LED);
	
	DoorPort_setFloor(data);
}
static void action_TRANS_tr1_FROM_doorClosed_TO_doorMoving_BY_openDoorControlPort(AFloorController* self, const InterfaceItemBase* ifitem) {
	DoorPort_open();
}
static void action_TRANS_tr2_FROM_doorMoving_TO_doorClosed_BY_doneDoorPort(AFloorController* self, const InterfaceItemBase* ifitem) {
	ControlPort_done();
}
static void action_TRANS_tr5_FROM_tp1_TO_tp1_BY_requestUpAckControlPort_tr5(AFloorController* self, const InterfaceItemBase* ifitem) {
	UpButtonPort_ledOn();
}
static void action_TRANS_tr6_FROM_tp1_TO_tp1_BY_requestDownAckControlPort_tr6(AFloorController* self, const InterfaceItemBase* ifitem) {
	DownButtonPort_ledOn();
}
static void action_TRANS_tr7_FROM_tp2_TO_tp2_BY_pressedUpButtonPort_tr7(AFloorController* self, const InterfaceItemBase* ifitem) {
	ControlPort_requestUp();
}
static void action_TRANS_tr8_FROM_tp2_TO_tp2_BY_pressedDownButtonPort_tr8(AFloorController* self, const InterfaceItemBase* ifitem) {
	ControlPort_requestDown();
}
static void action_TRANS_tr9_FROM_tp1_TO_tp1_BY_requestsClearControlPort_tr9(AFloorController* self, const InterfaceItemBase* ifitem) {
	DownButtonPort_ledOff();
	UpButtonPort_ledOff();
}
static void action_TRANS_tr3_FROM_doorMoving_TO_doorMoving_BY_openDoorControlPort_tr3(AFloorController* self, const InterfaceItemBase* ifitem) {
	DoorPort_open();
}

/**
 * calls exit codes while exiting from the current state to one of its
 * parent states while remembering the history
 * @param current__et - the current state
 * @param to - the final parent state
 * @param handler__et - entry and exit codes are called only if not handler (for handler TransitionPoints)
 */
static void exitTo(AFloorController* self, etInt16 current__et, etInt16 to, boolean handler__et) {
	while (current__et!=to) {
		switch (current__et) {
			case STATE_doorClosed:
				self->history[STATE_TOP] = STATE_doorClosed;
				current__et = STATE_TOP;
				break;
			case STATE_doorMoving:
				self->history[STATE_TOP] = STATE_doorMoving;
				current__et = STATE_TOP;
				break;
			default:
				/* should not occur */
				break;
		}
	}
}

/**
 * calls action, entry and exit codes along a transition chain. The generic data are cast to typed data
 * matching the trigger of this chain. The ID of the final state is returned
 * @param chain__et - the chain ID
 * @param generic_data__et - the generic data pointer
 * @return the +/- ID of the final state either with a positive sign, that indicates to execute the state's entry code, or a negative sign vice versa
 */
static etInt16 executeTransitionChain(AFloorController* self, int chain__et, const InterfaceItemBase* ifitem, void* generic_data__et) {
	switch (chain__et) {
		case CHAIN_TRANS_INITIAL_TO__doorClosed:
		{
			return STATE_doorClosed;
		}
		case CHAIN_TRANS_tr0_FROM_tp0_TO_tp0_BY_setFloorControlPort_tr0:
		{
			uint8 data = *((uint8*) generic_data__et);
			action_TRANS_tr0_FROM_tp0_TO_tp0_BY_setFloorControlPort_tr0(self, ifitem, data);
			return STATE_TOP + STATE_MAX;
		}
		case CHAIN_TRANS_tr1_FROM_doorClosed_TO_doorMoving_BY_openDoorControlPort:
		{
			action_TRANS_tr1_FROM_doorClosed_TO_doorMoving_BY_openDoorControlPort(self, ifitem);
			return STATE_doorMoving;
		}
		case CHAIN_TRANS_tr2_FROM_doorMoving_TO_doorClosed_BY_doneDoorPort:
		{
			action_TRANS_tr2_FROM_doorMoving_TO_doorClosed_BY_doneDoorPort(self, ifitem);
			return STATE_doorClosed;
		}
		case CHAIN_TRANS_tr5_FROM_tp1_TO_tp1_BY_requestUpAckControlPort_tr5:
		{
			action_TRANS_tr5_FROM_tp1_TO_tp1_BY_requestUpAckControlPort_tr5(self, ifitem);
			return STATE_TOP + STATE_MAX;
		}
		case CHAIN_TRANS_tr6_FROM_tp1_TO_tp1_BY_requestDownAckControlPort_tr6:
		{
			action_TRANS_tr6_FROM_tp1_TO_tp1_BY_requestDownAckControlPort_tr6(self, ifitem);
			return STATE_TOP + STATE_MAX;
		}
		case CHAIN_TRANS_tr7_FROM_tp2_TO_tp2_BY_pressedUpButtonPort_tr7:
		{
			action_TRANS_tr7_FROM_tp2_TO_tp2_BY_pressedUpButtonPort_tr7(self, ifitem);
			return STATE_TOP + STATE_MAX;
		}
		case CHAIN_TRANS_tr8_FROM_tp2_TO_tp2_BY_pressedDownButtonPort_tr8:
		{
			action_TRANS_tr8_FROM_tp2_TO_tp2_BY_pressedDownButtonPort_tr8(self, ifitem);
			return STATE_TOP + STATE_MAX;
		}
		case CHAIN_TRANS_tr9_FROM_tp1_TO_tp1_BY_requestsClearControlPort_tr9:
		{
			action_TRANS_tr9_FROM_tp1_TO_tp1_BY_requestsClearControlPort_tr9(self, ifitem);
			return STATE_TOP + STATE_MAX;
		}
		case CHAIN_TRANS_tr3_FROM_doorMoving_TO_doorMoving_BY_openDoorControlPort_tr3:
		{
			action_TRANS_tr3_FROM_doorMoving_TO_doorMoving_BY_openDoorControlPort_tr3(self, ifitem);
			return STATE_doorMoving;
		}
			default:
				/* should not occur */
				break;
	}
	return NO_STATE;
}

/**
 * calls entry codes while entering a state's history. The ID of the final leaf state is returned
 * @param state__et - the state which is entered
 * @param handler__et - entry code is executed if not handler
 * @return - the ID of the final leaf state
 */
static etInt16 enterHistory(AFloorController* self, etInt16 state__et, boolean handler__et) {
	boolean skip_entry__et = ET_FALSE;
	if (state__et >= STATE_MAX) {
		state__et = (etInt16) (state__et - STATE_MAX);
		skip_entry__et = ET_TRUE;
	}
	while (ET_TRUE) {
		switch (state__et) {
			case STATE_doorClosed:
				/* in leaf state: return state id */
				return STATE_doorClosed;
			case STATE_doorMoving:
				/* in leaf state: return state id */
				return STATE_doorMoving;
			case STATE_TOP:
				state__et = self->history[STATE_TOP];
				break;
			default:
				/* should not occur */
				break;
		}
		skip_entry__et = ET_FALSE;
	}
	/* return NO_STATE; // required by CDT but detected as unreachable by JDT because of while (true) */
}

static void AFloorController_executeInitTransition(AFloorController* self) {
	int chain__et = CHAIN_TRANS_INITIAL_TO__doorClosed;
	etInt16 next__et = executeTransitionChain(self, chain__et, NULL, NULL);
	next__et = enterHistory(self, next__et, ET_FALSE);
	setState(self, next__et);
}

/* receiveEvent contains the main implementation of the FSM */
static void AFloorController_receiveEvent(AFloorController* self, InterfaceItemBase* ifitem, int evt, void* generic_data__et) {
	int trigger__et = ifitem->localId + EVT_SHIFT*evt;
	int chain__et = NOT_CAUGHT;
	etInt16 catching_state__et = NO_STATE;
	boolean is_handler__et = ET_FALSE;
	((void)trigger__et);	/* avoids unused warning */
	
	if (!handleSystemEvent(ifitem, evt, generic_data__et)) {
		switch (getState(self)) {
			case STATE_doorClosed:
				switch(trigger__et) {
						case TRIG_ControlPort__openDoor:
							{
								chain__et = CHAIN_TRANS_tr1_FROM_doorClosed_TO_doorMoving_BY_openDoorControlPort;
								catching_state__et = STATE_TOP;
							}
						break;
						case TRIG_ControlPort__setFloor:
							{
								chain__et = CHAIN_TRANS_tr0_FROM_tp0_TO_tp0_BY_setFloorControlPort_tr0;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_ControlPort__requestUpAck:
							{
								chain__et = CHAIN_TRANS_tr5_FROM_tp1_TO_tp1_BY_requestUpAckControlPort_tr5;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_ControlPort__requestDownAck:
							{
								chain__et = CHAIN_TRANS_tr6_FROM_tp1_TO_tp1_BY_requestDownAckControlPort_tr6;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_ControlPort__requestsClear:
							{
								chain__et = CHAIN_TRANS_tr9_FROM_tp1_TO_tp1_BY_requestsClearControlPort_tr9;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_UpButtonPort__pressed:
							{
								chain__et = CHAIN_TRANS_tr7_FROM_tp2_TO_tp2_BY_pressedUpButtonPort_tr7;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_DownButtonPort__pressed:
							{
								chain__et = CHAIN_TRANS_tr8_FROM_tp2_TO_tp2_BY_pressedDownButtonPort_tr8;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						default:
							/* should not occur */
							break;
				}
				break;
			case STATE_doorMoving:
				switch(trigger__et) {
						case TRIG_DoorPort__done:
							{
								chain__et = CHAIN_TRANS_tr2_FROM_doorMoving_TO_doorClosed_BY_doneDoorPort;
								catching_state__et = STATE_TOP;
							}
						break;
						case TRIG_ControlPort__openDoor:
							{
								chain__et = CHAIN_TRANS_tr3_FROM_doorMoving_TO_doorMoving_BY_openDoorControlPort_tr3;
								catching_state__et = STATE_TOP;
							}
						break;
						case TRIG_ControlPort__setFloor:
							{
								chain__et = CHAIN_TRANS_tr0_FROM_tp0_TO_tp0_BY_setFloorControlPort_tr0;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_ControlPort__requestUpAck:
							{
								chain__et = CHAIN_TRANS_tr5_FROM_tp1_TO_tp1_BY_requestUpAckControlPort_tr5;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_ControlPort__requestDownAck:
							{
								chain__et = CHAIN_TRANS_tr6_FROM_tp1_TO_tp1_BY_requestDownAckControlPort_tr6;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_ControlPort__requestsClear:
							{
								chain__et = CHAIN_TRANS_tr9_FROM_tp1_TO_tp1_BY_requestsClearControlPort_tr9;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_UpButtonPort__pressed:
							{
								chain__et = CHAIN_TRANS_tr7_FROM_tp2_TO_tp2_BY_pressedUpButtonPort_tr7;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						case TRIG_DownButtonPort__pressed:
							{
								chain__et = CHAIN_TRANS_tr8_FROM_tp2_TO_tp2_BY_pressedDownButtonPort_tr8;
								catching_state__et = STATE_TOP;
								is_handler__et = ET_TRUE;
							}
						break;
						default:
							/* should not occur */
							break;
				}
				break;
			default:
				/* should not occur */
				break;
		}
	}
	if (chain__et != NOT_CAUGHT) {
		exitTo(self, getState(self), catching_state__et, is_handler__et);
		{
			etInt16 next__et = executeTransitionChain(self, chain__et, ifitem, generic_data__et);
			next__et = enterHistory(self, next__et, is_handler__et);
			setState(self, next__et);
		}
	}
}

void AFloorController_init(AFloorController* self){
	ET_MSC_LOGGER_SYNC_ENTRY("AFloorController", "init")
	self->state = STATE_TOP;
	{
		int i;
		for (i=0; i<AFLOORCONTROLLER_HISTORY_SIZE; ++i)
			self->history[i] = NO_STATE;
	}
	AFloorController_executeInitTransition(self);
	ET_MSC_LOGGER_SYNC_EXIT
}


void AFloorController_receiveMessage(void* self, const void* ifitem, const etMessage* msg){
	ET_MSC_LOGGER_SYNC_ENTRY("AFloorController", "_receiveMessage")
	
	AFloorController_receiveEvent(self, (etPort*)ifitem, msg->evtID, (void*)(((char*)msg)+MEM_CEIL(sizeof(etMessage))));
	
	ET_MSC_LOGGER_SYNC_EXIT
}


/*--------------------- operations ---------------------*/

