/**
 * @author generated by eTrice
 *
 * Source File of ActorClass AMotorController
 * 
 */

#include "AMotorController.h"

#include "modelbase/etActor.h"
#include "debugging/etLogger.h"
#include "debugging/etMSCLogger.h"
#include "etUnit/etUnit.h"
#include "base/etMemory.h"

#include "ElevatorFreeRTOS_Model/PMotorControl.h"
#include "room/basic/service/timing/PTimer.h"

#include "AMotorController_Utils.h"


/* interface item IDs */
enum interface_items {
	IFITEM_ControlPort = 1,
	IFITEM_timer = 2
};

/* state IDs */
enum state_ids {
	NO_STATE = 0,
	STATE_TOP = 1,
	STATE_idle = 2,
	STATE_goinigUp = 3,
	STATE_goingDown = 4,
	STATE_MAX = 5
};

/* transition chains */
enum chain_ids {
	CHAIN_TRANS_INITIAL_TO__idle = 1,
	CHAIN_TRANS_tr0_FROM_idle_TO_goinigUp_BY_goUpOneFloorControlPort = 2,
	CHAIN_TRANS_tr1_FROM_goinigUp_TO_cp0_BY_timeouttimer = 3,
	CHAIN_TRANS_tr2_FROM_idle_TO_goingDown_BY_goDownOneFloorControlPort = 4,
	CHAIN_TRANS_tr5_FROM_goingDown_TO_cp1_BY_timeouttimer = 5
};

/* triggers */
enum triggers {
	POLLING = 0,
	TRIG_ControlPort__goUpOneFloor = IFITEM_ControlPort + EVT_SHIFT*PMotorControl_IN_goUpOneFloor,
	TRIG_ControlPort__goDownOneFloor = IFITEM_ControlPort + EVT_SHIFT*PMotorControl_IN_goDownOneFloor,
	TRIG_timer__timeout = IFITEM_timer + EVT_SHIFT*PTimer_OUT_timeout
};


static void setState(AMotorController* self, etInt16 new_state) {
	self->state = new_state;
}

static etInt16 getState(AMotorController* self) {
	return self->state;
}

/* Entry and Exit Codes */

/* Action Codes */
static void action_TRANS_tr0_FROM_idle_TO_goinigUp_BY_goUpOneFloorControlPort(AMotorController* self, const InterfaceItemBase* ifitem) {
	timer_startTimeout(50);
}
static void action_TRANS_tr1_FROM_goinigUp_TO_cp0_BY_timeouttimer(AMotorController* self, const InterfaceItemBase* ifitem) {
	timer_startTimeout(50);
	shiftMotorUp();
}
static void action_TRANS_tr2_FROM_idle_TO_goingDown_BY_goDownOneFloorControlPort(AMotorController* self, const InterfaceItemBase* ifitem) {
	timer_startTimeout(50);
}
static void action_TRANS_tr3_FROM_cp0_TO_goinigUp(AMotorController* self, const InterfaceItemBase* ifitem) {
	timer_startTimeout(50);
}
static void action_TRANS_tr4_FROM_cp0_TO_idle_COND_tr4(AMotorController* self, const InterfaceItemBase* ifitem) {
	ControlPort_floorReached(getMotorPosition()&0x07);
}
static void action_TRANS_tr5_FROM_goingDown_TO_cp1_BY_timeouttimer(AMotorController* self, const InterfaceItemBase* ifitem) {
	timer_startTimeout(50);
	shiftMotorDown();
}
static void action_TRANS_tr6_FROM_cp1_TO_goingDown(AMotorController* self, const InterfaceItemBase* ifitem) {
	timer_startTimeout(50);
}
static void action_TRANS_tr7_FROM_cp1_TO_idle_COND_tr7(AMotorController* self, const InterfaceItemBase* ifitem) {
	ControlPort_floorReached(getMotorPosition()&0x07);
}

/**
 * calls exit codes while exiting from the current state to one of its
 * parent states while remembering the history
 * @param current__et - the current state
 * @param to - the final parent state
 */
static void exitTo(AMotorController* self, etInt16 current__et, etInt16 to) {
	while (current__et!=to) {
		switch (current__et) {
			case STATE_idle:
				self->history[STATE_TOP] = STATE_idle;
				current__et = STATE_TOP;
				break;
			case STATE_goinigUp:
				self->history[STATE_TOP] = STATE_goinigUp;
				current__et = STATE_TOP;
				break;
			case STATE_goingDown:
				self->history[STATE_TOP] = STATE_goingDown;
				current__et = STATE_TOP;
				break;
			default:
				/* should not occur */
				break;
		}
	}
}

/**
 * calls action, entry and exit codes along a transition chain. The generic data are cast to typed data
 * matching the trigger of this chain. The ID of the final state is returned
 * @param chain__et - the chain ID
 * @param generic_data__et - the generic data pointer
 * @return the +/- ID of the final state either with a positive sign, that indicates to execute the state's entry code, or a negative sign vice versa
 */
static etInt16 executeTransitionChain(AMotorController* self, int chain__et, const InterfaceItemBase* ifitem, void* generic_data__et) {
	switch (chain__et) {
		case CHAIN_TRANS_INITIAL_TO__idle:
		{
			return STATE_idle;
		}
		case CHAIN_TRANS_tr0_FROM_idle_TO_goinigUp_BY_goUpOneFloorControlPort:
		{
			action_TRANS_tr0_FROM_idle_TO_goinigUp_BY_goUpOneFloorControlPort(self, ifitem);
			return STATE_goinigUp;
		}
		case CHAIN_TRANS_tr1_FROM_goinigUp_TO_cp0_BY_timeouttimer:
		{
			action_TRANS_tr1_FROM_goinigUp_TO_cp0_BY_timeouttimer(self, ifitem);
			if (getMotorPosition()) {
			action_TRANS_tr4_FROM_cp0_TO_idle_COND_tr4(self, ifitem);
			return STATE_idle;}
			else {
			action_TRANS_tr3_FROM_cp0_TO_goinigUp(self, ifitem);
			return STATE_goinigUp;}
		}
		case CHAIN_TRANS_tr2_FROM_idle_TO_goingDown_BY_goDownOneFloorControlPort:
		{
			action_TRANS_tr2_FROM_idle_TO_goingDown_BY_goDownOneFloorControlPort(self, ifitem);
			return STATE_goingDown;
		}
		case CHAIN_TRANS_tr5_FROM_goingDown_TO_cp1_BY_timeouttimer:
		{
			action_TRANS_tr5_FROM_goingDown_TO_cp1_BY_timeouttimer(self, ifitem);
			if (getMotorPosition()) {
			action_TRANS_tr7_FROM_cp1_TO_idle_COND_tr7(self, ifitem);
			return STATE_idle;}
			else {
			action_TRANS_tr6_FROM_cp1_TO_goingDown(self, ifitem);
			return STATE_goingDown;}
		}
			default:
				/* should not occur */
				break;
	}
	return NO_STATE;
}

/**
 * calls entry codes while entering a state's history. The ID of the final leaf state is returned
 * @param state__et - the state which is entered
 * @return - the ID of the final leaf state
 */
static etInt16 enterHistory(AMotorController* self, etInt16 state__et) {
	boolean skip_entry__et = ET_FALSE;
	if (state__et >= STATE_MAX) {
		state__et = (etInt16) (state__et - STATE_MAX);
		skip_entry__et = ET_TRUE;
	}
	while (ET_TRUE) {
		switch (state__et) {
			case STATE_idle:
				/* in leaf state: return state id */
				return STATE_idle;
			case STATE_goinigUp:
				/* in leaf state: return state id */
				return STATE_goinigUp;
			case STATE_goingDown:
				/* in leaf state: return state id */
				return STATE_goingDown;
			case STATE_TOP:
				state__et = self->history[STATE_TOP];
				break;
			default:
				/* should not occur */
				break;
		}
		skip_entry__et = ET_FALSE;
	}
	/* return NO_STATE; // required by CDT but detected as unreachable by JDT because of while (true) */
}

static void AMotorController_executeInitTransition(AMotorController* self) {
	int chain__et = CHAIN_TRANS_INITIAL_TO__idle;
	etInt16 next__et = executeTransitionChain(self, chain__et, NULL, NULL);
	next__et = enterHistory(self, next__et);
	setState(self, next__et);
}

/* receiveEvent contains the main implementation of the FSM */
static void AMotorController_receiveEvent(AMotorController* self, InterfaceItemBase* ifitem, int evt, void* generic_data__et) {
	int trigger__et = ifitem->localId + EVT_SHIFT*evt;
	int chain__et = NOT_CAUGHT;
	etInt16 catching_state__et = NO_STATE;
	((void)trigger__et);	/* avoids unused warning */
	
	if (!handleSystemEvent(ifitem, evt, generic_data__et)) {
		switch (getState(self)) {
			case STATE_idle:
				switch(trigger__et) {
						case TRIG_ControlPort__goUpOneFloor:
							{
								chain__et = CHAIN_TRANS_tr0_FROM_idle_TO_goinigUp_BY_goUpOneFloorControlPort;
								catching_state__et = STATE_TOP;
							}
						break;
						case TRIG_ControlPort__goDownOneFloor:
							{
								chain__et = CHAIN_TRANS_tr2_FROM_idle_TO_goingDown_BY_goDownOneFloorControlPort;
								catching_state__et = STATE_TOP;
							}
						break;
						default:
							/* should not occur */
							break;
				}
				break;
			case STATE_goinigUp:
				switch(trigger__et) {
						case TRIG_timer__timeout:
							{
								chain__et = CHAIN_TRANS_tr1_FROM_goinigUp_TO_cp0_BY_timeouttimer;
								catching_state__et = STATE_TOP;
							}
						break;
						default:
							/* should not occur */
							break;
				}
				break;
			case STATE_goingDown:
				switch(trigger__et) {
						case TRIG_timer__timeout:
							{
								chain__et = CHAIN_TRANS_tr5_FROM_goingDown_TO_cp1_BY_timeouttimer;
								catching_state__et = STATE_TOP;
							}
						break;
						default:
							/* should not occur */
							break;
				}
				break;
			default:
				/* should not occur */
				break;
		}
	}
	if (chain__et != NOT_CAUGHT) {
		exitTo(self, getState(self), catching_state__et);
		{
			etInt16 next__et = executeTransitionChain(self, chain__et, ifitem, generic_data__et);
			next__et = enterHistory(self, next__et);
			setState(self, next__et);
		}
	}
}

void AMotorController_init(AMotorController* self){
	ET_MSC_LOGGER_SYNC_ENTRY("AMotorController", "init")
	self->state = STATE_TOP;
	{
		int i;
		for (i=0; i<AMOTORCONTROLLER_HISTORY_SIZE; ++i)
			self->history[i] = NO_STATE;
	}
	AMotorController_executeInitTransition(self);
	ET_MSC_LOGGER_SYNC_EXIT
}


void AMotorController_receiveMessage(void* self, const void* ifitem, const etMessage* msg){
	ET_MSC_LOGGER_SYNC_ENTRY("AMotorController", "_receiveMessage")
	
	AMotorController_receiveEvent(self, (etPort*)ifitem, msg->evtID, (void*)(((char*)msg)+MEM_CEIL(sizeof(etMessage))));
	
	ET_MSC_LOGGER_SYNC_EXIT
}


/*--------------------- operations ---------------------*/

