/**
 * @author generated by eTrice
 *
 * Header File of ActorClass AStartGenerator
 * 
 */

#ifndef _ELEVATORFREERTOS_MODEL_ASTARTGENERATOR_H_
#define _ELEVATORFREERTOS_MODEL_ASTARTGENERATOR_H_

#include "etDatatypes.h"
#include "messaging/etMessage.h"

#include "ElevatorFreeRTOS_Model/PStartGenerator.h"


typedef struct AStartGenerator AStartGenerator;

/* const part of ActorClass (ROM) */
typedef struct AStartGenerator_const {
	/* simple ports */
	const PStartGeneratorPort ControlPort;
	
	/* data receive ports */

	/* saps */
	
	/* replicated ports */
	
	/* services */
} AStartGenerator_const;


/* constant for state machine data */
#define ASTARTGENERATOR_HISTORY_SIZE 2

/* variable part of ActorClass (RAM) */
struct AStartGenerator {
	const AStartGenerator_const* const constData;
	
	/* data send ports */
	
	/*--------------------- attributes ---------------------*/
	
	
	/* state machine variables */
	etInt16 state;
	etInt16 history[ASTARTGENERATOR_HISTORY_SIZE];
};

void AStartGenerator_init(AStartGenerator* self);

void AStartGenerator_receiveMessage(void* self, const void* ifitem, const etMessage* msg);


/*--------------------- operations ---------------------*/


#endif /* _ELEVATORFREERTOS_MODEL_ASTARTGENERATOR_H_ */

