/**
 * @author generated by eTrice
 *
 * Source File of ActorClass ElevatorTop
 * 
 */

#include "ElevatorTop.h"

#include "modelbase/etActor.h"
#include "debugging/etLogger.h"
#include "debugging/etMSCLogger.h"
#include "etUnit/etUnit.h"
#include "base/etMemory.h"

#include "ElevatorFreeRTOS_Model/PButtonControl.h"
#include "ElevatorFreeRTOS_Model/PCabineControl.h"
#include "ElevatorFreeRTOS_Model/PDoorControl.h"
#include "ElevatorFreeRTOS_Model/PFloorControl.h"
#include "ElevatorFreeRTOS_Model/PMainControllerStatus.h"
#include "ElevatorFreeRTOS_Model/PMotorControl.h"
#include "ElevatorFreeRTOS_Model/PStartGenerator.h"
#include "room/basic/service/timing/PTimer.h"

#include "ElevatorTop_Utils.h"


/* interface item IDs */
/* empty enum not generated */


void ElevatorTop_init(ElevatorTop* self){
	ET_MSC_LOGGER_SYNC_ENTRY("ElevatorTop", "init")
	ET_MSC_LOGGER_SYNC_EXIT
}


void ElevatorTop_receiveMessage(void* self, const void* ifitem, const etMessage* msg){
	ET_MSC_LOGGER_SYNC_ENTRY("ElevatorTop", "_receiveMessage")
	
	ET_MSC_LOGGER_SYNC_EXIT
}


/*--------------------- operations ---------------------*/

