/**
 * @author generated by eTrice
 *
 * Header File of ActorClass ElevatorTop
 * 
 */

#ifndef _ELEVATORFREERTOS_MODEL_ELEVATORTOP_H_
#define _ELEVATORFREERTOS_MODEL_ELEVATORTOP_H_

#include "etDatatypes.h"
#include "messaging/etMessage.h"

#include "ElevatorFreeRTOS_Model/PButtonControl.h"
#include "ElevatorFreeRTOS_Model/PCabineControl.h"
#include "ElevatorFreeRTOS_Model/PDoorControl.h"
#include "ElevatorFreeRTOS_Model/PFloorControl.h"
#include "ElevatorFreeRTOS_Model/PMainControllerStatus.h"
#include "ElevatorFreeRTOS_Model/PMotorControl.h"
#include "ElevatorFreeRTOS_Model/PStartGenerator.h"
#include "room/basic/service/timing/PTimer.h"


typedef struct ElevatorTop ElevatorTop;

/* const part of ActorClass (ROM) */
/* this actor class has no ports and thus no constant data */


/* variable part of ActorClass (RAM) */
struct ElevatorTop {
	/* data send ports */
	
	/*--------------------- attributes ---------------------*/
	uint8 dummy;
	
};

void ElevatorTop_init(ElevatorTop* self);

void ElevatorTop_receiveMessage(void* self, const void* ifitem, const etMessage* msg);


/*--------------------- operations ---------------------*/


#endif /* _ELEVATORFREERTOS_MODEL_ELEVATORTOP_H_ */

