/**
 * @author generated by eTrice
 *
 * Source File of Node msp430FreeRTOS with SubSystem elevator_subSysRef
 * 
 */

#include <stdio.h>
#include <string.h>


#include "msp430FreeRTOS_elevator_subSysRef.h"

#include "debugging/etLogger.h"
#include "debugging/etMSCLogger.h"
#include "debugging/etDataLogger.h"
#include "messaging/etSystemProtocol.h"
#include "osal/etTimer.h"
#include "osal/etSema.h"
#include "runtime/etRuntime.h"
#include "etRuntimeConfig.h"


/* data for Node msp430FreeRTOS with SubSystem elevator_subSysRef */
typedef struct msp430FreeRTOS_elevator_subSysRef {
	char *name;
	volatile int shutdownRequest;
} msp430FreeRTOS_elevator_subSysRef;

static msp430FreeRTOS_elevator_subSysRef msp430FreeRTOS_elevator_subSysRefInst = {"msp430FreeRTOS_elevator_subSysRef", 0};

static void msp430FreeRTOS_elevator_subSysRef_initActorInstances(void);
static void msp430FreeRTOS_elevator_subSysRef_constructActorInstances(void);

/* include instances for all classes */
#include "msp430FreeRTOS_elevator_subSysRef_Inst.h"
#include "msp430FreeRTOS_elevator_subSysRef_Disp.h"

static void msp430FreeRTOS_elevator_subSysRef_initMessageServices(void) {
	ET_MSC_LOGGER_SYNC_ENTRY("msp430FreeRTOS_elevator_subSysRef", "initMessageServices")
	{
		etTime interval;
		
		/* initialization of all message services */
		interval.sec = 0;
		interval.nSec = 100000000;
		etMessageService_init(
			&msgService_PhysicalThreadLowPrio,
			msgBuffer_PhysicalThreadLowPrio,
			PHYSICALTHREADLOWPRIO_POOL_SIZE,
			PHYSICALTHREADLOWPRIO_BLOCK_SIZE,
			200,
			3,
			interval,
			MsgDispatcher_PhysicalThreadLowPrio_receiveMessage,
			EXECMODE_MIXED);
			
	}
	
	ET_MSC_LOGGER_SYNC_EXIT
}

static void msp430FreeRTOS_elevator_subSysRef_startMessageServices(void) {
	ET_MSC_LOGGER_SYNC_ENTRY("msp430FreeRTOS_elevator_subSysRef", "startMessageServices")
	
	etMessageService_start(&msgService_PhysicalThreadLowPrio);
	
	ET_MSC_LOGGER_SYNC_EXIT
}

static void msp430FreeRTOS_elevator_subSysRef_stopMessageServices(void) {
	ET_MSC_LOGGER_SYNC_ENTRY("msp430FreeRTOS_elevator_subSysRef", "stopMessageServices")
	
	etMessageService_stop(&msgService_PhysicalThreadLowPrio);
	
	ET_MSC_LOGGER_SYNC_EXIT
}

static void msp430FreeRTOS_elevator_subSysRef_destroyMessageServices(void) {
	ET_MSC_LOGGER_SYNC_ENTRY("msp430FreeRTOS_elevator_subSysRef", "destroyMessageServices")
	
	etMessageService_destroy(&msgService_PhysicalThreadLowPrio);
	
	ET_MSC_LOGGER_SYNC_EXIT
}

void msp430FreeRTOS_elevator_subSysRef_init(void) {
	ET_MSC_LOGGER_SYNC_ENTRY("msp430FreeRTOS_elevator_subSysRef", "init")
	etLogger_logInfoF("%s_init", msp430FreeRTOS_elevator_subSysRefInst.name);
	
	/* construct all actors */
	msp430FreeRTOS_elevator_subSysRef_constructActorInstances();
	
	/* initialization of all message services */
	msp430FreeRTOS_elevator_subSysRef_initMessageServices();
	
	/* init all actors */
	msp430FreeRTOS_elevator_subSysRef_initActorInstances();
	
	
	ET_MSC_LOGGER_SYNC_EXIT
}

void msp430FreeRTOS_elevator_subSysRef_start(void) {
	ET_MSC_LOGGER_SYNC_ENTRY("msp430FreeRTOS_elevator_subSysRef", "start")
	etLogger_logInfoF("%s_start", msp430FreeRTOS_elevator_subSysRefInst.name);
	msp430FreeRTOS_elevator_subSysRef_startMessageServices();
	ET_MSC_LOGGER_SYNC_EXIT
}

void msp430FreeRTOS_elevator_subSysRef_run(etBool runAsTest) {
#ifdef ET_RUNNER_ACTIVATE 
	ET_MSC_LOGGER_SYNC_ENTRY("msp430FreeRTOS_elevator_subSysRef", "run")
	
	if (runAsTest) {
		etSema_waitForWakeup(etRuntime_getTerminateSemaphore());
	}
	else {
		printf("type quit to exit\n");
		fflush(stdout);
		while (ET_TRUE) {
			char line[64];

			if (fgets(line, 64, stdin) != NULL) {
				if (strncmp(line, "quit", 4)==0)
					break;
			}
		}
	}
	
	ET_MSC_LOGGER_SYNC_EXIT
#endif	
}

void msp430FreeRTOS_elevator_subSysRef_stop(void){
	ET_MSC_LOGGER_SYNC_ENTRY("msp430FreeRTOS_elevator_subSysRef", "stop")
	etLogger_logInfoF("%s_stop", msp430FreeRTOS_elevator_subSysRefInst.name);

	msp430FreeRTOS_elevator_subSysRef_stopMessageServices();
	
	ET_MSC_LOGGER_SYNC_EXIT
}

void msp430FreeRTOS_elevator_subSysRef_destroy(void){
	ET_MSC_LOGGER_SYNC_ENTRY("msp430FreeRTOS_elevator_subSysRef", "destroy")
	etLogger_logInfoF("%s_destroy", msp430FreeRTOS_elevator_subSysRefInst.name);
	
	msp430FreeRTOS_elevator_subSysRef_destroyMessageServices();
	
	ET_MSC_LOGGER_SYNC_EXIT
}

void msp430FreeRTOS_elevator_subSysRef_shutdown(void){
	ET_MSC_LOGGER_SYNC_ENTRY("msp430FreeRTOS_elevator_subSysRef", "shutdown")
	etLogger_logInfoF("%s_shutdown", msp430FreeRTOS_elevator_subSysRefInst.name);
	
	msp430FreeRTOS_elevator_subSysRefInst.shutdownRequest = 1;
	
	ET_MSC_LOGGER_SYNC_EXIT
}


static void msp430FreeRTOS_elevator_subSysRef_constructActorInstances(void){
	ET_MSC_LOGGER_SYNC_ENTRY("msp430FreeRTOS_elevator_subSysRef", "constructActorInstances")
	
	
	ET_MSC_LOGGER_SYNC_EXIT
}

static void msp430FreeRTOS_elevator_subSysRef_initActorInstances(void){
	ET_MSC_LOGGER_SYNC_ENTRY("msp430FreeRTOS_elevator_subSysRef", "initActorInstances")
	
	ElevatorTop_init(&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator);
	AFloorController_init(&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_0);
	ADoorController_init(&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_0_door);
	AButtonController_init(&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_0_buttons_0);
	AButtonController_init(&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_0_buttons_1);
	AFloorController_init(&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_1);
	ADoorController_init(&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_1_door);
	AButtonController_init(&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_1_buttons_0);
	AButtonController_init(&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_1_buttons_1);
	AFloorController_init(&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_2);
	ADoorController_init(&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_2_door);
	AButtonController_init(&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_2_buttons_0);
	AButtonController_init(&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_2_buttons_1);
	AFloorController_init(&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_3);
	ADoorController_init(&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_3_door);
	AButtonController_init(&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_3_buttons_0);
	AButtonController_init(&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_3_buttons_1);
	AFloorController_init(&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_4);
	ADoorController_init(&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_4_door);
	AButtonController_init(&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_4_buttons_0);
	AButtonController_init(&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_floors_4_buttons_1);
	AMotorController_init(&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_motor);
	ACabineControllerWithIndication_init(&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine);
	ADoorController_init(&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_door);
	AButtonController_init(&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_buttons_0);
	AButtonController_init(&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_buttons_1);
	AButtonController_init(&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_buttons_2);
	AButtonController_init(&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_buttons_3);
	AButtonController_init(&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_buttons_4);
	AButtonControllerRelMsg_init(&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_cabine_doorButton);
	AElevatorMainController_init(&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_top);
	AStartGenerator_init(&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_top_helper);
	Test_init(&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_elevator_ref0);
	ATimingService_init(&_ElevatorFreeRTOS_LogSys_elevator_subSysRef_timingService);
	
	ET_MSC_LOGGER_SYNC_EXIT
}
