/**
 * @author generated by eTrice
 *
 * Source File of ProtocolClass PButtonControl
 * 
 */

#include "PButtonControl.h"
#include "debugging/etMSCLogger.h"
#include "PButtonControl_Utils.h"


/*--------------------- port methods */

void PButtonControlPort_pressed(const PButtonControlPort* self) {
	ET_MSC_LOGGER_SYNC_ENTRY("PButtonControlPort", "pressed")
		etPort_sendMessage(self, PButtonControl_OUT_pressed, 0, NULL);
	ET_MSC_LOGGER_SYNC_EXIT
}

void PButtonControlReplPort_pressed_broadcast(const PButtonControlReplPort* self) {
	int i;
	ET_MSC_LOGGER_SYNC_ENTRY("PButtonControlReplPort", "pressed")
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		etPort_sendMessage((&((etReplPort*)self)->ports[i].port), PButtonControl_OUT_pressed, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

void PButtonControlReplPort_pressed(const PButtonControlReplPort* self, int idx__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PButtonControlReplPort", "pressed")
	if (0<=idx__et && idx__et<((etReplPort*)self)->size) {
		etPort_sendMessage((&((etReplPort*)self)->ports[idx__et].port), PButtonControl_OUT_pressed, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}


void PButtonControlPort_released(const PButtonControlPort* self) {
	ET_MSC_LOGGER_SYNC_ENTRY("PButtonControlPort", "released")
		etPort_sendMessage(self, PButtonControl_OUT_released, 0, NULL);
	ET_MSC_LOGGER_SYNC_EXIT
}

void PButtonControlReplPort_released_broadcast(const PButtonControlReplPort* self) {
	int i;
	ET_MSC_LOGGER_SYNC_ENTRY("PButtonControlReplPort", "released")
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		etPort_sendMessage((&((etReplPort*)self)->ports[i].port), PButtonControl_OUT_released, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

void PButtonControlReplPort_released(const PButtonControlReplPort* self, int idx__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PButtonControlReplPort", "released")
	if (0<=idx__et && idx__et<((etReplPort*)self)->size) {
		etPort_sendMessage((&((etReplPort*)self)->ports[idx__et].port), PButtonControl_OUT_released, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

etInt32 PButtonControlReplPort_getReplication(const PButtonControlReplPort* self) {
	return ((etReplPort*)self)->size;
}



void PButtonControlConjPort_setButtonId(const PButtonControlConjPort* self, uint8 data__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PButtonControlConjPort", "setButtonId")
		etPort_sendMessage(self, PButtonControl_IN_setButtonId, sizeof(uint8), &data__et);
	ET_MSC_LOGGER_SYNC_EXIT
}

void PButtonControlConjReplPort_setButtonId_broadcast(const PButtonControlConjReplPort* self, uint8 data__et) {
	int i;
	ET_MSC_LOGGER_SYNC_ENTRY("PButtonControlConjReplPort", "setButtonId")
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		etPort_sendMessage((&((etReplPort*)self)->ports[i].port), PButtonControl_IN_setButtonId, sizeof(uint8), &data__et);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

void PButtonControlConjReplPort_setButtonId(const PButtonControlConjReplPort* self, int idx__et, uint8 data__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PButtonControlConjReplPort", "setButtonId")
	if (0<=idx__et && idx__et<((etReplPort*)self)->size) {
		etPort_sendMessage((&((etReplPort*)self)->ports[idx__et].port), PButtonControl_IN_setButtonId, sizeof(uint8), &data__et);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}


void PButtonControlConjPort_setLedId(const PButtonControlConjPort* self, uint8 data__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PButtonControlConjPort", "setLedId")
		etPort_sendMessage(self, PButtonControl_IN_setLedId, sizeof(uint8), &data__et);
	ET_MSC_LOGGER_SYNC_EXIT
}

void PButtonControlConjReplPort_setLedId_broadcast(const PButtonControlConjReplPort* self, uint8 data__et) {
	int i;
	ET_MSC_LOGGER_SYNC_ENTRY("PButtonControlConjReplPort", "setLedId")
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		etPort_sendMessage((&((etReplPort*)self)->ports[i].port), PButtonControl_IN_setLedId, sizeof(uint8), &data__et);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

void PButtonControlConjReplPort_setLedId(const PButtonControlConjReplPort* self, int idx__et, uint8 data__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PButtonControlConjReplPort", "setLedId")
	if (0<=idx__et && idx__et<((etReplPort*)self)->size) {
		etPort_sendMessage((&((etReplPort*)self)->ports[idx__et].port), PButtonControl_IN_setLedId, sizeof(uint8), &data__et);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}


void PButtonControlConjPort_setFloor(const PButtonControlConjPort* self, uint8 data__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PButtonControlConjPort", "setFloor")
		etPort_sendMessage(self, PButtonControl_IN_setFloor, sizeof(uint8), &data__et);
	ET_MSC_LOGGER_SYNC_EXIT
}

void PButtonControlConjReplPort_setFloor_broadcast(const PButtonControlConjReplPort* self, uint8 data__et) {
	int i;
	ET_MSC_LOGGER_SYNC_ENTRY("PButtonControlConjReplPort", "setFloor")
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		etPort_sendMessage((&((etReplPort*)self)->ports[i].port), PButtonControl_IN_setFloor, sizeof(uint8), &data__et);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

void PButtonControlConjReplPort_setFloor(const PButtonControlConjReplPort* self, int idx__et, uint8 data__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PButtonControlConjReplPort", "setFloor")
	if (0<=idx__et && idx__et<((etReplPort*)self)->size) {
		etPort_sendMessage((&((etReplPort*)self)->ports[idx__et].port), PButtonControl_IN_setFloor, sizeof(uint8), &data__et);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}


void PButtonControlConjPort_ledOn(const PButtonControlConjPort* self) {
	ET_MSC_LOGGER_SYNC_ENTRY("PButtonControlConjPort", "ledOn")
		etPort_sendMessage(self, PButtonControl_IN_ledOn, 0, NULL);
	ET_MSC_LOGGER_SYNC_EXIT
}

void PButtonControlConjReplPort_ledOn_broadcast(const PButtonControlConjReplPort* self) {
	int i;
	ET_MSC_LOGGER_SYNC_ENTRY("PButtonControlConjReplPort", "ledOn")
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		etPort_sendMessage((&((etReplPort*)self)->ports[i].port), PButtonControl_IN_ledOn, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

void PButtonControlConjReplPort_ledOn(const PButtonControlConjReplPort* self, int idx__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PButtonControlConjReplPort", "ledOn")
	if (0<=idx__et && idx__et<((etReplPort*)self)->size) {
		etPort_sendMessage((&((etReplPort*)self)->ports[idx__et].port), PButtonControl_IN_ledOn, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}


void PButtonControlConjPort_ledOff(const PButtonControlConjPort* self) {
	ET_MSC_LOGGER_SYNC_ENTRY("PButtonControlConjPort", "ledOff")
		etPort_sendMessage(self, PButtonControl_IN_ledOff, 0, NULL);
	ET_MSC_LOGGER_SYNC_EXIT
}

void PButtonControlConjReplPort_ledOff_broadcast(const PButtonControlConjReplPort* self) {
	int i;
	ET_MSC_LOGGER_SYNC_ENTRY("PButtonControlConjReplPort", "ledOff")
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		etPort_sendMessage((&((etReplPort*)self)->ports[i].port), PButtonControl_IN_ledOff, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

void PButtonControlConjReplPort_ledOff(const PButtonControlConjReplPort* self, int idx__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PButtonControlConjReplPort", "ledOff")
	if (0<=idx__et && idx__et<((etReplPort*)self)->size) {
		etPort_sendMessage((&((etReplPort*)self)->ports[idx__et].port), PButtonControl_IN_ledOff, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}


void PButtonControlConjPort_ledToggle(const PButtonControlConjPort* self) {
	ET_MSC_LOGGER_SYNC_ENTRY("PButtonControlConjPort", "ledToggle")
		etPort_sendMessage(self, PButtonControl_IN_ledToggle, 0, NULL);
	ET_MSC_LOGGER_SYNC_EXIT
}

void PButtonControlConjReplPort_ledToggle_broadcast(const PButtonControlConjReplPort* self) {
	int i;
	ET_MSC_LOGGER_SYNC_ENTRY("PButtonControlConjReplPort", "ledToggle")
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		etPort_sendMessage((&((etReplPort*)self)->ports[i].port), PButtonControl_IN_ledToggle, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

void PButtonControlConjReplPort_ledToggle(const PButtonControlConjReplPort* self, int idx__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PButtonControlConjReplPort", "ledToggle")
	if (0<=idx__et && idx__et<((etReplPort*)self)->size) {
		etPort_sendMessage((&((etReplPort*)self)->ports[idx__et].port), PButtonControl_IN_ledToggle, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

etInt32 PButtonControlConjReplPort_getReplication(const PButtonControlConjReplPort* self) {
	return ((etReplPort*)self)->size;
}



