/**
 * @author generated by eTrice
 *
 * Source File of ProtocolClass PDoorControl
 * 
 */

#include "PDoorControl.h"
#include "debugging/etMSCLogger.h"
#include "PDoorControl_Utils.h"


/*--------------------- port methods */

void PDoorControlPort_done(const PDoorControlPort* self) {
	ET_MSC_LOGGER_SYNC_ENTRY("PDoorControlPort", "done")
		etPort_sendMessage(self, PDoorControl_OUT_done, 0, NULL);
	ET_MSC_LOGGER_SYNC_EXIT
}

void PDoorControlReplPort_done_broadcast(const PDoorControlReplPort* self) {
	int i;
	ET_MSC_LOGGER_SYNC_ENTRY("PDoorControlReplPort", "done")
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		etPort_sendMessage((&((etReplPort*)self)->ports[i].port), PDoorControl_OUT_done, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

void PDoorControlReplPort_done(const PDoorControlReplPort* self, int idx__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PDoorControlReplPort", "done")
	if (0<=idx__et && idx__et<((etReplPort*)self)->size) {
		etPort_sendMessage((&((etReplPort*)self)->ports[idx__et].port), PDoorControl_OUT_done, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

etInt32 PDoorControlReplPort_getReplication(const PDoorControlReplPort* self) {
	return ((etReplPort*)self)->size;
}



void PDoorControlConjPort_setFloor(const PDoorControlConjPort* self, uint8 data__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PDoorControlConjPort", "setFloor")
		etPort_sendMessage(self, PDoorControl_IN_setFloor, sizeof(uint8), &data__et);
	ET_MSC_LOGGER_SYNC_EXIT
}

void PDoorControlConjReplPort_setFloor_broadcast(const PDoorControlConjReplPort* self, uint8 data__et) {
	int i;
	ET_MSC_LOGGER_SYNC_ENTRY("PDoorControlConjReplPort", "setFloor")
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		etPort_sendMessage((&((etReplPort*)self)->ports[i].port), PDoorControl_IN_setFloor, sizeof(uint8), &data__et);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

void PDoorControlConjReplPort_setFloor(const PDoorControlConjReplPort* self, int idx__et, uint8 data__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PDoorControlConjReplPort", "setFloor")
	if (0<=idx__et && idx__et<((etReplPort*)self)->size) {
		etPort_sendMessage((&((etReplPort*)self)->ports[idx__et].port), PDoorControl_IN_setFloor, sizeof(uint8), &data__et);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}


void PDoorControlConjPort_open(const PDoorControlConjPort* self) {
	ET_MSC_LOGGER_SYNC_ENTRY("PDoorControlConjPort", "open")
		etPort_sendMessage(self, PDoorControl_IN_open, 0, NULL);
	ET_MSC_LOGGER_SYNC_EXIT
}

void PDoorControlConjReplPort_open_broadcast(const PDoorControlConjReplPort* self) {
	int i;
	ET_MSC_LOGGER_SYNC_ENTRY("PDoorControlConjReplPort", "open")
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		etPort_sendMessage((&((etReplPort*)self)->ports[i].port), PDoorControl_IN_open, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

void PDoorControlConjReplPort_open(const PDoorControlConjReplPort* self, int idx__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PDoorControlConjReplPort", "open")
	if (0<=idx__et && idx__et<((etReplPort*)self)->size) {
		etPort_sendMessage((&((etReplPort*)self)->ports[idx__et].port), PDoorControl_IN_open, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}


void PDoorControlConjPort_close(const PDoorControlConjPort* self) {
	ET_MSC_LOGGER_SYNC_ENTRY("PDoorControlConjPort", "close")
		etPort_sendMessage(self, PDoorControl_IN_close, 0, NULL);
	ET_MSC_LOGGER_SYNC_EXIT
}

void PDoorControlConjReplPort_close_broadcast(const PDoorControlConjReplPort* self) {
	int i;
	ET_MSC_LOGGER_SYNC_ENTRY("PDoorControlConjReplPort", "close")
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		etPort_sendMessage((&((etReplPort*)self)->ports[i].port), PDoorControl_IN_close, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

void PDoorControlConjReplPort_close(const PDoorControlConjReplPort* self, int idx__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PDoorControlConjReplPort", "close")
	if (0<=idx__et && idx__et<((etReplPort*)self)->size) {
		etPort_sendMessage((&((etReplPort*)self)->ports[idx__et].port), PDoorControl_IN_close, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

etInt32 PDoorControlConjReplPort_getReplication(const PDoorControlConjReplPort* self) {
	return ((etReplPort*)self)->size;
}



