/**
 * @author generated by eTrice
 *
 * Source File of ProtocolClass PMainControllerStatus
 * 
 */

#include "PMainControllerStatus.h"
#include "debugging/etMSCLogger.h"
#include "PMainControllerStatus_Utils.h"


/*--------------------- port methods */

void PMainControllerStatusPort_status(const PMainControllerStatusPort* self, uint32 data__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PMainControllerStatusPort", "status")
		etPort_sendMessage(self, PMainControllerStatus_OUT_status, sizeof(uint32), &data__et);
	ET_MSC_LOGGER_SYNC_EXIT
}

void PMainControllerStatusReplPort_status_broadcast(const PMainControllerStatusReplPort* self, uint32 data__et) {
	int i;
	ET_MSC_LOGGER_SYNC_ENTRY("PMainControllerStatusReplPort", "status")
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		etPort_sendMessage((&((etReplPort*)self)->ports[i].port), PMainControllerStatus_OUT_status, sizeof(uint32), &data__et);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

void PMainControllerStatusReplPort_status(const PMainControllerStatusReplPort* self, int idx__et, uint32 data__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PMainControllerStatusReplPort", "status")
	if (0<=idx__et && idx__et<((etReplPort*)self)->size) {
		etPort_sendMessage((&((etReplPort*)self)->ports[idx__et].port), PMainControllerStatus_OUT_status, sizeof(uint32), &data__et);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}


void PMainControllerStatusPort_idle(const PMainControllerStatusPort* self) {
	ET_MSC_LOGGER_SYNC_ENTRY("PMainControllerStatusPort", "idle")
		etPort_sendMessage(self, PMainControllerStatus_OUT_idle, 0, NULL);
	ET_MSC_LOGGER_SYNC_EXIT
}

void PMainControllerStatusReplPort_idle_broadcast(const PMainControllerStatusReplPort* self) {
	int i;
	ET_MSC_LOGGER_SYNC_ENTRY("PMainControllerStatusReplPort", "idle")
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		etPort_sendMessage((&((etReplPort*)self)->ports[i].port), PMainControllerStatus_OUT_idle, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

void PMainControllerStatusReplPort_idle(const PMainControllerStatusReplPort* self, int idx__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PMainControllerStatusReplPort", "idle")
	if (0<=idx__et && idx__et<((etReplPort*)self)->size) {
		etPort_sendMessage((&((etReplPort*)self)->ports[idx__et].port), PMainControllerStatus_OUT_idle, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}


void PMainControllerStatusPort_floor(const PMainControllerStatusPort* self, uint8 data__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PMainControllerStatusPort", "floor")
		etPort_sendMessage(self, PMainControllerStatus_OUT_floor, sizeof(uint8), &data__et);
	ET_MSC_LOGGER_SYNC_EXIT
}

void PMainControllerStatusReplPort_floor_broadcast(const PMainControllerStatusReplPort* self, uint8 data__et) {
	int i;
	ET_MSC_LOGGER_SYNC_ENTRY("PMainControllerStatusReplPort", "floor")
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		etPort_sendMessage((&((etReplPort*)self)->ports[i].port), PMainControllerStatus_OUT_floor, sizeof(uint8), &data__et);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

void PMainControllerStatusReplPort_floor(const PMainControllerStatusReplPort* self, int idx__et, uint8 data__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PMainControllerStatusReplPort", "floor")
	if (0<=idx__et && idx__et<((etReplPort*)self)->size) {
		etPort_sendMessage((&((etReplPort*)self)->ports[idx__et].port), PMainControllerStatus_OUT_floor, sizeof(uint8), &data__et);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

etInt32 PMainControllerStatusReplPort_getReplication(const PMainControllerStatusReplPort* self) {
	return ((etReplPort*)self)->size;
}



void PMainControllerStatusConjPort_getStatus(const PMainControllerStatusConjPort* self) {
	ET_MSC_LOGGER_SYNC_ENTRY("PMainControllerStatusConjPort", "getStatus")
		etPort_sendMessage(self, PMainControllerStatus_IN_getStatus, 0, NULL);
	ET_MSC_LOGGER_SYNC_EXIT
}

void PMainControllerStatusConjReplPort_getStatus_broadcast(const PMainControllerStatusConjReplPort* self) {
	int i;
	ET_MSC_LOGGER_SYNC_ENTRY("PMainControllerStatusConjReplPort", "getStatus")
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		etPort_sendMessage((&((etReplPort*)self)->ports[i].port), PMainControllerStatus_IN_getStatus, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

void PMainControllerStatusConjReplPort_getStatus(const PMainControllerStatusConjReplPort* self, int idx__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PMainControllerStatusConjReplPort", "getStatus")
	if (0<=idx__et && idx__et<((etReplPort*)self)->size) {
		etPort_sendMessage((&((etReplPort*)self)->ports[idx__et].port), PMainControllerStatus_IN_getStatus, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}


void PMainControllerStatusConjPort_setIdleFloor(const PMainControllerStatusConjPort* self, uint8 data__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PMainControllerStatusConjPort", "setIdleFloor")
		etPort_sendMessage(self, PMainControllerStatus_IN_setIdleFloor, sizeof(uint8), &data__et);
	ET_MSC_LOGGER_SYNC_EXIT
}

void PMainControllerStatusConjReplPort_setIdleFloor_broadcast(const PMainControllerStatusConjReplPort* self, uint8 data__et) {
	int i;
	ET_MSC_LOGGER_SYNC_ENTRY("PMainControllerStatusConjReplPort", "setIdleFloor")
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		etPort_sendMessage((&((etReplPort*)self)->ports[i].port), PMainControllerStatus_IN_setIdleFloor, sizeof(uint8), &data__et);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

void PMainControllerStatusConjReplPort_setIdleFloor(const PMainControllerStatusConjReplPort* self, int idx__et, uint8 data__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PMainControllerStatusConjReplPort", "setIdleFloor")
	if (0<=idx__et && idx__et<((etReplPort*)self)->size) {
		etPort_sendMessage((&((etReplPort*)self)->ports[idx__et].port), PMainControllerStatus_IN_setIdleFloor, sizeof(uint8), &data__et);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}


void PMainControllerStatusConjPort_setIdleTime(const PMainControllerStatusConjPort* self, uint8 data__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PMainControllerStatusConjPort", "setIdleTime")
		etPort_sendMessage(self, PMainControllerStatus_IN_setIdleTime, sizeof(uint8), &data__et);
	ET_MSC_LOGGER_SYNC_EXIT
}

void PMainControllerStatusConjReplPort_setIdleTime_broadcast(const PMainControllerStatusConjReplPort* self, uint8 data__et) {
	int i;
	ET_MSC_LOGGER_SYNC_ENTRY("PMainControllerStatusConjReplPort", "setIdleTime")
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		etPort_sendMessage((&((etReplPort*)self)->ports[i].port), PMainControllerStatus_IN_setIdleTime, sizeof(uint8), &data__et);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

void PMainControllerStatusConjReplPort_setIdleTime(const PMainControllerStatusConjReplPort* self, int idx__et, uint8 data__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PMainControllerStatusConjReplPort", "setIdleTime")
	if (0<=idx__et && idx__et<((etReplPort*)self)->size) {
		etPort_sendMessage((&((etReplPort*)self)->ports[idx__et].port), PMainControllerStatus_IN_setIdleTime, sizeof(uint8), &data__et);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}


void PMainControllerStatusConjPort_requestIdle(const PMainControllerStatusConjPort* self) {
	ET_MSC_LOGGER_SYNC_ENTRY("PMainControllerStatusConjPort", "requestIdle")
		etPort_sendMessage(self, PMainControllerStatus_IN_requestIdle, 0, NULL);
	ET_MSC_LOGGER_SYNC_EXIT
}

void PMainControllerStatusConjReplPort_requestIdle_broadcast(const PMainControllerStatusConjReplPort* self) {
	int i;
	ET_MSC_LOGGER_SYNC_ENTRY("PMainControllerStatusConjReplPort", "requestIdle")
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		etPort_sendMessage((&((etReplPort*)self)->ports[i].port), PMainControllerStatus_IN_requestIdle, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

void PMainControllerStatusConjReplPort_requestIdle(const PMainControllerStatusConjReplPort* self, int idx__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PMainControllerStatusConjReplPort", "requestIdle")
	if (0<=idx__et && idx__et<((etReplPort*)self)->size) {
		etPort_sendMessage((&((etReplPort*)self)->ports[idx__et].port), PMainControllerStatus_IN_requestIdle, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}


void PMainControllerStatusConjPort_requestFloor(const PMainControllerStatusConjPort* self) {
	ET_MSC_LOGGER_SYNC_ENTRY("PMainControllerStatusConjPort", "requestFloor")
		etPort_sendMessage(self, PMainControllerStatus_IN_requestFloor, 0, NULL);
	ET_MSC_LOGGER_SYNC_EXIT
}

void PMainControllerStatusConjReplPort_requestFloor_broadcast(const PMainControllerStatusConjReplPort* self) {
	int i;
	ET_MSC_LOGGER_SYNC_ENTRY("PMainControllerStatusConjReplPort", "requestFloor")
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		etPort_sendMessage((&((etReplPort*)self)->ports[i].port), PMainControllerStatus_IN_requestFloor, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

void PMainControllerStatusConjReplPort_requestFloor(const PMainControllerStatusConjReplPort* self, int idx__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PMainControllerStatusConjReplPort", "requestFloor")
	if (0<=idx__et && idx__et<((etReplPort*)self)->size) {
		etPort_sendMessage((&((etReplPort*)self)->ports[idx__et].port), PMainControllerStatus_IN_requestFloor, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

etInt32 PMainControllerStatusConjReplPort_getReplication(const PMainControllerStatusConjReplPort* self) {
	return ((etReplPort*)self)->size;
}



