/**
 * @author generated by eTrice
 *
 * Header File of ProtocolClass PStartGenerator
 * 
 */

#ifndef _ELEVATORFREERTOS_MODEL_PSTARTGENERATOR_H_
#define _ELEVATORFREERTOS_MODEL_PSTARTGENERATOR_H_

#include "etDatatypes.h"
#include "modelbase/etPort.h"




/* message IDs */
enum PStartGenerator_msg_ids {
	PStartGenerator_MSG_MIN = 0,
	PStartGenerator_OUT_check = 1,
	PStartGenerator_OUT_checkDoorStatus = 2,
	PStartGenerator_IN_requestCheck = 3,
	PStartGenerator_IN_requestCheckDoorStatus = 4,
	PStartGenerator_MSG_MAX = 5
};

/*--------------------- port structs and methods */
typedef etPort PStartGeneratorPort;
typedef etReplPort PStartGeneratorReplPort;


void PStartGeneratorPort_check(const PStartGeneratorPort* self);
void PStartGeneratorReplPort_check_broadcast(const PStartGeneratorReplPort* self);
void PStartGeneratorReplPort_check(const PStartGeneratorReplPort* self, int idx);
void PStartGeneratorPort_checkDoorStatus(const PStartGeneratorPort* self);
void PStartGeneratorReplPort_checkDoorStatus_broadcast(const PStartGeneratorReplPort* self);
void PStartGeneratorReplPort_checkDoorStatus(const PStartGeneratorReplPort* self, int idx);


etInt32 PStartGeneratorReplPort_getReplication(const PStartGeneratorReplPort* self);
typedef etPort PStartGeneratorConjPort;
typedef etReplPort PStartGeneratorConjReplPort;


void PStartGeneratorConjPort_requestCheck(const PStartGeneratorConjPort* self);
void PStartGeneratorConjReplPort_requestCheck_broadcast(const PStartGeneratorConjReplPort* self);
void PStartGeneratorConjReplPort_requestCheck(const PStartGeneratorConjReplPort* self, int idx);
void PStartGeneratorConjPort_requestCheckDoorStatus(const PStartGeneratorConjPort* self);
void PStartGeneratorConjReplPort_requestCheckDoorStatus_broadcast(const PStartGeneratorConjReplPort* self);
void PStartGeneratorConjReplPort_requestCheckDoorStatus(const PStartGeneratorConjReplPort* self, int idx);


etInt32 PStartGeneratorConjReplPort_getReplication(const PStartGeneratorConjReplPort* self);



#endif /* _ELEVATORFREERTOS_MODEL_PSTARTGENERATOR_H_ */

