/**
 * @author generated by eTrice
 *
 * Source File of ProtocolClass PStartGenerator
 * 
 */

#include "PStartGenerator.h"
#include "debugging/etMSCLogger.h"
#include "PStartGenerator_Utils.h"


/*--------------------- port methods */

void PStartGeneratorPort_check(const PStartGeneratorPort* self) {
	ET_MSC_LOGGER_SYNC_ENTRY("PStartGeneratorPort", "check")
		etPort_sendMessage(self, PStartGenerator_OUT_check, 0, NULL);
	ET_MSC_LOGGER_SYNC_EXIT
}

void PStartGeneratorReplPort_check_broadcast(const PStartGeneratorReplPort* self) {
	int i;
	ET_MSC_LOGGER_SYNC_ENTRY("PStartGeneratorReplPort", "check")
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		etPort_sendMessage((&((etReplPort*)self)->ports[i].port), PStartGenerator_OUT_check, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

void PStartGeneratorReplPort_check(const PStartGeneratorReplPort* self, int idx__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PStartGeneratorReplPort", "check")
	if (0<=idx__et && idx__et<((etReplPort*)self)->size) {
		etPort_sendMessage((&((etReplPort*)self)->ports[idx__et].port), PStartGenerator_OUT_check, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}


void PStartGeneratorPort_checkDoorStatus(const PStartGeneratorPort* self) {
	ET_MSC_LOGGER_SYNC_ENTRY("PStartGeneratorPort", "checkDoorStatus")
		etPort_sendMessage(self, PStartGenerator_OUT_checkDoorStatus, 0, NULL);
	ET_MSC_LOGGER_SYNC_EXIT
}

void PStartGeneratorReplPort_checkDoorStatus_broadcast(const PStartGeneratorReplPort* self) {
	int i;
	ET_MSC_LOGGER_SYNC_ENTRY("PStartGeneratorReplPort", "checkDoorStatus")
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		etPort_sendMessage((&((etReplPort*)self)->ports[i].port), PStartGenerator_OUT_checkDoorStatus, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

void PStartGeneratorReplPort_checkDoorStatus(const PStartGeneratorReplPort* self, int idx__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PStartGeneratorReplPort", "checkDoorStatus")
	if (0<=idx__et && idx__et<((etReplPort*)self)->size) {
		etPort_sendMessage((&((etReplPort*)self)->ports[idx__et].port), PStartGenerator_OUT_checkDoorStatus, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

etInt32 PStartGeneratorReplPort_getReplication(const PStartGeneratorReplPort* self) {
	return ((etReplPort*)self)->size;
}



void PStartGeneratorConjPort_requestCheck(const PStartGeneratorConjPort* self) {
	ET_MSC_LOGGER_SYNC_ENTRY("PStartGeneratorConjPort", "requestCheck")
		etPort_sendMessage(self, PStartGenerator_IN_requestCheck, 0, NULL);
	ET_MSC_LOGGER_SYNC_EXIT
}

void PStartGeneratorConjReplPort_requestCheck_broadcast(const PStartGeneratorConjReplPort* self) {
	int i;
	ET_MSC_LOGGER_SYNC_ENTRY("PStartGeneratorConjReplPort", "requestCheck")
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		etPort_sendMessage((&((etReplPort*)self)->ports[i].port), PStartGenerator_IN_requestCheck, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

void PStartGeneratorConjReplPort_requestCheck(const PStartGeneratorConjReplPort* self, int idx__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PStartGeneratorConjReplPort", "requestCheck")
	if (0<=idx__et && idx__et<((etReplPort*)self)->size) {
		etPort_sendMessage((&((etReplPort*)self)->ports[idx__et].port), PStartGenerator_IN_requestCheck, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}


void PStartGeneratorConjPort_requestCheckDoorStatus(const PStartGeneratorConjPort* self) {
	ET_MSC_LOGGER_SYNC_ENTRY("PStartGeneratorConjPort", "requestCheckDoorStatus")
		etPort_sendMessage(self, PStartGenerator_IN_requestCheckDoorStatus, 0, NULL);
	ET_MSC_LOGGER_SYNC_EXIT
}

void PStartGeneratorConjReplPort_requestCheckDoorStatus_broadcast(const PStartGeneratorConjReplPort* self) {
	int i;
	ET_MSC_LOGGER_SYNC_ENTRY("PStartGeneratorConjReplPort", "requestCheckDoorStatus")
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		etPort_sendMessage((&((etReplPort*)self)->ports[i].port), PStartGenerator_IN_requestCheckDoorStatus, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

void PStartGeneratorConjReplPort_requestCheckDoorStatus(const PStartGeneratorConjReplPort* self, int idx__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("PStartGeneratorConjReplPort", "requestCheckDoorStatus")
	if (0<=idx__et && idx__et<((etReplPort*)self)->size) {
		etPort_sendMessage((&((etReplPort*)self)->ports[idx__et].port), PStartGenerator_IN_requestCheckDoorStatus, 0, NULL);
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

etInt32 PStartGeneratorConjReplPort_getReplication(const PStartGeneratorConjReplPort* self) {
	return ((etReplPort*)self)->size;
}



